test/test.py
test/test_transforms.py
torchaudio/__init__.py
torchaudio/datasets/vctk.py
torchaudio/datasets/yesno.py
torchaudio/transforms.py
tox.ini

also fix lint across the project

Add docstrings for load and save

---

torchaudio/__init__.py

Fixes following the tensor/variable merge.
Tests pass with latest version of PyTorch now.
@soumith @colesbury

Fixes after tensor/variable merge

---

test/test_transforms.py
torchaudio/transforms.py

Re-committing #23 , now that 0.4 is released

mel spectrograms in pytorch (no longer req librosa)

---

torchaudio/transforms.py

fixes for 0.4

---

torchaudio/datasets/vctk.py
torchaudio/datasets/yesno.py

Small fix of the issue, that in order to download the dataset, the whole archive was loaded into the memory and only then unloaded to disk.

Download of dataset requires to hold archive in memory

---

torchaudio/transforms.py

The `stft` signature is being changed in https://github.com/pytorch/pytorch/pull/9497 (landing rn) to be consistent with `librosa`. This patch updates `transforms. SPECTROGRAM` so the behavior still matches the doc. (actually behavior changed because doc says `pad` pads on both size but the previous behavior only pads at the end). Note that the new `stft` support richer options, so cc @dhpollack on whether to update `SPECTROGRAM`.
An identical patch is also landing to facebook internal `torchaudio`.

Update torch audio for new stft signature

---

test/test.py
torchaudio/__init__.py
torchaudio/torch_sox.cpp
torchaudio/torch_sox.h

This is a rewrite of pull request #17 with the new cpp interface and the ability to save files with a bit precision other than 32-bit.  I also left the normalization parameter in.

allow loading with offsets and num_frames and saving specified bit precision

---

test/test_transforms.py
torchaudio/transforms.py

Found another bug in the MEL2 transform if `n_fft` was set.  The approximation of the filterbank matrix triangles was not optimal, so a better approximation of the triangles is now used.  I also created a few more tests.

fix MEL2 and update filterbank conversion matrix

---

torchaudio/datasets/vctk.py

[DOC][MINOR] Doc string update use audio instead of PIL

---

torchaudio/functional.py
torchaudio/transforms.py

T44497670 Refactor transforms.py into functional.py.

Migrate audio transform computations into functional.py

---

test/compliance/generate_fbank_data.py
test/compliance/generate_test_stft_data.py

https://github.com/pytorch/audio/pull/127
-in the generation of data, we should use logging instead of print and pass a command line argument 
-in the generation of data, we should not remove files by default

Quick cleanup of kaldi fbank

---

.gitignore
docs/source/conf.py
docs/source/functional.rst
docs/source/index.rst
torchaudio/functional.py

Documentation for torch.functional

torch.functional Docs

---

README.md

Let's mention how to install sox through Anaconda in README, #133.

Mention how to install sox through Anaconda in README

---

.gitignore
build_tools/travis/install.sh
setup.py
test/test_transforms.py
torchaudio/__init__.py

From pytorch [__init__.py](https://github.com/pytorch/pytorch/blob/master/torch/__init__.py) and [setup.py](https://github.com/pytorch/pytorch/blob/798d5d9771412bea95b44a0c8eb72337cbf73c81/setup.py#L284), they generate version.py and expose it to the user.
This would be useful in torchaudio to see which what configuration is currently installed

Adding __version__, git_version to torchaudio

---

test/compliance/test_kaldi.py
torchaudio/compliance/kaldi.py

Fix for https://github.com/pytorch/audio/issues/153

Multichannel Resample

---

build_tools/packaging/README.md
build_tools/packaging/conda/build_audio.sh
build_tools/packaging/conda/torchaudio/meta.yaml
build_tools/packaging/wheel/build_from_source.sh
build_tools/packaging/wheel/linux_manywheel.sh
build_tools/packaging/wheel/osx_wheel.sh

Put packaging scripts from 0.2.0 branch to master.

---

torchaudio/torch_sox.cpp

@thomasbrandon I took the liberty of opening up this PR for you.

Fix segfault passing null to sox_close

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/questions-help-support.md

Based on https://github.com/pytorch/pytorch/blob/master/.github/ISSUE_TEMPLATE/, we want contributors to have a template for writing issues

Creating an Issue Template

---

setup.py

Make it possible to change the name of torch (e.g., to torch_nightly)

---

build_tools/packaging/wheel/build_from_source.sh

Build mad as part of dependency build process of packaging.

---

build_tools/packaging/README.md
build_tools/packaging/wheel/build_from_source.sh
setup.py

Small README tweak.
https://github.com/pytorch/audio/commit/d3fe2a77854e4b45867a7353a8d135eedf785b9f
Make it possible to change the name of torch (e.g., to torch_nightly). https://github.com/pytorch/audio/pull/176
Build mad as part of dependency build process of packaging. https://github.com/pytorch/audio/pull/179

Moving commits from master to v0.2.0

---

setup.py

Link against mad in setup.py

---

test/test.py
test/test_compliance_kaldi.py
test/test_dataloader.py
test/test_datasets_vctk.py
test/test_functional.py
test/test_kaldi_io.py
test/test_legacy.py
test/test_sox_effects.py
test/test_transforms.py

https://github.com/pytorch/audio/pull/186

Make test scripts runnable without being modules

---

README.md

Binary install instructions.

---

README.md

https://github.com/pytorch/audio/pull/190

Binary install instructions

---

build_tools/packaging/wheel/linux_manywheel.sh
build_tools/packaging/wheel/osx_wheel.sh
setup.py

Support for building nightlies on master.

---

test/test_jit.py
torchaudio/functional.py

Add missing from __future__ import division.

---

build_tools/packaging/wheel/osx_wheel.sh

https://github.com/pytorch/audio/pull/199
I think we forgot to revert the deletion

Packaging improvements for 0.2.0 

---

.travis.yml
requirements.txt
test/common_utils.py
test/compliance/generate_fbank_data.py
test/compliance/generate_test_stft_data.py
test/compliance/utils.py
test/test.py
test/test_compliance_kaldi.py
test/test_dataloader.py
test/test_datasets_vctk.py
test/test_functional.py
test/test_jit.py
test/test_kaldi_io.py
test/test_sox_effects.py
test/test_transforms.py
torchaudio/__init__.py
torchaudio/_docs.py
torchaudio/common_utils.py
torchaudio/compliance/kaldi.py
torchaudio/datasets/vctk.py
torchaudio/datasets/yesno.py
torchaudio/functional.py
torchaudio/kaldi_io.py
torchaudio/sox_effects.py
torchaudio/transforms.py

https://github.com/pytorch/audio/pull/209

Make torchaudio work on Python 2. 

---

build_tools/packaging/conda/build_audio.sh
build_tools/packaging/conda/torchaudio/build.sh
build_tools/packaging/conda/torchaudio/meta.yaml
build_tools/packaging/wheel/build_from_source.sh
build_tools/packaging/wheel/linux_manywheel.sh
build_tools/packaging/wheel/osx_wheel.sh
setup.py

https://github.com/pytorch/audio/pull/203
https://github.com/pytorch/audio/commit/a8bd18dab1d3527da835d4ace72f43c94997abaf
from master to v0.3.0

Conda nightly packaging updates and Add missing build script.

---

.circleci/config.yml
.gitignore
build_tools/packaging/README.md
build_tools/packaging/conda/build_audio.sh
build_tools/packaging/conda/get-latest.py
build_tools/packaging/wheel/linux_manywheel.sh

Add CircleCI pipeline for Linux binary builds.

---

.circleci/config.yml

Attempt OS X binaries

---

packaging/build_conda.sh
packaging/build_wheel.sh

I forgot to call this in the scripts here

Setup cuda_suffix

---

packaging/pkg_helpers.bash

Updates from vision (ported from 0.3.0)

---

packaging/build_conda.sh
packaging/build_wheel.sh
packaging/pkg_helpers.bash

Refactor version suffix so conda packages don't get suffixes.

---

packaging/build_conda.sh
packaging/build_wheel.sh
packaging/pkg_helpers.bash

* Refactor version suffix so conda packages don't get suffixes.

Refactor version suffix so conda packages don't get suffixes. (#223)

---

.circleci/config.yml
.circleci/config.yml.in
.travis.yml

CI Fix: Remove Python 3.7

---

torchaudio/functional.py

https://github.com/pytorch/audio/issues/240
the window tensor should be the same device as the stft matrix

ISTFT window device for #240

---

torchaudio/compliance/kaldi.py

The resampler was not working with cuda tensors, due to some tensors in the way that were not put to the input device.

fixed resample to work with cuda tensors

---

torchaudio/__init__.py
torchaudio/sox_effects.py

Addresses https://github.com/pytorch/audio/issues/98

Small documentation tweak of [0, 1] to [-1, 1]

---

README.md
test/test_functional.py
test/test_jit.py
torchaudio/functional.py
torchaudio/transforms.py

Fixes to address issue https://github.com/pytorch/audio/issues/292

Fix mel filter bank

---

.circleci/config.yml
.circleci/config.yml.in

Push-based nightlies

---

torchaudio/functional.py

Update functional to be jit script, as discussed [here](https://github.com/pytorch/audio/pull/315#issuecomment-548604295).

make all functional jit script

---

.circleci/config.yml
.circleci/config.yml.in

soumith -> pytorch for docker images

---

torchaudio/functional.py

Fix python 2 flake8 error with character encoding.

fix python 2 flake8 error with character encoding

---

torchaudio/functional.py
torchaudio/transforms.py

* Revert #282.
* Use standard infinitive form for first verb.
* Standardize spacing in one place.
Tested locally, and all signature show properly in `audio/docs/build/html/functional.html`.

Remove explicit signature.

---

.circleci/config.yml
.circleci/config.yml.in

original setting is to download binaries from pypi or conda repo based on html file generated, which might not use the one just build. Which might give use false signal.
test run result is: https://github.com/pytorch/audio/pull/364/checks?check_run_id=342841117

Better smoke test

---

torchaudio/functional.py

Just a minor pull request, I don't see the need for the  complexity in the original code for `amplitude_to_DB`

Simpler amplitude_to_DB

---

README.md
test/test_transforms.py

Minor fixes to documentation and tests for `MelScale`.

Fix MelScale test and documentation

---

test/test_compliance_kaldi.py
test/test_transforms.py
torchaudio/compliance/kaldi.py

Make `resample_waveform` jitable.

JIT resample waveform

---

torchaudio/functional.py

Create directly on device for #365.
Tested on GPU device.

create tensor directly on device.

---

torchaudio/functional.py

Use standard naming from [readme](https://github.com/pytorch/audio/blob/master/README.md/).

use standard naming.

---

test/test_functional.py

* Move jitability test to TestFunctional.
* Remove typo in some jitability test.
* Test `dither` and `mask_along_axis_iid` for shape only due to randomness, and for two channels.

Move jitability test

---

torchaudio/datasets/vctk.py
torchaudio/datasets/yesno.py

DeprecationWarning are hidden by default. Upgrading to UserWarning.

Upgrading to UserWarning so that the user gets the warning.

---

.circleci/config.yml
.circleci/config.yml.in

Version bump to 0.4.0.
For reference: [0.3.2](https://github.com/pytorch/audio/pull/354#issue-345440580) and #407.

Update version number to v0.4.0

---

torchaudio/functional.py
torchaudio/transforms.py

Replace reshape by view when batching since batching shouldn't require copying the data., as mentioned in [comment](https://github.com/pytorch/audio/pull/391#discussion_r366004960).

replace reshape by view

---

test/test_transforms.py

Adding missing test to cover all 13 transforms with cuda test.

add cuda test for complex norm

---

torchaudio/datasets/librispeech.py

Adding dev-other option in librispeech, see [here](http://www.openslr.org/12/).

adding dev-other.

---

test/test_transforms.py
torchaudio/transforms.py

batch resample transform

---

test/test_transforms.py
torchaudio/compliance/kaldi.py

* Testing resample jit instead of spectrogram. 
* Remove custom gcd command since python2.7 is deprecated
Closes #440

jit scripting for resample

---

docs/source/functional.rst
test/test_functional_filtering.py
torchaudio/functional.py

Add `allpass` filter to functional module. #443

Add allpass filter to functional

---

test/test_transforms.py

Add batch test to TimeStretch transformation

add batch test to TimeStretch

---

README.md
docs/source/transforms.rst
test/test_sox_effects.py
test/test_transforms.py
torchaudio/functional.py
torchaudio/transforms.py

Relates to #260 
- Add transform to mimic Sox Vol effect
- Add tests to compare with Sox

Add Vol Transformation

---

test/test_functional.py
torchaudio/functional.py

- Add functional DB_to_amplitude
- Add tests to functional DB_to_amplitude

Add Functional DB_to_amplitude

---

torchaudio/transforms.py

relates to #477
- Add inline typing to transforms
- Update docstrings according to inline typing

Inline typing transforms

---

packaging/torchaudio/meta.yaml

Only test with cpu-only binaries

---

torchaudio/datasets/utils.py
torchaudio/datasets/vctk.py

[BC breaking] fix issue with VCTK dataset

---

test/test_torchscript_consistency.py
test/test_transforms.py

This PR is derived from #466. 
It extracts torchscript consistency test from `test_transforms` module and put them in a dedicated module/class (`test_torchscript::TestTransforms`).

Extract JIT tests from test_transforms to the dedicated test module

---

torchaudio/compliance/kaldi.py

- Add inline typing to compliance kaldi
- Minor fixes on docstrings
- Minor fixes for Flake8 rules
cc #477

Inline typing Compliance Kaldi

---

test/compliance/generate_fbank_data.py
test/compliance/generate_test_stft_data.py
test/test_datasets.py
test/test_transforms.py
torchaudio/__init__.py

Relates to #494 
This fixes B007, B008, B009 reported by flake8 bugbear plugin. (F821 and F841 are fixed in #504)

Fix flake8-bugbear lint errors

---

torchaudio/datasets/commonvoice.py
torchaudio/datasets/librispeech.py
torchaudio/datasets/ljspeech.py
torchaudio/datasets/speechcommands.py
torchaudio/datasets/vctk.py
torchaudio/datasets/yesno.py

Add inline typing to Datasets
relates to: #477

Datasets inline typing

---

test/test_batch_consistency.py

The helper functions in batch test have duplicated code and confusing names. This PR refactors them and improve the readability (thus maintainability).

Cleanup batch test

---

test/test_torchscript_consistency.py

Similar to #519 
This refactors helper function in `test_torchscript_consistency` module and improves readability.

Refactor torchscript test helper function

---

torchaudio/common_utils.py
torchaudio/datasets/utils.py

add inline typing to `utils` dataset and `common_utils`
relates to: #477

Inline typing utils dataset

---

test/test_torchscript_consistency.py

Currently torchscript tests for Transforms module runs GPU tests optionally when GPU is available.
This makes it hard for understand what test is ran/skipped/success/fail.
This PR separates CPU test and GPU test and make them explicit in test report.
Relates to #515 
[<img width="735" alt="Screen Shot 2020-04-07 at 13 25 46" src="https://user-images.githubusercontent.com/855818/78700457-5bb14c00-78d3-11ea-9e2b-24a75b1df0c2.png">](https://travis-ci.org/github/pytorch/audio/jobs/672182174)

Separate CPU and GPU tests for Transforms torchscript test

---

torchaudio/kaldi_io.py

relates to: #477 
- Add inline typing kaldi_io module

add inline Typing kaldi_io

---

README.md

Fixes #545 as mentioned [here](https://github.com/pytorch/audio/pull/547#issuecomment-613741627).

add --pre flag

---

packaging/build_conda.sh
packaging/build_wheel.sh
setup.py

cc @vincentqb @cpuhrsch @seemethere @soumith

Bump master version to 0.6.0

---

test/common_utils.py

`random_int_tensor` is defined but not used.

Remove unused helper function

---

test/test_batch_consistency.py
torchaudio/functional.py

This is the simplified version of #560 where changes related to batch consistency are imported.

Make sliding_window_cmn batch-aware

---

torchaudio/_backend.py

Do not offer sox as a backend in windows

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/unittest/run_test.sh

This PR adds test reports to CCI. CCI could give us some insights on our tests. https://circleci.com/build-insights

Add test result on CCI

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/unittest/environment.yml
.circleci/unittest/post_process.sh
.circleci/unittest/run_test.sh

This enables coverage repot on PR.

Enable coverage report

---

.circleci/unittest/scripts/run_test.sh

Run flake8 in CCI unittest

---

test/test_kaldi_compatibility.py

Adding the test I wrote while investigating #400.

Add compatibility test for `compute-fbank-feats`

---

torchaudio/functional.py
torchaudio/transforms.py

Resolves #555
cc. @Ektoplasmakugel

Fix docstring of masking behavior

---

test/test_batch_consistency.py

Change for  https://github.com/pytorch/audio/issues/610.

make seed parameterized in test_batch_consistency

---

setup.py
torchaudio/torch_sox.cpp
torchaudio/torch_sox.h

Remove multiple definitions of `SoxEffect`.

---

test/test_batch_consistency.py

Adopt PyTorch's test util to batch consistency test

---

test/common_utils.py
test/torchscript_consistency_impl.py

and remove I/O from torchscript test.

Add util to generate whitenoise

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py

tested at https://github.com/pytorch/audio/pull/656

Add windows smoke test job to CI

---

README.md

See: https://github.com/mthrok/audio/blob/version-matrix/README.md#dependencies

Add compatible version matrix

---

torchaudio/__init__.py
torchaudio/sox_effects.py

For better [cohesion and coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)#:~:text=Coupling%20versus%20cohesion,-Coupling%20and%20cohesion&text=Coupling%20refers%20to%20the%20interdependencies,as%20the%20module%20becomes%20large.), move sox_effects related functions to sox_effects module.
Then perform initialization in `__init__.py`.

Move sox effect init/shut down to sox_effects module

---

torchaudio/functional.py

Fixes #684 
Issue due to   ```_generate_wave_table``` helper  function . Made it device aware .
Refactored both ```flanger``` and ```phaser``` functions that use this helper function.

Flanger and phaser GPU fix

---

torchaudio/functional.py

Remove in-place operations from GriffinLim for backprop

---

packaging/build_conda.sh
packaging/build_wheel.sh
setup.py

bump nightly versions to 0.7.0

---

.circleci/config.yml
.circleci/config.yml.in
packaging/pkg_helpers.bash

These were changes that were made in the process of releasing `v0.6.0-rc1`

Cherry picking changes for release improvements

---

test/test_datasets.py

See https://github.com/pytorch/audio/pull/772#issuecomment-657218491

Remove sox backend for one test, followup from Issue 764

---

torchaudio/models/_wavernn.py

This is to fix the output type of upsampling block.
Related to #724

Fix output type of upsampling

---

docs/source/models.rst

Add WaveRNN model name in docs.

Add model name in docs

---

.circleci/unittest/linux/scripts/environment.yml
.circleci/unittest/windows/scripts/environment.yml

librosa 0.8.0 has been released which include fix for https://github.com/librosa/librosa/issues/1160 (https://github.com/librosa/librosa/pull/1164)

Update librosa/numba in CI

---

test/torchaudio_unittest/torchscript_consistency_impl.py
torchaudio/functional.py

Fix dither with noise_shaping = True

---

docs/source/datasets.rst
test/torchaudio_unittest/datasets/vctk_test.py
torchaudio/datasets/__init__.py
torchaudio/datasets/vctk.py

add vctk_test for VCTK dataset based on #812 PR. The unit test is based on the changes from #812.

add vctk_test for VCTK dataset based on #812 PR

---

examples/interactive_asr/utils.py

Fixes #309 and a crash due to the added argument models in the call to task.build_generator in examples/interactive_asr/utils.py

Fix interactive asr

---

torchaudio/backend/utils.py

Add deprecation warning to sox backend

---

torchaudio/backend/soundfile_backend.py
torchaudio/backend/sox_backend.py
torchaudio/backend/sox_io_backend.py

Add deprecation warnings to load_wav functions

---

docs/source/models.rst
torchaudio/models/conv_tasnet.py

Add conv-tasnet to models documentation.

Update model documentation

---

test/torchaudio_unittest/models_test.py
torchaudio/models/__init__.py

removing * imports for models based on offline discussion with @mthrok.

remove * in import of models

---

.circleci/unittest/windows/scripts/environment.yml

Fix Windows unit tests

---

test/torchaudio_unittest/common_utils/backend_utils.py
test/torchaudio_unittest/datasets/tedlium_test.py
torchaudio/datasets/tedlium.py

fix tedlium load_audio

---

torchaudio/transforms.py

[doc] Update librosa link

---

test/torchaudio_unittest/datasets/tedlium_test.py

Fix flake8 error

---

torchaudio/compliance/kaldi.py

The old version computes fbank as follows:
```
power_spectrum = power_spectrum.unsqueeze(1) 
mel_energies = mel_energies.unsqueeze(0)
mel_energies = (power_spectrum * mel_energies).sum(dim=2)
```
It equals:
```
mel_energies = torch.mm(power_spectrum, mel_energies.T).
```
Speed of computing 30s audios: 0.24s --> 0.06s.

Improve the speed of torchaudio.compliance.kaldi.fbank

---

.circleci/config.yml
.circleci/config.yml.in

Cherry-picking #952 to master branch.

Cherry-pick 'Upload to "test" channel on release branch (#952)'

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/windows/scripts/install.sh

This is necessary/useful for the future release too.

Cherry-pick 'Use PyTorch RC for unittest in release branch (#953)'

---

.circleci/config.yml
.circleci/config.yml.in

EDIT: needs to go to master branch too.

Fix binary smoke test

---

docs/source/index.rst

Adds introductory context and links to the PyTorch Libraries to audio docs.
Cherry-picked #968 for release/0.7

Update index.rst (#968)

---

torchaudio/backend/sox_backend.py

*Note:* this should also go to master branch.

Add deprecation warnings to libsox specific functions

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py

Fix GPU CI job setup.
Checkout the result here https://app.circleci.com/pipelines/github/pytorch/audio/3721/workflows/207722e6-8d5e-44f8-9e0f-71347a5b21ed.

Fix GPU CI setup

---

examples/pipeline_wav2letter/main.py

Remove print-freq option and compute validation loss at each epoch in wav2letter pipeline.
Fixes #995.

remove print-freq option in wav2letter pipeline

---

torchaudio/transforms.py

Fixes #1008 
Changed the code to pass `noise_down_time` parameter correclty

Fix 'noise_down_time' arg in VAD

---

test/torchaudio_unittest/datasets/cmuarctic_test.py
torchaudio/datasets/cmuarctic.py

Add pathlib.Path support to `cmuarctic`

---

test/torchaudio_unittest/datasets/ljspeech_test.py
test/torchaudio_unittest/datasets/vctk_test.py
torchaudio/datasets/ljspeech.py
torchaudio/datasets/vctk.py

Relates to #950 
Pathlib support added for both VCTK and LJSPEECH in this PR

Pathlib support for VCTK and LJSPEECH

---

test/torchaudio_unittest/datasets/gtzan_test.py
torchaudio/datasets/gtzan.py

Add pathlib.Path support to `gtzan`

---

.circleci/build_docs/commit_docs.sh

fix some typos in the script that prevented it from working

fix typos in commit_docs.sh script

---

torchaudio/functional/functional.py

Argument in griffinlim is not used

---

.circleci/build_docs/commit_docs.sh
.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py

Follow what is done in pytorch/pytorch to succeed at `git push`

add org-member context and generate a .netrc file for git push

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/windows/scripts/environment.yml
.circleci/unittest/windows/scripts/install.sh
packaging/pkg_helpers.bash

[v0.7.x] Add Python 3.9 support

---

torchaudio/datasets/commonvoice.py

After #1079, Cherry-pick #1076 into master branch.
See #1077 for the agenda.

Disallow download=True in CommonVoice

---

.circleci/build_docs/commit_docs.sh

force https by adding a https remote

---

test/torchaudio_unittest/datasets/utils_test.py
torchaudio/datasets/utils.py

Remove walk_files

---

torchaudio/backend/_soundfile_backend.py
torchaudio/backend/sox_io_backend.py

Hi @mthrok, this PR is in response to your comment [here](https://github.com/pytorch/audio/pull/1122#issuecomment-750491683)

[Doc] apply change to the return type for load functions

---

torchaudio/backend/_soundfile_backend.py

add format arg in new soundfile backend

---

test/torchaudio_unittest/datasets/vctk_test.py

refactor vctk unittest

---

test/torchaudio_unittest/datasets/speechcommands_test.py

refactor speechcommands unittest

---

test/torchaudio_unittest/datasets/librispeech_test.py

refactor librispeech unittest

---

test/torchaudio_unittest/datasets/tedlium_test.py

refactor tedlium unittest

---

test/torchaudio_unittest/datasets/ljspeech_test.py

Refactor LJSpeech unittest

---

test/torchaudio_unittest/datasets/libritts_test.py

Refactor LibriTTS unittest

---

test/torchaudio_unittest/datasets/cmuarctic_test.py

Refactor CMUARCTIC unittest

---

test/torchaudio_unittest/datasets/gtzan_test.py

Refactor GTZAN unittest

---

torchaudio/prototype/transducer.py

Fix small typo in transducer :)

Fix typo in transducer

---

.circleci/config.yml
.circleci/config.yml.in

Now that torchaudio has C++ code and caching Conda environment that includes compiler tool chain causes flaky behavior. This PR disables it.

Disable CircleCI cache

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/unittest/linux/docker/Dockerfile
.circleci/unittest/linux/scripts/install.sh

* Do not install system-wide sox, so that it would not get mixed up with static one torchaudio builds
* Do not install system-wide cmake. It's installed at test. 
* Move libsndfile installation to Docker image

Update unit test base Docker image

---

torchaudio/datasets/ljspeech.py

[Refactor][Dataset] LJSPEECH implementation

---

test/torchaudio_unittest/transforms_test.py
torchaudio/transforms.py

This PR tries to address issue #1203

Expose stft arguments to MelSpectrogram

---

torchaudio/transforms.py

This PR attempts to address issue #1207

Expose normalization method to Mel transforms

---

CONTRIBUTING.md
README.md
test/torchaudio_unittest/README.md

Closes https://github.com/pytorch/audio/issues/926
The guidelines are inspired from torchvision's guide, with some audio-specific guidelines.

Added CONTRIBUTING.md

---

test/torchaudio_unittest/transducer_test.py

This PR attempts to address issue #1251.

Fix transducer test

---

torchaudio/csrc/sox/effects_chain.cpp
torchaudio/csrc/sox/utils.cpp

Addresses https://github.com/pytorch/audio/issues/1265.

Replaced if-elseif-else with switch

---

versions.html

Add a version selector like in pytorch docs.

Add a versions.html page to choose versions

---

test/torchaudio_unittest/functional/librosa_compatibility_test.py
test/torchaudio_unittest/librosa_compatibility_test.py

feat: refactor librosa compatibility test

---

test/torchaudio_unittest/backend/sox_io/info_test.py
test/torchaudio_unittest/backend/sox_io/save_test.py
torchaudio/backend/sox_io_backend.py
torchaudio/csrc/sox/io.cpp
torchaudio/csrc/sox/types.cpp
torchaudio/csrc/sox/types.h
torchaudio/csrc/sox/utils.cpp

Cherrypicking #1276 & #1291 from the master branch

Added HTK format support to sox_io's save & info

---

docs/source/functional.rst
docs/source/transforms.rst
torchaudio/functional/functional.py

Apply #1316 on release branch.

[Release 0.8] Add missing functionals and transform to docs.

---

torchaudio/backend/common.py

Cherrypicking #1322 for 0.8 release.

[release/0.8] Update AudioMetaData docstring with encoding values

---

docs/source/functional.rst

Add subcategories to functional documentation

---

packaging/build_conda.sh
packaging/build_wheel.sh
setup.py

This will be merged after the release.

[Release 0.8] Bump master version number

---

0.8.0/functional.html

Rebuild the doc page for functional.py since it changed after the v0.8.0rc3 release. Follow on for gh-1354.

update functional to release/0.8

---

examples/interactive_asr/vad.py
examples/pipeline_wav2letter/languagemodels.py
test/torchaudio_unittest/compliance_kaldi_test.py

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/audio/issues). This PR fixes a few of them.
- Fixed implicit Object Inheritance
- Remove unnecessary use of comprehension 
- Consider merging these comparisons with 'in'
- Consider using max

Lint code style and remove PY2 compatibility

---

test/torchaudio_unittest/backend/sox_io/load_test.py

clean up `load_test.py` unit tests by reducing several `assert_XXX` functions into one main `assert_format` function

Refactor sox_io load_test

---

test/torchaudio_unittest/transforms/librosa_compatibility_test.py
torchaudio/functional/filtering.py

Some cause internal lint errors.
cc D26772272

fix a few typos

---

test/torchaudio_unittest/transforms/autograd_test_impl.py

Autograd tests for Transforms MFCC

---

.circleci/unittest/windows/scripts/environment.yml

State needed for shipit to cleanly apply patch

Sync environment.yml such that patch applies

---

test/torchaudio_unittest/transforms/autograd_test_impl.py

Add autograd test for T.Fade

---

test/torchaudio_unittest/transforms/autograd_test_impl.py

Add autograd test for T.SpectralCentroid

---

torchaudio/functional/functional.py

cc @mthrok 
This reverts commit 8d2eeb114e7f8a6659d132b98adb50d886108fb2.

Revert "Refactor implementation of F.compute_deltas (#1423)"

---

test/torchaudio_unittest/transforms/autograd_test_impl.py

Add autograd test for T.Vol

---

third_party/sox/CMakeLists.txt

Explicitly disable wavpack when building SoX

---

.circleci/config.yml
.circleci/config.yml.in

Should be moved back to stable once
https://github.com/pytorch/pytorch/issues/56654 is closed

Move windows GPU images to previous tag

---

test/torchaudio_unittest/common_utils/case_utils.py
test/torchaudio_unittest/functional/functional_cpu_test.py
test/torchaudio_unittest/functional/functional_cuda_test.py
test/torchaudio_unittest/functional/functional_impl.py
test/torchaudio_unittest/functional/torchscript_consistency_cpu_test.py
test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py
test/torchaudio_unittest/functional/torchscript_consistency_impl.py
test/torchaudio_unittest/transforms/torchscript_consistency_cpu_test.py
test/torchaudio_unittest/transforms/torchscript_consistency_cuda_test.py
test/torchaudio_unittest/transforms/torchscript_consistency_impl.py

Small refactor: Merge the complex Tensor test suites into the other Tensor test suites.

Merge test classes for complex

---

torchaudio/csrc/rnnt/cpu/compute.cpp
torchaudio/csrc/rnnt/gpu/compute.cu
torchaudio/prototype/rnnt_loss.py

move runtime checks for RNNT loss from python to C++
cc #1240

Migrate RNNTL input checks to C++

---

.github/workflows/codeql.yml

CodeQL failing changes

---

packaging/build_conda.sh
packaging/build_wheel.sh
setup.py

Now that branch for 0.9 release is created. We need to update the master version.

Update the master version to 0.10

---

torchaudio/prototype/rnnt_loss.py

add return type in documentation for rnnt loss

Add return type for RNNT loss

---

torchaudio/csrc/rnnt/autograd.cpp
torchaudio/csrc/rnnt/compute.cpp
torchaudio/csrc/rnnt/compute.h
torchaudio/csrc/rnnt/compute_alphas.cpp
torchaudio/csrc/rnnt/compute_betas.cpp
torchaudio/csrc/rnnt/cpu/compute.cpp
torchaudio/csrc/rnnt/cpu/compute_alphas.cpp
torchaudio/csrc/rnnt/cpu/compute_betas.cpp
torchaudio/csrc/rnnt/gpu/compute.cu
torchaudio/csrc/rnnt/gpu/compute_alphas.cu
torchaudio/csrc/rnnt/gpu/compute_betas.cu
torchaudio/prototype/rnnt_loss.py

rename variables in RNNT loss C++ code to be consistent with Python interface

Rename RNNT loss C++ parameters

---

test/torchaudio_unittest/rnnt/utils.py
torchaudio/prototype/rnnt_loss.py

add reduction argument for RNN transducer loss. options: mean (default), none, sum

Add reduction parameter for RNNT loss

---

.circleci/torchscript_bc_test/common.sh
.circleci/unittest/linux/scripts/install.sh
CMakeLists.txt
build_tools/setup_helpers/extension.py
examples/libtorchaudio/CMakeLists.txt
packaging/build_wheel.sh
packaging/torchaudio/build.sh
test/torchaudio_unittest/rnnt/autograd_cpu_test.py
test/torchaudio_unittest/rnnt/autograd_cuda_test.py
test/torchaudio_unittest/rnnt/rnnt_loss_cpu_test.py
test/torchaudio_unittest/rnnt/rnnt_loss_cuda_test.py
test/torchaudio_unittest/rnnt/torchscript_consistency_cpu_test.py
test/torchaudio_unittest/rnnt/torchscript_consistency_cuda_test.py
test/torchaudio_unittest/rnnt/utils.py
torchaudio/csrc/CMakeLists.txt

for consistency, use `RNNT` instead of `transducer` to refer to RNN transducer

Rename transducer to RNNT

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/windows/scripts/environment.yml
.circleci/unittest/windows/scripts/install.sh

Fix CircleCI environment

---

test/torchaudio_unittest/rnnt/autograd_impl.py
test/torchaudio_unittest/rnnt/rnnt_loss_impl.py
test/torchaudio_unittest/rnnt/utils.py

Summary of changes
- remove numpy dependencies
- replace usages of numpy testing
- use torch tensors for data instead of numpy 
- rename testing functions for consistency

Refactor RNNT Loss Unit Tests

---

examples/pipeline_tacotron2/text/numbers.py
examples/pipeline_tacotron2/text/test_text.py
examples/pipeline_tacotron2/text/text_preprocessing.py

Some of the preprocessing functions from [here](https://github.com/keithito/tacotron).

Add text preprocessing utilities for TTS pipeline

---

examples/pipeline_wavernn/inference.py
examples/pipeline_wavernn/wavernn_inference_wrapper.py

Following [this suggestion](https://github.com/pytorch/audio/pull/1637#discussion_r679210971).

Rename infer method to forward for WaveRNNInferenceWrapper

---

.circleci/unittest/linux/scripts/install.sh
packaging/pkg_helpers.bash
packaging/torchaudio/meta.yaml

Essentially copy-n-paste of https://github.com/pytorch/vision/pull/4203 into this repo
Fixes https://github.com/pytorch/pytorch/issues/62424

Pin MKL to 2021.2.0

---

torchaudio/__init__.py

Fix models import

---

examples/pipeline_tacotron2/datasets.py
examples/pipeline_wavernn/README.md

fix CI python style check failure, and convert tabs to spaces, which is blocking torchaudio import

Fix spacing

---

torchaudio/transforms.py

Example for Mu law encoding  

---

examples/pipeline_tacotron2/README.md
examples/pipeline_tacotron2/text/text_preprocessing.py
examples/pipeline_tacotron2/train.py
examples/pipeline_tacotron2/utils.py

Currently, it supports using [DeepPhonemizer](https://github.com/as-ideas/DeepPhonemizer) as the phonemizer since it is easy to install.

Add phoneme text preprocessing for Tacotron2

---

torchaudio/prototype/tacotron2.py

Add tacotron2 pretrained models

Add tacotron2 pretrained models

---

packaging/torchaudio/meta.yaml

Cherry pick of https://github.com/pytorch/audio/pull/1697 for 0.8 LTS release

[lts/release/1.8] packaging: Ensure we're propagating BUILD_VERSION (#1697) 

---

docs/source/functional.rst
docs/source/transforms.rst

Add docs for InverseSpectrogram

---

examples/pipeline_tacotron2/README.md
examples/pipeline_tacotron2/inference.py

An example for doing Tacotron2 inferencing.
#1642 #1648 should be merged before this can work.

Add an inference example for Tacotron2

---

.circleci/config.yml
.circleci/config.yml.in
packaging/windows/internal/cuda_install.bat

Copy `cuda_install.bat` from
https://github.com/pytorch/vision/blob/3d9d264198e2167030dc04bf453aeca47daa37db/packaging/windows/internal/cuda_install.bat
Add it to `binary_windows_wheel` and `binary_windows_conda` steps

Add CUDA install step to Win Packaging jobs

---

docs/source/functional.rst

https://318213-90321822-gh.circle-artifacts.com/0/docs/functional.html#metric

Add edit_distance to documentation with a new category Metric

---

.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/windows/scripts/install.sh

As a preparation for the HuBERT model integration.

Update the version of fairseq used for testing model

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py

Cherry-pick of
https://github.com/pytorch/vision/commit/d2460a75de237cfef8e5c3415f7bb0ad8467c0e5
into this repo
Fixes https://github.com/pytorch/audio/issues/1750

Upload wheels to respective folders

---

examples/pipeline_tacotron2/README.md

https://colab.research.google.com/drive/1MPcn1_G5lKozxZ7v8b9yucOD5X5cLK4j?usp=sharing

Add link to TTS colab example to README

---

examples/beamforming/mvdr.py

summary:
- The ``stv_power`` solution requires normalization of the steering vector to get the enhanced speech.
- Fix the iteration number to be consistence with [ESPNet implementation](https://github.com/espnet/espnet/blob/master/espnet2/enh/layers/beamformer.py#L97-L98).
- The Si-SDR results can be reproduced in https://github.com/nateanl/torchaudio_mvdr_tutorial
Before adding normalization, the Si-SDR results. The tutorial can be found [here](https://colab.research.google.com/drive/1x-ndCcC8VHZyXMCsTCJ-r7uP4fK2tRqu?usp=sharing)
```
ref_channel:  8.77162157407502
stv_evd:  4.864215687007221
stv_power:  -44.74227104483583
```
After adding normalization:
```
ref_channel:  8.771621920879326
stv_evd:  7.344749326823148
stv_power:  8.453569938642666
```

Add normalization to steering vector solutions in MVDR Module

---

build_tools/setup_helpers/extension.py
torchaudio/_extension.py
torchaudio/csrc/CMakeLists.txt
torchaudio/lib/.gitignore

To make the structure somewhat similar to PyTorch core, which has the following pattern
```
torch/_C.so
torch/lib/libc10.dylib
torch/lib/libtorch.dylib
...
```
```
torchaudio/_torchaudio.so
torchaudio/lib/libtorchaudio.so
```

Put libtorchaudio in lib directory 

---

examples/libtorchaudio/speech_recognition/README.md
test/torchaudio_unittest/assets/wav2vec2/fairseq/generate_fairseq_model_config.py

[Fbsync] Update URL for fairseq repo

---

torchaudio/transforms.py

Here is the view of the documentation:

[DOC] Add equations to MVDR Docstring

---

packaging/windows/internal/cuda_install.bat

update windows cuda installer 11.1.0 to 11.1.1

---

torchaudio/datasets/vctk.py

* It's been a while since VCTK is taken down.

Deprecate VCTK

---

test/torchaudio_unittest/models/wav2vec2/model_test.py

This one is failing as well. I am getting the impression that it's OOM.

Skip hubert_xlarge TS test on Windows

---

torchaudio/datasets/utils.py

Now that torchdata is public, deprecating the utilities.

Deprecate data utils

---

.circleci/config.yml
.circleci/config.yml.in

update circle ci torchaudio/pytorch versions for release

Set release version and base PyTorch version

---

docs/source/models.rst
test/integration_tests/wav2vec2_model_test.py
torchaudio/models/__init__.py
torchaudio/models/wav2vec2/pretrained.py

This commit adds
- HUBERT_LARGE
- HUBERT_XLARGE
- HUBERT_ASR_XLARGE

Add the rest of HuBERT pretrained models

---

docs/source/index.rst
docs/source/prototype.rst
docs/source/refs.bib
test/torchaudio_unittest/prototype/emformer_cpu_test.py
test/torchaudio_unittest/prototype/emformer_gpu_test.py
test/torchaudio_unittest/prototype/emformer_test_impl.py
torchaudio/prototype/__init__.py
torchaudio/prototype/emformer.py

Adds an implementation of Emformer, a memory-efficient transformer architecture introduced in https://ieeexplore.ieee.org/document/9414560 that targets low-latency streaming speech recognition applications.

Introduce Emformer

---

CITATION
README.md

Thanks @nateanl for uploading the [paper](https://arxiv.org/abs/2110.15018) to arxiv.
I've added the bibtex information in this PR.
Please check.
Thanks.

Add citation information

---

docs/source/index.rst

Add citation information in the documentation

---

0.10.0/index.html

https://mthrok.github.io/audio/0.10.0/index.html

Add citation to stable (0.10.0) doc

---

.github/process_commit.py
.github/workflows/pr-labels.yml

Reverts pytorch/audio#1964 as the resulting message only contains the first line.

Revert "Update PR label notifier"

---

_config.yml

This fixes the issue with image rendering
https://mthrok.github.io/audio/main/auto_examples/wav2vec2/index.html

Update Jekyll config to serve Sphinx-Gallery images and notebooks

---

docs/source/index.rst

- Add link to index page on left
- Package Reference -> API Reference
- Update description.
https://427463-90321822-gh.circle-artifacts.com/0/docs/index.html

Tweak index page

---

.circleci/config.yml
.circleci/config.yml.in

Release pytorch 1.10.2

---

.circleci/config.yml
.circleci/config.yml.in
.circleci/regenerate.py
.circleci/unittest/linux/scripts/install.sh
.circleci/unittest/linux/scripts/setup_env.sh
.circleci/unittest/windows/scripts/install.sh
.circleci/unittest/windows/scripts/setup_env.sh
packaging/build_conda.sh
packaging/pkg_helpers.bash
packaging/torchaudio/meta.yaml
test/torchaudio_unittest/common_utils/__init__.py
test/torchaudio_unittest/common_utils/case_utils.py
test/torchaudio_unittest/models/tacotron2/model_test_impl.py

[release/0.11] Add Python 3.10 (build and test) 

---

.github/workflows/build-m1-binaries.yml
packaging/pkg_helpers.bash

Summary:
Adding tagged builds for torchaudio
see: https://github.com/pytorch/vision/pull/6140
Pull Request resolved: https://github.com/pytorch/audio/pull/2471
Reviewed By: hwangjeff
Differential Revision: D37080828
fbshipit-source-id: 13d754f522510514f0148ba465ce12a320058722

Adding tagged builds to torchaudio (#2471)

---

.circleci/config.yml
.circleci/config.yml.in

Increase inactivity timeout

---

versions.html

Update stable version to 0.13.0

---

.github/workflows/build-conda-m1.yml
.github/workflows/build-wheels-m1.yml
.github/workflows/build_conda_linux.yml
.github/workflows/build_conda_macos.yml
.github/workflows/build_wheels_linux.yml
.github/workflows/build_wheels_macos.yml

This is temporarily hardcoded to unblock release, we will do this more cleanly in a follow-up.

Channel=test for build matrix generation

---

.github/workflows/build-conda-m1.yml
.github/workflows/build-conda-windows.yml
.github/workflows/build_conda_linux.yml
.github/workflows/build_conda_macos.yml

Cherry-pick of https://github.com/pytorch/audio/pull/3582.

[Cherry-Pick] Conda Test-specific Token

---

examples/avsr/lightning.py
examples/avsr/lightning_av.py
examples/avsr/train.py

Following #2981, this PR simplifies the training step in the AV-ASR recipe

Simplify trainining step in av-asr recipe

---

torchaudio/csrc/CMakeLists.txt
torchaudio/csrc/rir/ray_tracing.cpp
torchaudio/csrc/rir/wall.h

Taken from https://github.com/pytorch/audio/pull/3234

Add the rest of C++ ray tracing implementation

---

src/torchaudio/csrc/ffmpeg/pybind/pybind.cpp
src/torchaudio/io/_stream_reader.py
test/torchaudio_unittest/io/stream_reader_test.py

Add bytes support to StreamReader

---

docs/source/prototype.functional.rst
src/libtorchaudio/rir/ray_tracing.cpp
src/libtorchaudio/rir/wall.h
src/torchaudio/prototype/functional/__init__.py
src/torchaudio/prototype/functional/_rir.py
test/cpp/rir/wall_collision.cpp
test/torchaudio_unittest/prototype/functional/functional_test_impl.py
test/torchaudio_unittest/prototype/functional/pyroomacoustics_compatibility_test.py
test/torchaudio_unittest/prototype/functional/torchscript_consistency_test_impl.py

Summary:
Revamped version of https://github.com/pytorch/audio/pull/3234 (which was also revamp of https://github.com/pytorch/audio/pull/2850)

Add Ray Tracing (#3604)

---

src/torio/__init__.py
src/torio/_extension/__init__.py
src/torio/_extension/utils.py
src/torio/io/__init__.py
src/torio/io/_streaming_media_decoder.py
src/torio/io/_streaming_media_encoder.py
src/torio/utils/__init__.py
src/torio/utils/ffmpeg_utils.py

Add torio top-level directory. It's not part of the package yet.

Prep for restructure

---

cmake/TorchAudioHelper.cmake
src/libtorio/ffmpeg/CMakeLists.txt
src/libtorio/ffmpeg/pybind/pybind.cpp
src/torchaudio/_extension/utils.py
tools/setup_helpers/extension.py

Summary: Update FFmpeg library/extension name
Differential Revision: D50633306

Update library/extension name

---

docs/source/libtorio.stream_reader.rst
docs/source/libtorio.stream_writer.rst
src/libtorio/ffmpeg/README.md
src/libtorio/ffmpeg/pybind/pybind.cpp
src/libtorio/ffmpeg/stream_reader/stream_processor.cpp
src/libtorio/ffmpeg/stream_reader/stream_reader.cpp
src/libtorio/ffmpeg/stream_reader/stream_reader.h
src/libtorio/ffmpeg/stream_writer/encode_process.cpp
src/libtorio/ffmpeg/stream_writer/encoder.cpp
src/libtorio/ffmpeg/stream_writer/stream_writer.cpp
src/libtorio/ffmpeg/stream_writer/stream_writer.h
src/torio/io/_streaming_media_decoder.py
src/torio/io/_streaming_media_encoder.py

Differential Revision: D50696105

Update StreamReader/Writer name

---

docs/source/installation.rst

Add the new release to compatibility matrix.
Addresses #3689

Update version matrix

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md

to let people know that it's not monitored.

Update GH issue template

---

.github/workflows/ffmpeg.yml

https://github.com/pytorch/audio/actions/runs/7428999619

Update ffmpeg binary versions

---

.github/workflows/build_wheels_aarch64_linux.yml
.github/workflows/build_wheels_linux.yml
.github/workflows/build_wheels_macos.yml
.github/workflows/build_wheels_windows.yml

Cherry pick of : https://github.com/pytorch/audio/pull/3726

Use oidc for wheel workflows, remove aws credentials

---

.github/workflows/build-wheels-m1.yml
.github/workflows/build_wheels_aarch64_linux.yml
.github/workflows/build_wheels_linux.yml
.github/workflows/build_wheels_macos.yml

Cherry-pick https://github.com/pytorch/audio/pull/3743 to release/2.2 branch

Add oidc permissions to workflows

---

.github/workflows/build-wheels-m1.yml
.github/workflows/build_wheels_aarch64_linux.yml
.github/workflows/build_wheels_linux.yml
.github/workflows/build_wheels_macos.yml

Revert "Add oidc permissions to workflows"

---

.github/workflows/build-conda-m1.yml
.github/workflows/build-wheels-m1.yml
.github/workflows/ffmpeg.yml

Update labels for M1 runners

---

.github/scripts/unittest-windows/install.sh
README.md

Fix windows CI CPU and GPU tests by unpinning mkl version and installing pybind11

---

.github/scripts/unittest-windows/install.sh

Cherry pick #3766 
```
git pull
git checkout release/2.3
git checkout -b cp_ea437b3
git cherry-pick ea437b3
git push ahmadsharif1
```

[RELEASE-ONLY CHANGES for 2.3] cherry-pick ea437b3 to fix windows CI

---

.github/workflows/build_wheels_windows.yml
packaging/vc_env_helper.bat

Depends on https://github.com/pytorch/test-infra/pull/5648
Works for https://github.com/pytorch/pytorch/issues/114850

Enable xpu windows CD

---

src/libtorchaudio/rnnt/gpu/gpu_kernel_utils.cuh
src/libtorchaudio/rnnt/gpu/gpu_kernels.cuh

Differential Revision: D64184710

[AMD] hipify torchaudio

---

.github/workflows/build_docs.yml
.github/workflows/ffmpeg.yml
.github/workflows/lint.yml
.github/workflows/unittest-linux-cpu.yml
.github/workflows/unittest-linux-gpu.yml

Same as https://github.com/pytorch/executorch/pull/7731

Fix linux_job_v2 after https://github.com/pytorch/test-infra/pull/6104

---

.github/workflows/unittest-linux-gpu.yml
.github/workflows/unittest-macos-cpu.yml
.github/workflows/unittest-windows-cpu.yml
.github/workflows/unittest-windows-gpu.yml

Temporarily deactivate GPU, Windows and MacOS unittest jobs

---

src/torchaudio/__init__.py
src/torchaudio/_internal/module_utils.py
src/torchaudio/io/__init__.py
src/torchaudio/transforms/__init__.py

Deprecate IO classes specially

---

.github/workflows/build_docs.yml
docs/source/conf.py
src/torchaudio/pipelines/_tts/utils.py

Add back documentation for tutorials with DeepPhonemizer fix

---

.github/workflows/unittest-linux-gpu.yml

Put back GPU linux tests

---

examples/tutorials/mvdr_tutorial.py

Remove dependencies for mvdr tutorial

---

examples/tutorials/audio_feature_augmentation_tutorial.py

Remove sox effect

---

examples/tutorials/audio_data_augmentation_tutorial.py

Remove augmentation effector

---

src/libtorchaudio/forced_align/cpu/compute.cpp
src/libtorchaudio/forced_align/gpu/compute.cu
src/libtorchaudio/lfilter.cpp
src/torchaudio/functional/_alignment.py

Use narrow instead of indexing by slices

---

docs/requirements-tutorials.txt
examples/tutorials/audio_feature_extractions_tutorial.py

This PR is meant to be merged only after all `[TUTORIAL DEPENDENCY REMOVAL]` get merged. At that point, I will turn it off draft mode.

Remove external dependencies for tutorials
