README.md, torchaudio/__init__.py, torchaudio/src/generic/th_sox.c, torchaudio/src/generic/th_sox.h, torchaudio/src/th_sox.h
Ported the code from [here](https://github.com/soumith/lua---audio) to save tensors! Should also close #2, let me know if any feedback
=> Added ability to save tensors

torchaudio/__init__.py
I had the following error after installation.  This patch fixed the problem.
>>> import torchaudio
>>> torchaudio.load("ffea344c-e8a6-4697-a952-2580c4c15e48.mp3")
File "<stdin>", line 1, in <module>
File "/home/david/miniconda3/envs/hu/lib/python3.6/site-packages/torchaudio-0.1-py3.6-linux-x86_64.egg/torchaudio/__init__.py", line 26, in load
func(bytes(filename), out, sample_rate_p)
TypeError: string argument without an encoding
=> bytes function requires type

torchaudio/__init__.py
Was running into an error using the previous string encoding since it isn't available on 2.7. This seems to work for both!
=> Fix load str for 2.7 compatibility

README.md
ImportError: No module named 'cffi'. Necessary for both mac and linux installations
=> cffi dependency

test/test.py, test/test_transforms.py, torchaudio/transforms.py
* Added an MEL spectrogram transform with librosa.  If librosa is not installed this fails gracefully.
* added two convenience permutation transformations.
* Removed the old tests in test/test.py and redid the relevant ones in the unit tests.
* created unit tests for the MEL spectrogram transform and the permutation transforms.
=> add MEL spectrograms transform and fixed a few tests.

test/test_transforms.py, torchaudio/transforms.py
[mu-law companding](https://en.wikipedia.org/wiki/%CE%9C-law_algorithm) is used to reduce the dynamic range an audio signal.  Notably, it is used in the [original WaveNet](https://arxiv.org/pdf/1609.03499.pdf) implementation.  
Addionally, and unrelated to the mu-law stuff, I made some minor documentation changes to the transformations file.
=> mu-law companding transform

test/test_transforms.py, torchaudio/__init__.py, torchaudio/transforms.py
Since pytorch is python2 compatible, torchaudio should also be python2 compatible.
=> Quick and dirty fix for "bytes" (in torchaudio.save) not available in python2

test/test_transforms.py, torchaudio/transforms.py
Using the `stft` function in the `master` branch, this create spectrograms in the power scale, converts those spectrograms to the MEL scale, and also converts the power scale to decibels.  This is similar to the basic functionality of the librosa mel spectrograms that is already in the library.
Notably, I have not done any checks to see if the pytorch version supports `stft`.  The current 0.3 branch does not support this function.  Additionally, the dimension of the input and the output differ from the original MEL transform.  This is because the `stft` function expects (c, n) rather than (n, c).  Finally, the input variable names don't correspond to librosa, because librosa has a lot more options than these functions.  This is all to say, one couldn't just change `MEL` to `MEL2`.
I split …
=> pytorch implementation of MEL spectrograms (no librosa req'd)

test/test_transforms.py, torchaudio/transforms.py
Reverts pytorch/audio#23
while there's nothing wrong with this PR when used with the master branch of pytorch, torch.stft hasn't gone into a release yet. So we are seeing user issues: #26 #25 #24  
I'll merge this back in once a release is cut that has `torch.stft` and the windowing functions
=> Revert "pytorch implementation of MEL spectrograms (no librosa req'd)"

test/test_transforms.py, torchaudio/transforms.py
Just like how `__repr__` exists for `transform` objects in `torchvision`, I have added them for `transform` objects here.
Tests are also included.
=> Add __repr__ for transforms

test/test.py, test/test_transforms.py
The tests fail because torch.cos is not implemented for LongTensor.  This is a simple fix that moves the conversion of the result of the cos function to float to the conversion of the inner function (torch.arange) to float.  Below the error message I received using the master branch of pytorch.
```
======================================================================
ERROR: test_save (__main__.Test_LoadSave)
File "test.py", line 95, in test_save
2 * math.pi * torch.arange(0, 4 * sr) * freq / sr)).float()
RuntimeError: "cos" not implemented for 'torch.LongTensor'
```
=> torch.cos not implemented for LongTensor fix

.clang-format, .clang-tidy, .flake8, setup.py, test/test.py, test/test_dataloader.py, test/test_legacy.py, test/test_sox_effects.py, test/test_transforms.py, torchaudio/__init__.py, torchaudio/sox_effects.py, torchaudio/torch_sox.cpp, torchaudio/torch_sox.h, torchaudio/transforms.py
The filter bank matrix that I used for the MEL2 transform was semi-broken because `torch.arange` returns a long tensor instead of a float tensor.  I realized I could replace a lot of the logic in the same transform with the bartlett window function to create triangular windows instead of manually creating them.  I also noticed that I was creating the filter bank matrix each time the transform was called instead of once upon initialization.  
I also refactored the code based on flake8.
=> MEL2 optimzation, filter bank conversion fix, flake8 refactor

.gitignore, torchaudio/__init__.py, torchaudio/transforms.py
`pathlib` is recommended for path handling nowadays. Simply using `str()`  makes it compatible with pathlib, without introducing a dependency (although it's been part of stdlib for quite a while now).
=> stringify filename on load for compatibility with pathlib

test/test_transforms.py, torchaudio/transforms.py
the name changes make sense, but I thought adding a deprecation warning makes sense here.  Especially since the version number hasn't changed.  Not exactly sure how changes like this normally go.
=> add friendly deprecation message

setup.py
Added `torch` as requirement to `torchaudio`. 
Does not solve when building from source but when user
```
pip install torchaudio
```
=> Added torch requirement to setup.py

test/test.py, test/test_transforms.py, torchaudio/transforms.py
This is a start, appreciate comments and any advice on achieving consistency with torch codebase.
Main modifications:
- switched the argument orders of Spectrogram, MelSpectrogram so that n_fft is the default way to construct as opposed to window size
- made normalization after torch.stft in Spectrogram a parametrized option
- changed SpectrogramToDB to the librosa implementation, which is more numerically stable
- fixed a bug in MelScale where the matrix multiply would fail if the input tensor was on a different device than the filterbank matrix
- changed default n_mels in MelScale, MelSpectrogram to align with librosa's
- added MFCC function that calculates the MFCC features for an input audio file. This uses a torch DCT implementation from another repo. Am unsure of whether it makes …
=> Librosa consistency

torchaudio/__init__.py
I fell for this myself. The sox info struct is specifying the total number of samples and not the number of sample per channel as it is normally used.
Its probably better to clarify this, since not everyone knows the difference between samples, length, frames....
=> clarify sox info length field

torchaudio/sox_effects.py
Need to send absolute filepath to the `__getitem__`, or you will get "cannot find the file" error.
=> Update documentation for SoxEffectsChain.

.travis.yml
Add `.travis.yml` file to run test automatically on travis as it is done for [pytorch/vision](https://github.com/pytorch/vision) as well.
The result can be seen here: [![Build Status](https://travis-ci.org/hagenw/audio.svg?branch=travis-test)](https://travis-ci.org/hagenw/audio)
Currently it is failing which is unrelated to this pull request and covered by this issue: #101
=> TST: add travis config

test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
From previous pull request:
"In general we don't want to support this. If someone wants to use numpy, they'll need to use our 0-cost conversions from their numpy array to a tensor, then pass it into this and then convert it back. We also don't want to use numpy to do our computations."
The major difference is mu_law_expanding and mu_law_encoding no longer accepts numpy arrays as input/output.
=>  Remove numpy support in transforms.py and functional.py

docs/source/kaldi_io.rst, torchaudio/common_utils.py, torchaudio/kaldi_io.py
Now that common_utils.py provides a robust method to check for whether an import is successful, we should use the same function to check for librosa in torchaudio/kaldi_io.py.
Change autodata to autofunction because we no longer need to wrap methods.
=> Use common_utils.py to check for correct import in torchaudio/kaldi_io.py

build_tools/travis/install.sh, test/test_transforms.py
In test_transforms.py, the tensors returned back are floats which throws an error when trying to compare a double with a float.
```
RuntimeError: expected device cpu and dtype Double but got device cpu and dtype Float
```
=> CI build fix

README.md
The current version of torch audio needs the nightly version of pytorch. Adding a reminder that the nightly version of pytorch may be needed for development might remind others to pay attention to that.
```bash
conda install -c conda-forge sox
conda install pytorch-nightly -c pytorch
git clone https://github.com/pytorch/audio.git
python setup.py clean --all
python setup.py clean
python setup.py develop  # or install
python -c "import torch; import torchaudio"
```
=> pytorch nightly version needed for development

test/test_functional.py, test/test_jit.py, test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
-Compose: From https://github.com/pytorch/audio/issues/110, "we wouldn't need it because once things are based on Layers people can simply build a nn.Sequential()."
-Aliases and deprecated modules: SPECTROGRAM, F2M, MEL If we are going to start breaking things in this new release, then it makes sense to do as much as possible so that the future stable versions do not have technical debt
-BLC2CBL: there is no input/output to this library that uses BLC or CBL format (going to keep LC2CL mainly because all the inputs are (c, n) meaning it would be convenient for users to switch this format).
The input (some outputs) of all transforms/functions would be (c, n) e.g Spectrogram, MFCC, MelSpectrogram, Resample, etc. This is to be consistent with PyTorch which has channel followed by the number …
=> [BC] Standardization of Transforms/Functionals

test/test_jit.py, test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
To be more consistent with torchaudio-contrib [MuLawDecoding](https://github.com/keunwoochoi/torchaudio-contrib/blob/master/torchaudio_contrib/layers.py#L443).
Also with the name 'encoding',  'decoding' seems to fit more
=> Renaming MuLawExpanding to MuLawDecoding

torchaudio/functional.py, torchaudio/transforms.py
In transforms.py
-Adding \_\_all\_\_ to show all layers/transforms
-Moving `SpectrogramToDB` to be beside `Spectrogram`
-Moving `MelSpectrogram` to be beside `MelScale`. Also since `MFCC` is an operation on top of `MelSpectrogram`, it makes sense to have it after `MelSpectrogram`
In functional.py
-Moving `spectrogram_to_DB` to be beside `spectrogram` (This also allows `create_fb_matrix` and `create_dct` to be beside each other)
=> Reorder transforms.py and functional.py + add __all__

test/test_jit.py, test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
We want to keep SpectrogramToDB's implementation of toDB mainly cause it is used in the computation for MelSpectrogram, MFCC. However, it is more generic and can be applied to any tensor (not just spectrograms).
=> Rename SpectrogramToDB to AmplitudeToDB

README.md
We want to describe 
* the standardization
* the philosophy behind the behavior of transformations.
See also
* [comment in #166](https://github.com/pytorch/audio/pull/166#issuecomment-515603852)
* [comment in keunwoochoi/torchaudio-contrib#36](https://github.com/keunwoochoi/torchaudio-contrib/issues/36#issuecomment-502144987)
=> Adding Manifesto to README

README.md, docs/source/compliance.kaldi.rst, docs/source/functional.rst, docs/source/kaldi_io.rst, docs/source/legacy.rst, docs/source/sox_effects.rst, docs/source/transforms.rst, torchaudio/__init__.py, torchaudio/_docs.py, torchaudio/compliance/kaldi.py, torchaudio/datasets/vctk.py, torchaudio/datasets/yesno.py, torchaudio/functional.py, torchaudio/kaldi_io.py, torchaudio/legacy.py, torchaudio/sox_effects.py, torchaudio/transforms.py
-With new features added and legacy code gets removed, the docs (rst) also have to be updated
-The current docs looks very shady/broken (some code missing e.g transforms forward) or formatted poorly
Preview: https://jamarshon.github.io/audio/
=> Large re-amp on the torchaudio/docs

README.md
https://github.com/pytorch/audio/pull/180
=> README updates (quick cleanup)

test/test.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets_vctk.py, test/test_functional.py, test/test_kaldi_io.py, test/test_legacy.py, test/test_sox_effects.py, test/test_transforms.py
This makes it easier to test against an installed wheel, as the
torchaudio folder is no longer preferentially picked up when
you run a test module.
I had to move all tests in subfolders into the top level test
directory to make this work, since you can't access .. modules
without mucking around with sys.path (which I don't want to do.)
NB: this BREAKS the syntax where you can run a test by
saying `python -m test.test`.  Instead, do `python test/test.py`
or use the pytest runner.
=> Make test scripts runnable without being modules.

README.md
https://github.com/pytorch/audio/pull/190
=> Binary install instructions. 

README.md, build_tools/packaging/wheel/build_from_source.sh, build_tools/packaging/wheel/linux_manywheel.sh, build_tools/packaging/wheel/osx_wheel.sh
- Instructions for how to install stable and master binaries,
without hardcoding wheel filenames
- Turn on Python 2 build (numba is only needed for testing)
- Make builds a little more hermetic
- Prefer building against nightly CPU-only torch build
- Don't install all of requirements.txt, it's not necessary
=> Packaging improvements for nightlies

test/test_jit.py, torchaudio/functional.py
https://github.com/pytorch/audio/pull/201
=> Add missing from __future__ import division.

README.md
* Mention standard complex number in README, with functionals available.
* Update formatting for `torch.hann_window`
=> Mention complex number support in README.

build_tools/packaging/wheel/build_from_source.sh, build_tools/packaging/wheel/linux_manywheel.sh, build_tools/packaging/wheel/osx_wheel.sh
Based off of #198 but nightly specific changes were dropped.
=> Packaging improvements for 0.2.0

.travis.yml, requirements.txt, test/common_utils.py, test/compliance/generate_fbank_data.py, test/compliance/generate_test_stft_data.py, test/compliance/utils.py, test/test.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets_vctk.py, test/test_functional.py, test/test_jit.py, test/test_kaldi_io.py, test/test_sox_effects.py, test/test_transforms.py, torchaudio/__init__.py, torchaudio/_docs.py, torchaudio/common_utils.py, torchaudio/compliance/kaldi.py, torchaudio/datasets/vctk.py, torchaudio/datasets/yesno.py, torchaudio/functional.py, torchaudio/kaldi_io.py, torchaudio/sox_effects.py, torchaudio/transforms.py
- Apply `__future__` imports uniformly (future division is the biggy, but absolute
imports mattered too)
- Hotfix use of tempfile.TemporaryDirectory using a BC library (DO NOT
add this library as a dependency to torchaudio; it's only for testing)
- Replace math.gcd with fractions.gcd
- Fix a weird pytest collection bug involving parametrized tests
- Turn on Python 2 and Python 3.7 in Travis.
=> Make torchaudio work on Python 2.

.travis.yml, build_tools/travis/install.sh, requirements.txt
Upgrading requirements.txt from torch 1.1.0 to 1.2.0
The python 3.7.4 seems to have issue when doing pip install torch 1.2.0 so using to 3.7.3 instead works (https://github.com/ContinuumIO/anaconda-issues/issues/11195). Instead of changing the code, I am going to wait until conda releases their fix.
=> CI Fix: upgrade to torch 1.2.0

test/test_transforms.py, torchaudio/transforms.py
In the issue https://github.com/pytorch/audio/issues/245, it was determined that for MelSpectrogram the transform already knows how many bins the stft will have and thus can initialize the fb matrix without needing to infer the dimensions of its first input.
The benefit of initializing the fb matrix immediately as opposed to lazy load when given a first input is that loading and saving from state dict (`load_state_dict`) will not throw an error as the tensor sizes match
=> MelSpectrogram: Use given n_fft to initialize fb immediately

.gitignore, .travis.yml, build_tools/travis/install.sh, build_tools/travis/test_script.sh, examples/interactive_asr/README.md, examples/interactive_asr/__init__.py, examples/interactive_asr/asr.py, examples/interactive_asr/utils.py, examples/test/test_interactive_asr.py
For the ASR demo, we should test that the `transcribe_file` works correctly (i.e. reads "sample.wav" and produces `[['THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG']]`).
To do this, functions inside `examples/interactive_asr/asr.py` are moved into `examples/interactive_asr/utils.py` so that the functions can be called in `examples/test/test_interactive_asr.py`. This also reduces the number of lines of code for `asr.py`
The Travis CI has been updated accordingly
=> Increasing test coverage (ASR demo)

torchaudio/torch_sox.cpp
`Tensor.data<T>` is deprecated (https://github.com/pytorch/pytorch/pull/24886) in favor of `Tensor.data_ptr<T>`. This PR cleans up its usage in torchaudio.
=> Change Tensor.data<T> to Tensor.data_ptr<T>

packaging/build_from_source.sh, torchaudio/torch_sox.cpp
- explicitly excluding alsa when building on linux
- torchaudio was using deprecated types and generating warnings
=> add asound for linux. fix deprecated torch type.

torchaudio/torch_sox.cpp
Compilation error noticed in #262.
First PR to crash is #261 according to [this](https://travis-ci.org/pytorch/audio/pull_requests). Unknown status from [this](https://travis-ci.org/pytorch/audio/builds).
This reverts commit 860edcdb13e07d017ae0d081d4e2e3034b5e455f.
=> Revert "Change Tensor.data<T> to Tensor.data_ptr<T> (#261)"

packaging/build_from_source.sh
Yesterday, we added curl retries to try to fix the build.
However, there are still issues here:
https://circleci.com/gh/pytorch/audio/5049?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/pytorch/audio/5055?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
1. Upped the retry count and lowered slightly the time to wait to connect.
2. Removed the "r" query parameter and "mirror".  This was set on two of the downloads but not the other two.  I believe it should be more robust to not specify this.
Let's try it.
=> Curl Settings for Build Script

test/test_compliance_kaldi.py, test/test_functional.py, test/test_transforms.py, torchaudio/compliance/kaldi.py, torchaudio/functional.py, torchaudio/transforms.py
This PR adds a functional/transform/compliance to compute the deltas of MFCC features, see also [here](http://practicalcryptography.com/miscellaneous/machine-learning/guide-mel-frequency-cepstral-coefficients-mfccs/#deltas-and-delta-deltas).
* The effect at the boundary follows Kaldi's convention of replicating the values (see [here](https://kaldi-asr.org/doc/feature-functions_8h_source.html)).
* To compute the deltas-deltas, simply compute the deltas on the deltas (though Kaldi has a `order` parameter to compute higher order deltas). The compliance interface loops over the order to computer higher order differences.
* This function simply returns the deltas. Kaldi instead appends them to the set of available features, see [here](https://github.com/kaldi-asr/kaldi/blob/master/src/featbin/a …
=> Compute deltas

test/test_functional_filtering.py, torchaudio/__init__.py, torchaudio/functional.py
I took master and tested on a GPU machine, passing in inputs that are tensors on GPU.  Failed due to internal tensors being created on CPU.
Fixed this, and added testing for GPU path if available.
=> Fix lfilter for GPU machine

.circleci/config.yml, .circleci/config.yml.in, packaging/build_conda.sh, packaging/build_from_source.sh, packaging/build_wheel.sh
=> 0.3.1 point release

README.md, torchaudio/functional.py, torchaudio/transforms.py
We want to clarify the naming of `n_*` variables, initiated by #293. Documentation of standardization in [README](https://github.com/pytorch/audio/blob/master/README.md).
=> standardizing n_*

torchaudio/torch_sox.cpp
Re-implement #261 which was reverted in #265.
This reverts commit 962c6b0f7f6efbd17349e4cf2fedfe6d2450aad1.
=> Revert "Revert "Change Tensor.data<T> to Tensor.data_ptr<T>

test/test_functional.py
Add four test cases of linearity check for inverse stft in test_functional.py.
=> add linearity test for istft

test/test_functional_filtering.py, torchaudio/functional.py
Add peaking equalizer filter in functional.py and test it in test_functional_filter.py.
=> Add peaking equalizer filter

torchaudio/augmentations.py
minor typo in dimension name in augmentation.
=> follow convention for dimension.

test/test_datasets.py, torchaudio/datasets/commonvoice.py, torchaudio/datasets/librispeech.py, torchaudio/datasets/vctk.py, torchaudio/datasets/yesno.py
Since this is what has been most used in domains, we keep tuples as the item to return for now.
for CommonVoice:
```
return waveform, sample_rate, dictionary
```
for LibriSpeech:
```
return (
waveform,
sample_rate,
utterance,
int(speaker_id),
int(chapter_id),
int(utterance_id),
)
```
for VCTK:
```
return waveform, sample_rate, utterance, speaker_id, utterance_id
```
for YesNo:
```
return waveform, sample_rate, labels
```
CC #303
=> Data points remain tuples

requirements.txt, torchaudio/datasets/utils.py
This adds resume to download function, and a validate function with md5 or sha256, from pytorch/pytorch#24915.
Following [this](https://tobiasraabe.github.io/blog/how-to-download-files-with-python.html), it was tested using:
```python
def test_download_url(self):
url = "http://www.patentsview.org/data/20171226/botanic.tsv.zip"
hash_url = "94c642405619b20ecaf657b30e84bab787320649e751ed6ac629c0be613ded44"
download_folder = "."
download_url(url, download_folder)
validate_download_url(url, download_folder, hash_url)
```
Do we have a url we can use to test? I'm leaning toward not having a test like this that would ping a url with every batch of test.
See 
* [another example](https://gist.github.com/mjohnsullivan/9322154#file-download-py-L32).
* [using keep …
=> Resume download

test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
We offer a layer that applies complex STFT without the power/normalization done in spectrogram. However, we do not want to overload the name "STFT" existing in pytorch, as done in the original proposal in [the proposal](https://github.com/pytorch/audio/pull/327/commits/008791c06a7ea187056f1ee48072ec37705c9148) from #285.
@ksanjeevan -- thoughts?
CC @ksanjeevan @keunwoochoi @cpuhrsch
=> Complex STFT transform from spectrogram

torchaudio/functional.py
Following on #326 and decorating `equalizer_biquad`.
=> decorating equalizer_biquad with jit

README.md
As done on pytorch.org, let's mention conda as the first way to install torchaudio.
=> Recommend conda installation

torchaudio/functional.py, torchaudio/transforms.py
* Moving batch pack/unpack from transform (vocoder) to functional, as done elsewhere.
* Also use ellipses for batch in docstring.
=> Move batch from vocoder transform to functional

torchaudio/datasets/utils.py
Addressing [comment](https://github.com/pytorch/audio/pull/320/files#r350377005).
=> correct file_obj reference.

test/test_functional.py, torchaudio/functional.py
Since this `_scale_to_interval` is private and not used internally, we don't need to keep it until we decide to add it back.
=> Remove scale to interval from #319

test/test_functional.py, test/test_transforms.py
Deactivate temporarily librosa consistency test which is currently failing on travis. Cannot reproduce offline. Blocking #355.
=> deactivate failing test

torchaudio/functional.py
I made the following improvements to the `lfilter` functional code.
* use `torch.clamp` instead of `torch.min(..., torch.max(...))`
* remove unneeded creation of various intermediate tensors previously required
* vectorize calculation of windows on padded waveform
* make for-loop calculation more efficient by directly calculating items on the diagonal
For me, this reduced the run time of `test/test_functional_filtering.py` from about 120s to 80s.
=> Improve lfilter functional

test/test_transforms.py, torchaudio/transforms.py
Tensors initialized but not registered as buffers during module instantiation do not move when the module is moved to another device. This fix registers such tensors as buffers so that they are automatically moved when the module moves.
=> Module GPU test fixes

torchaudio/datasets/utils.py, torchaudio/functional.py, torchaudio/transforms.py
Fixes the following Travis build errors:
```
E     File "torchaudio/transforms.py", line 82
E   SyntaxError: Non-ASCII character '\xc3' in file torchaudio/transforms.py on line 83, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
and
```
if six.PY2:
>           csv_reader = csv.reader(utf_8_encoder(unicode_csv_data), **kwargs)
E           NameError: global name 'utf_8_encoder' is not defined
torchaudio/datasets/utils.py:46: NameError
```
and
```
def test_commonvoice_bg(self):
path = os.path.join(self.path, "commonvoice")
data = COMMONVOICE(path, "train.tsv", "tatar")
data = bg_iterator(data, 5)
>       for d in data:
E       TypeError: iter() returned non-iterator of type '_ThreadedIterator'
```
and
```
E           TypeError: constant_pad_nd(): argument …
```
=> Fix several errors in tests run by Travis

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/test/test_sort_yaml.py
Compare to application to vision repo in pytorch/vision#1321
See rationale writeup: https://github.com/pytorch/vision/pull/1321#issuecomment-531033978
Fixes #304
=> Adopt native-Python code generation convention

.circleci/config.yml, .circleci/regenerate.py
This drops a special case in the native-Python code generation logic that was put in place to emulate old codegen behavior that was originally a bug (see [original comment](https://github.com/pytorch/audio/pull/378#discussion_r361589458)).
=> Apply 'nightly' branch filter to binary uploads

test/test_functional.py
A seed of `42` (which is used elsewhere in the project) seems to work.
=> Fix random seed for flaky test_griffinlim test

test/test.py
=> conditionally skip unsupported subTest tests for Python 2

.circleci/config.yml.in
With the introduction of the `filter_branch` parameter to the `workflows`
function we no longer have a need to have this if block anymore per
@ezyang's assessment.
NOTE: `regenerate.py` was re-ran but had no effect.
=> .circleci: Remove if block, wasn't doing anything

test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
Align with librosa:
* fix power of spectrogram: closes #389
* makes power a float, so as to work with complex norm
* partially re-enabling librosa consistency test to test with different power: closes #373.
=> [Bug Fix] fix power of spectrogram. makes power a float

test/test_functional.py, test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
* Extend batch support from #337 to MelScale, MelSpectrogram, MFCC. 
* Update documentation for transforms.
* `mask_along_axis_iid` supports batching, so is not updated here, see #401 and #350.
Closes #383
=> extend batch support

test/test_functional.py, test/test_transforms.py, torchaudio/functional.py, torchaudio/transforms.py
Apply #391 except griffinlim. Using pull request to trigger builds and test before merging in v0.4.0.
* extend batch support
closes #383
* function for batch test.
* set seed.
=> Adding batch to v0.4.0

.circleci/config.yml, .circleci/config.yml.in, packaging/build_conda.sh, packaging/build_wheel.sh
Create 0.3.2 point release. To generate binaries: [wheels](https://github.com/pytorch/audio/pull/308#issuecomment-543188716) and [conda](https://github.com/pytorch/audio/pull/308#issuecomment-546020394) in #308. Once push of binaries is done, push [release notes](https://github.com/pytorch/audio/releases).
Permissions needed for point release:
Fixes #338.
cc @seemethere
=> 0.3.2 point release.

packaging/pkg_helpers.bash
CUDA_SUFFIX was still being used here when it should've been swapped out
for PYTORCH_VERSION_SUFFIX, which is what's being used for conda below.
=> packaging: Install correct version of pytorch for pip

packaging/build_conda.sh, packaging/build_wheel.sh, setup.py
Following #410, master should be moved to 0.5.0.
=> move master to 0.5.0

.circleci/config.yml, .circleci/regenerate.py, .travis.yml
Removes for both Travis and CircleCI
Python 2.7 was EOL on January 1, 2020
The last torchaudio release to support Python 2.7 was 0.4.0
=> ci: Remove 2.7 tests

test/test.py
This reverts commit cdf5c83d406748c717fafabe09c3026a971b2d48.
=> Revert "conditionally skip unsupported subTest tests for Python 2 (#386)"

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, packaging/pkg_helpers.bash, packaging/torchaudio/meta.yaml
Adds python 3.8 to the build matrix.
Related PRs:
* https://github.com/pytorch/pytorch/pull/31948
* https://github.com/pytorch/vision/pull/1731
=> .circleci: Bump python3.7 -> python3.8

torchaudio/functional.py
[Test](https://travis-ci.org/pytorch/audio/jobs/638411105) falling on master:
```
======================================================================
ERROR: test_torchscript_dither (__main__.TestFunctional)
File "test/test_functional.py", line 641, in test_torchscript_dither
_test_torchscript_functional_shape(F.dither, tensor)
File "test/test_functional.py", line 23, in _test_torchscript_functional_shape
jit_out = jit_method(*args, **kwargs)
RuntimeError: result type Float can't be cast to the desired output type Long
The above operation failed in interpreter.
File "/Users/vincentqb/anaconda3/envs/audio-built/lib/python3.7/site-packages/torchaudio- …
```
=> dither jit test

torchaudio/transforms.py
=> Migrate TimeStretch and AmplitudeToDB to torch.nn.Module

torchaudio/transforms.py
@vincentqb, fixing what was mentioned https://github.com/pytorch/audio/pull/456.
=> phase_advance should be a buffer so it moves device correctly

torchaudio/transforms.py
- Add missing params on Docstrings
- Add type, optional and Default to params
- Normalize nomenclature on params
This will make easier to work within the torchaudio since will improve a little the documentation, and will improve static analysis from IDE by adding the correct types to the params
=> Improve Docstrings in transfroms

torchaudio/compliance/kaldi.py
Following [comment](https://github.com/pytorch/audio/issues/371#issuecomment-594130485), setting `dither` to `0` and setting `energy_floor` to `1.`.
```python
import torchaudio
filename = "audio/test/assets/steam-train-whistle-daniel_simon.mp3"
s, sr = torchaudio.load(filename)
spec1 = torchaudio.compliance.kaldi.spectrogram(s, dither=0., energy_floor=1.)
spec2 = torchaudio.compliance.kaldi.spectrogram(s, dither=1e-6)
print(2*((spec1 - spec2).abs()/(spec1.abs() + spec2.abs())).mean())
spec1 = torchaudio.compliance.kaldi.fbank(s, dither=0., energy_floor=1.)
spec2 = torchaudio.compliance.kaldi.fbank(s, dither=1e-6)
print(2*((spec1 - spec2).abs()/(spec1.abs() + spec2.abs())).mean())
spec1 = torchaudio.compliance.kaldi.mfcc(s, dither=0., energy_floor=1.)
spec2 = …
```
=> Change default value of dither

.circleci/config.yml, .circleci/config.yml.in
pjh5 is a former employee so we should switch over to using a bot token.
Should resolve nightly pipeline failing on upload.
Similar to https://github.com/pytorch/vision/pull/1960
=> .circleci: Switch to use token for conda uploads

.gitignore
Ignore files generate by Pycharm and OSX files
- This will make easier to manage commits
=> Ignore pycharm and OSX files

test/test_functional_filtering.py, torchaudio/functional.py
Hi ,
Checked this issue #260 ( Reducing dependency in Sox) 
Went throught Sox source code and implemented below functions along the lines of existing allpass function in functional.py
- ```bandpass_biquad``` 
- ```bandreject_biquad```   
Add test cases for both ```bandpass_biquad``` and ```bandreject_biquad``` to test_functional_filtering.py
All tests in test_functional_filtering.py passed
Output of test_functional_filtering.py
```
.........skipping GPU test for lfilter_basic because device not available
.skipping GPU test for lfilter because device not available
...
Ran 13 tests in 1422.882s
OK
```
=> Add bandpass and bandreject to functional

test/test_functional.py, test/test_transforms.py
- Compare results from `functional.AmplitudeToDB` with librosa corresponding functions
- Add batch test to `transform.AmplitudeToDB`
- Add to `test_librosa_consistency` test for magnitude
=> Add test transform and functional AmplitudeToDB

torchaudio/functional.py
=> Fix Issue #471

test/test_functional_filtering.py, torchaudio/functional.py
Hi ,
Regarding the issue #260 ( Reducing dependency in Sox)
Implemented below functions  in functional.py
-  ```band_biquad```
-  ```treble_biquad```
-  ```deemph_biquad```
-  ```riaa_biquad```
Added test cases for all four in to test_functional_filtering.py
All tests in test_functional_filtering.py passed on CPU.
```
............skipping GPU test for lfilter_basic because device not available
.skipping GPU test for lfilter because device not available
.....
Ran 18 tests in 2250.942s
OK
````
@vincentqb could you please review changes and run tests on GPU
=> Add band,treble,deemph,riaa to functional.py

torchaudio/transforms.py
Spelling correction in docstrings for `transforms.FrequencyMasking` and `transforms.TimeMasking`.
=> Spelling correction

torchaudio/__init__.py, torchaudio/common_utils.py, torchaudio/compliance/kaldi.py, torchaudio/functional.py, torchaudio/kaldi_io.py, torchaudio/sox_effects.py, torchaudio/transforms.py
This change removes `__future__` imports from torch audio.
```
grep '__future__' -lr torchaudio  | grep -v '__pycache__' | xargs sed -i '/__future__/d'
```
Relates to #477
=> Remove __future__ from torachaudio

test/test_functional.py, test/test_torchscript_consistency.py
This PR is derived from #466. 
It extracts torchscript consistency test from `test_functional` module and put them in a dedicated module/class (`test_torchscript::TestFunctional`).
=> Extract JIT tests from test_functional to the dedicated test module

test/test_functional.py, test/test_librosa_compatibility.py
From #466.
Similar to #480 
It extracts librosa consistency test from `test_functional` module and put them in a dedicated module/class (`test_librosa_consistency::TestFunctional`).
=> Extract librosa tests from test_functional to the dedicated test module

torchaudio/functional.py
relates to #477
- Use inline type hinting
- Fix Docstrings according with typing
During this fix two functions have a parameter that is not being used for anything: `griffinlim` with `normalized` and `istft` with `pad_mode`, probably they should be removed since they can mislead.
=> Add inline typing to functional

.circleci/docker/Dockerfile, README.md, examples/interactive_asr/vad.py, torchaudio/datasets/utils.py
Hey , Regarding the Issue (#477  )
I have replaced the package ```six``` with python 3 equivalents 
and changed readme and docker file which has reference to  package ```six``` installation
@vincentqb  could you review these changes
=> Python 2 deprecation  - Replace package six with python3 versions

test/test_librosa_compatibility.py, test/test_transforms.py
From #466.
Similar to #481.
This PR extracts `librosa` consistency test from `test_transforms` module and put them in a dedicated module/class (`test_librosa_consistency::TestTransforms`).
=> Extract librosa tests from test_transforms to the dedicated test module

torchaudio/sox_effects.py
- Add inline typing
relates to #477
Where are `Any` I do not know how to classify its types.
The `class SoxEffectsChain(object):` does not need anymore the `object` and the lines 52-55 of the docstrings I think are not right since is the method `sox_build_flow_effects`  that returns that, however, I left as it is.
=> Add inline typing to SoxEffects

test/test_batch_consistency.py, test/test_functional.py
From #466.
This PR extracts batch consistency test from `test_functional` module and put them in a dedicated module/class (`test_batch_consistency::TestFunctional`).
=> Extract batch test from test_functional and move to the dedicated module

test/test_functional.py, test/test_functional_filtering.py
Relates to #466
SoX compatibility tests in `test_functional` better fit to `test_functional_filtering` of which majority of the tests are about SoX compatibility.
=> Move SoX filter test to test_functional_filtering

test/test_functional_filtering.py, test/test_torchscript_consistency.py
Relates #466 
This PR moves JIT consistency tests in `test_functional_filtering` module into `test_torchscript_consistency` module for better [coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)) and [cohesion](https://en.wikipedia.org/wiki/Cohesion_(computer_science)).
=> Extract JIT tests from filter test module and put in JIT test module.

test/test_batch_consistency.py, test/test_librosa_compatibility.py, test/test_torchscript_consistency.py
As noted [here](https://github.com/pytorch/audio/pull/508#pullrequestreview-387586964), tests were not running.
cc @mthrok
=> run tests again

torchaudio/transforms.py
This PR makes `Fade` compatible with device other than CPU. It was generating coefficients on CPU so that when the input Tensor is on CUDA, it failed.
=> Fix Fade device compatibility

test/test_batch_consistency.py
Batch test helper can be simpler with Pythonic expression.
The default value of `atol` and `rtol` are teken from the downstream function [here](https://github.com/pytorch/pytorch/blob/66d50060ebb091a5186acd0c066439a3b80f8ea6/aten/src/ATen/native/native_functions.yaml#L385).
=> Simplify helper function

test/test_batch_consistency.py, test/test_compliance_kaldi.py, test/test_functional.py, test/test_functional_filtering.py, test/test_librosa_compatibility.py, test/test_torchscript_consistency.py, test/test_transforms.py
Currently there are three different assertions used for numerical comparison.
```python
assert torch.allclose(...
self.assertTrue(torch.allclose(...
torch.assert_allclose(...
```
`torch.assert_allclose` has nice features compared to the others;
- More readable error
`AssertionError: Not within tolerance rtol=0.0001 atol=1e-05 at input[0, 1] (-0.8857436776161194 vs. 1.0887877941131592) and 2 other locations (100.00%)`
- Will raise an error if the shapes are different.
`RuntimeError: expand(torch.FloatTensor{[1, 1, 3]}, size=[1, 3]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)`
Example:
```python
import unittest
import torch
t1 = torch.randn(1, 3)
t2 = torch.randn(1, 3)
class TestNotClose(unittest.TestCase):
def test_0(self): …
```
=> Use torch.testing.assert_allclose

test/test_functional_filtering.py
`test_lfilter_basic_gpu` and `test_lfilter_gpu ` were reported as `PASSED` where there is no GPU, which should be `SKIPPED`.
=> Fix GPU test skip logic

torchaudio/functional.py
This improves the speed of `lfilter` (and functions that use `lfilter`, such as `biquad`) by 10%.
* Before (23.4369 seconds for `lfilter` call)
Breakdown
```
720|    220501|       4.4464|   2.0165e-05| 18.97%|    for i_sample, o0 in enumerate(input_signal_windows.t()):
(call)|         1|  7.86781e-05|  7.86781e-05|  0.00%|# /scratch/moto/pytorch/torch/tensor.py:460 __iter__
(call)|    220500|      2.72458|  1.23564e-05| 11.62%|# /scratch/moto/pytorch/torch/tensor.py:474 <lambda>
721|    220500|      2.80982|   1.2743e-05| 11.99%|        windowed_output_signal = padded_output_waveform[:, i_sample:(i_sample + n_order)]
722|    220500|      4.92106|  2.23177e-05| 21.00%|        o0.sub_(torch.mv(windowed_output_signal, a_coeffs_flipped))
723|    220500|      3.72974|  1.69149e-05| 15.91%| …
```
=> Use fused op in lfilter

mypy.ini
In order to start using Mypy full potential, we must start fixing the issues that he might throw.
Relates to #477
As a starter I add the following definitions to the config file:
allow_redefinition: True
`Allows variables to be redefined with an arbitrary type, as long as the redefinition is in the same block and nesting level as the original definition.`
ignore_missing_imports: True
`Suppresses error messages about imports that cannot be resolved.`
=> Add mypy Config File

torchaudio/_backend.py, torchaudio/_soundfile_backend.py, torchaudio/_sox_backend.py
=> Inline typing _backend

test/test_torchscript_consistency.py, torchaudio/functional.py
Similar to #520 this PR make
1. torchscript consistency test on `functional` module  device aware
2. Define the above test for CPU and GPU
3. Fix some device compatibility issues in `functional` module found in Step 2.
Relates to #515
=> Separate CPU and GPU tests for functions torchscript test + Fix devices in two functionals

test/test_functional.py
Turned out that `test_mask_along_axis_iid` is flaky.
This PR sets manual seed so that the test is deterministic.
=> Set manual seed in `test_mask_along_axis_iid`

test/common_utils.py
Fix the case when the test utility collects available backends, it is not handling `ImportError` and fails.
Resolves #536
=> Fix test backend ImportError

.travis.yml, build_tools/travis/install.sh, build_tools/travis/test_script.sh, requirements.txt
- Install PyTorch nightly build on CI test.
- Update requirements
**Important version changes**
- Drop Python 3.5 unit test.
- Add Python 3.8 unit test.
- Replace other test (lint and example) being run on 3.5 with 3.6
Unblocks #531
=> Run test against PyTorch nightly on Travis CI

.travis.yml, build_tools/travis/install.sh, build_tools/travis/test_script.sh, requirements.txt, torchaudio/functional.py
Found the note
`# TODO: remove this once https://github.com/pytorch/pytorch/issues/21478 gets solved`
And the issue is resolved and we should not need to wrap `torch.stft` anymore.
=> Call torch.stft directly

test/test_functional.py, test/test_sox_compatibility.py
Now with #532 landed, `lfilter` tests (which has nothing to do with SoX, unlike the rest of the tests in the same module) better belongs to `test_functional` rather than `test_sox_compatibility`.
=> Move lfilter test to test_functional

torchaudio/__init__.py
- Add inline typing to `__init__`
- [Atention] function `save_encinfo` had major changes due to error that mypy throw, parameters `signalinfo`, `encodinginfo` are mandatory and not optional
relates to: #477
=> Inline typing init

test/test_sox_compatibility.py
This lfilter tests were moved to `test_torchscript_consistency.py` in #507 and GPU tests were added in #528.
We can safely remove this tests from `test_functional_filtering.py`.
You can see the moved test [here](https://github.com/pytorch/audio/blob/af88b9259c284e6d8dc2973514aa826aa293ba96/test/test_torchscript_consistency.py#L215-L254).
=> Remove duplicated lfilter tests

test/common_utils.py, test/test_batch_consistency.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets.py, test/test_functional.py, test/test_kaldi_io.py, test/test_librosa_compatibility.py, test/test_sox_compatibility.py, test/test_sox_effects.py, test/test_torchscript_consistency.py, test/test_transforms.py
This PR aims the following things;
1. Introduce and adopt helper function `get_asset_path` that abstract the logic to construct path to test assets.
2. Remove `create_temp_assets_dir` anywhere except `test_io`.
The benefits of doing so are,
a. the test code becomes simpler (no manual construction of asset path with `os.path.join`)
b. No unnecessary directory creation and file copies.
For 2. and b. tests in `test_io.py` (or tests that use `torchaudio.save`) are the only tests that need to write file to the disc, where the use of temporary directory makes it cleaner, therefore, `create_temp_assets_dir` is not necessary elsewhere. (still, `test_io` does not need to copy the entire asset directory, but that's not the point here.)
Also if any test is accidentally overwriting an asset data, not …
=> Simplify and abstract away asset access in test

README.md
=> Correct nightly installation instructions

docs/source/functional.rst, test/test_batch_consistency.py, test/test_sox_compatibility.py, test/test_torchscript_consistency.py, torchaudio/functional.py
Hi ,
Regarding the issue #260 ( Reducing dependency in Sox)
Implemented below function in functional.py
- contrast
Added a test case  to test_sox_compatibility.py
All tests in test_sox_compatibility.py passed on CPU.
```
................gain: can't reclaim headroom
.
Ran 17 tests in 501.774s
OK
```
@vincentqb could you please review changes
=> Add contrast to functional

test/test_sox_compatibility.py
Hi ,
Regarding the issue #557 . 
I have changed all upper case variables to lower case in test_sox_compatibility.py
@mthrok  could you please review these changes
=> Fix  variable names in test_sox_compatibility.py

test/test_batch_consistency.py
Somehow only `test_mfcc` is using `mp3`, whereas other ones use `wav`.
For batch testing this difference does not matter (or we even do not need to use real data but that's separate point.), so by using `wav` file, we can forget about backend in batch tests.
=> Make batch test backend-agnostic

docs/source/functional.rst, test/test_batch_consistency.py, test/test_sox_compatibility.py, test/test_torchscript_consistency.py, torchaudio/functional.py
Hi ,
Regarding the issue #260 ( Reducing dependency in Sox)
Implemented ```dcshift``` function in functional.py
-  function.rst  - updated with new fucntion
- test_sox_compatibility.py - Added two tests for dcshift and changes as per #557 . Tests passed
```
..................gain: can't reclaim headroom
.
Ran 19 tests in 475.924s
OK
```
- test_batch_consistency.py - added test for dcshift 
```
.................
Ran 17 tests in 204.327s
OK
```
- test_torchscript_consistency.py - added test but giving error, couldn't understand the issue.
Below is the log 
```
$ python test/test_torchscript_consistency.py …
```
=> Add dcshift to functional

torchaudio/functional.py
This PR improves `lfilter` speed by 10%. See https://github.com/pytorch/audio/pull/517 for the script to measure the line by line execution time.
Before
Total time: 13.7078
```
722|    220501|      2.44247|  1.10769e-05| 17.82%|    for i_sample, o0 in enumerate(input_signal_windows.t()):
(call)|         1|  6.36578e-05|  6.36578e-05|  0.00%|# /scratch/moto/pytorch/torch/tensor.py:460 __iter__
(call)|    220500|      1.60566|  7.28191e-06| 11.71%|# /scratch/moto/pytorch/torch/tensor.py:474 <lambda>
723|    220500|      1.86697|  8.46698e-06| 13.62%|        windowed_output_signal = padded_output_waveform[:, i_sample:(i_sample + n_order)]
724|    220500|      1.94628|  8.82669e-06| 14.20%|        o0.addmv_(windowed_output_signal, a_coeffs_flipped, alpha=-1)
725|    220500|         2.46| …
```
=> Improve lfilter speed

torchaudio/__init__.py, torchaudio/_sox_backend.py, torchaudio/datasets/utils.py, torchaudio/datasets/vctk.py, torchaudio/sox_effects.py, torchaudio/transforms.py
relates to #477 
This should fix all mypy issues and could be used to check if PR follow all its agreements running:
` mypy torchaudio/`
getting:
`Success: no issues found in 19 source files
`
=> Fix inline typing for mypy

test/common_utils.py, test/test_dataloader.py, test/test_sox_effects.py
Fixes #533 by only initializing SoX once on-demand in test.
*NB* This does not affect the way tests are ran in CI.
=> Only initialize sox once and never shutdown in test

docs/source/functional.rst, test/test_batch_consistency.py, test/test_sox_compatibility.py, test/test_torchscript_consistency.py, torchaudio/functional.py
Hi ,
Regarding the issue #260 ( Reducing dependency in Sox)
Implemented ```overdrive``` function in functional.py
-  function.rst - updated with new fucntion
-   test_sox_compatibility.py - Added a test for overdrive . Tests passed
```
...................gain: can't reclaim headroom
.
Ran 20 tests in 509.658s
OK
```
-   test_torchscript_consistency.py - added test . Test passed
```
...................................sssssssssssssssssssssssssssssssssss................ssssssssssssssss
Ran 102 tests in 1400.141s
OK (skipped=51)
````
-  test_batch_consistency.py - added test for overdrive . Test for overdrive passed, but 
existing batch_mfcc  failed
``` …
```
=> Add overdrive to functional

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py
Remove Python 2.7 related options from regenerate script. This does not change `config.yml` as 2.7 is deprecated.
=> Remove Python2.7 related code from CircleCI helper function

.circleci/config.yml, .circleci/regenerate.py
PyTorch master has dropped support for Python 3.5 but torch audio is still building binary for Python 3.5.
Not sure if intended. Can you advise? @seemethere @soumith @ezyang
=> Stop build binary for Python3.5

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/environment.yml, .circleci/unittest/install.sh, .circleci/unittest/run_test.sh, .circleci/unittest/setup_env.sh, test/test_librosa_compatibility.py
This PR adds unit test on Circle CI.
These tests are added as a new workflow so that binary build and unit tests are independent each other.
=> Run unit test on CCI

.circleci/docker/Dockerfile
Nightly smoke test is failing for Python 3.8 as conda environment does not exist.
=> Fix smoke test image

.circleci/config.yml, .circleci/config.yml.in
`circleci_consistency` under `nightly` workflow should run only for `nightly` branch.
The same job runs for PR under `build` workflow. So it's redundant.
=> Run nightly workflow only on nightly branch

test/common_utils.py, test/test_dataloader.py, test/test_sox_effects.py, torchaudio/__init__.py, torchaudio/sox_effects.py
This PR
- Adds safeguard to SoX initialization/shutdown
- When SoX is initialized, it register the exit hook to call shutdown using `atexit`
- SoX is shutdown at the end of program execution.
- Users can still manually shutdown.
- Automatically initialize SoX when a building effects chain. This frees the users from need to call `initialize_sox`/`shutdown_sox`, yet they can still do so. This gives better backend abstraction.
=> Handle SoX init/shutdown automatically

torchaudio/functional.py, torchaudio/transforms.py
Reverts pytorch/audio#409
We can use view instead of reshape if we are certain that the to-be-viewed Tensor is always shape compliant with the target shape, which won't necessarily apply to input Tensors. The advantage is that we'll always avoid a copy and can be sure to not incur a copy (lest we get the referenced error). Let's revert this change that was implemented due to [my comment](https://github.com/pytorch/audio/pull/409). Thank you following up on this Vincent!
=> Revert "replace reshape by view"

test/test_kaldi_compatibility.py
Follow up of #540 
This PR adds
- Kaldı compatibility test
- ~~batch consistency test~~
for `sliding_window_cmn`
~~and make `sliding_window_cmn` handle batched input.~~
cc @wanglong001 
EDIT: batch ompatibility part was moved to #570
=> Add Kaldi compatibility test for `sliding_window_cmn`

torchaudio/functional.py
In contrast to the docstring, `torchaudio.functional.griffinlim()` currently requires `momentum > 0`. This PR fixes the code to require `momentum >= 0`, and also skips the momentum-related computation if `momentum` is a false-ish constant.
Hats off to librosa for that momentum trick, by the way, hadn't seen it before. And thanks for porting it!
=> Allow zero momentum in Griffin-Lim

test/test_functional.py, torchaudio/functional.py
to give users control on the clamping behavior within the range [-1, 1], which was hardcoded before.
Fixes #596
=> lfilter: add an optional arg `clamp`

test/README.md
Add README that documents how test directory is organized and (briefly) how to add new tests.
~~Our `CONTRIBUTING.md` can point this for the direction to add test.~~ This can be incorporated into the actual `CONTRIBUTING.md`
closes #466
=> Add README for test

docs/source/functional.rst, test/test_batch_consistency.py, test/test_sox_compatibility.py, test/test_torchscript_consistency.py, torchaudio/functional.py
Hi ,
Regarding the issue ( Reducing dependency in Sox -  #260 )
Implemented ```phaser``` function in functional.py
- function.rst - updated with new function
- test_sox_compatibility.py - Added two tests for phaser
- test_batch_consistency.py - added test for phaser
- test_torchscript_consistency.py - added test for phaser
All CPU test passed.
@vincentqb could you please review these changes
=> Add phaser to functional

test/test_batch_consistency.py
`test_batch_mfcc` fails not only on Windows but also on [GPU linux machine](https://app.circleci.com/pipelines/github/pytorch/audio/1628/workflows/9c945119-bd14-40a4-9813-6d1f0fd764bc/jobs/41720).
I suspect this is resulted from the different version of CPU architecture ( `amd64-6_85` vs GPU `amd64-6_79` Windows `amd64-1_`) but cannot be sure. 
Looking at the error rate, more than 99.9% of elements are within the range of `1e-5` so I think it's safe to reduce it to `1e-4` so that Windows and GPU can pass this test.
=> Reduce tolerance for MFCC

torchaudio/__init__.py
Mypy detected `_SOX_INITIALIZED` merely as `bool`, however, can be `None` as well
=> Fix Mypy Variable Typing

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/linux/docker/.gitignore, .circleci/unittest/linux/docker/Dockerfile, .circleci/unittest/linux/docker/build_and_push.sh, .circleci/unittest/linux/scripts/install.sh
This PR adds CUDA-enabled unit test to CCI workflow.
GPU-enabled test only runs on `master` branch. (after PR is merged.)
(If we want to run the test for all the PR, I am open to it.)
See [here](https://app.circleci.com/pipelines/github/pytorch/audio/1693/workflows/f92f223d-cef0-4843-88b2-7e7d97399730) for the resulting CUDA test.
=> Add CUDA test on CCI

test/common_utils.py, test/test_functional.py, test/test_kaldi_compatibility.py, test/test_torchscript_consistency.py, torchaudio/compliance/kaldi.py
To work on #613, I added a helper function which simplifies the logic to generate test suites for different device, which also extends it to dtype.
As a result, torchscript consistency test is performed on (cpu, cuda) x (float32, float64) matrix. (float64 is newly added)
1. This revealed that some transforms (`Resample`) is not compatible with float64, which is fixed in this PR.
1. Interestingly `lfilter` does not yield consistent result among Python and torchscript only when `float64`.
I looked at it but do not have an immediate fix so I marked them as expected to fail.
=> Introduce common utility for defining test matrix for device/dtype

test/test_kaldi_compatibility.py, torchaudio/compliance/kaldi.py
=> Make Kaldi fbank support cuda

torchaudio/transforms.py
=> Make power and normalized configurable for transforms.MelSpectrogram

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/windows/scripts/install.sh
Tested through 
https://circleci.com/gh/pytorch/audio/45189?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/pytorch/audio/45176?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/pytorch/audio/45191?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Enable CUDA tests for Windows

test/test_functional.py, torchaudio/functional.py
Corresponding PR https://github.com/pytorch/pytorch/pull/35569
This PR will use `istft` from torch repo, which is ported to C++.
This PR will not succeed until the upstream PR is merged and `torch.istft` becomes available.
=> Use istft from torch

README.md
Show the instructions on how to switch the backend amongst available ones, in the readme.
=> backend change instructions in readme

test/test_librosa_compatibility.py, test/test_torchscript_consistency.py, torchaudio/functional.py
=> add slaney normalization

test/common_utils.py, test/test_functional.py, test/test_torchscript_consistency.py
@cpuhrsch 
Part 1 of PyTorch test framework adaptation. Applied to torchscript tests and some functional test.
If this looks good, I will expand the adaptation to other tests.
=> Adopt PyTorch's test util to torchscript test

test/torchscript_consistency_cpu_test.py, test/torchscript_consistency_cuda_test.py, test/torchscript_consistency_impl.py
Currently there is no CUDA device for regular FB's infra, where `torchaudio`'s tests are ran.
Skipping these tests consistently raises a flag so we decided to split the tests into runnable and not-runnable on file-level.
=> Split CUDA and CPU tests of `torchscript_consistency`

test/test_sox_compatibility.py
=> Adopt PyTorch's test util to SoX compatibility test

test/test_librosa_compatibility.py
=> Adopt PyTorch's test util to librosa compatibilities test

.circleci/config.yml, .circleci/config.yml.in
1. Docker image used for smoke test is old (No Python 3.8). Updating this to the latest one. build [here](https://app.circleci.com/pipelines/github/pytorch/audio/1763/workflows/56c846a5-acaa-41a7-92f5-46ec66186c61/jobs/44484)
2. Add `latest` tag to the newly built docker so that later we can always use `latest` version and we do not have to update docker image tag manually.
=> Update smoke test docker image and tag new images latest

test/kaldi_compatibility_cpu_test.py, test/kaldi_compatibility_cuda_test.py, test/kaldi_compatibility_impl.py
- Adopt PyTorch's test utility on kaldi compatibility test
- Separate CPU test and GPU test
=> Adopt PyTorch's test utility on kaldi compatibility test

test/test_io.py
`set(["sox", "soundfile"]) not in set(["sox", "soundfile"])` is never true.
=> Fix io test

test/torchscript_consistency_impl.py, torchaudio/functional.py
Following up on [comment](https://github.com/pytorch/audio/pull/589#discussion_r425449900)
=> Make parameter optional string

test/__init__.py, test/kaldi_compatibility_cpu_test.py, test/kaldi_compatibility_cuda_test.py, test/kaldi_compatibility_impl.py, test/test_batch_consistency.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets.py, test/test_functional.py, test/test_io.py, test/test_kaldi_io.py, test/test_librosa_compatibility.py, test/test_sox_compatibility.py, test/test_sox_effects.py, test/test_transforms.py, test/torchscript_consistency_cpu_test.py, test/torchscript_consistency_cuda_test.py, test/torchscript_consistency_impl.py
This PR contains
- changes to tweak for test import (relative import and addition of `__init__.py`)
- Initialization required to use soundfile in fb infrastructure. This is harmless in other locations, yet `__init__.py` was the best place to put so I included it in public facing code base.
=> Apply tweaks required for running test in fbcode

README.md, build_tools/setup_helpers/build_third_party_helper.sh
There was an issue when building from source in an Anaconda environment under `Arch Linux` where building `liblame` would fail with `undefined reference` errors related to the `ncurses` library (`tgetstr`, `tgetnum`, `tgetent`). This PR allows `liblame` to build under this specific setting.
=> Fix `undefined reference` errors (#666)

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, README.md, build_tools/setup_helpers/extension.py, packaging/build_wheel.sh, packaging/torchaudio/build.sh
This PR changes
1. The way how to decide if codecs/SoX should be built when building torchaudio C++ extension.
It check whether `BUILD_SOX` env is defined or not. (Originally, it was checking the existence of `.use_external_sox` file.)
2. Revert the default behavior of codecs/SoX build.
It does not build codecs/SoX by default.
=> Use environment variable for switching SoX dep

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, build_tools/setup_helpers/build_third_party.sh, build_tools/setup_helpers/build_third_party_helper.sh
Making dozens of connections simultaneously to sourceforge.net makes workflows flaky.
This PR fixes this by making download only once par workflow and cache the downloaded files on for the rest of the day. (so download occurs once a day).
=> Limit the number of downloads par workflow for reliable build

docs/source/functional.rst, test/test_batch_consistency.py, test/test_sox_compatibility.py, test/torchscript_consistency_impl.py, torchaudio/functional.py
Hi ,
Regarding the issue ( Reducing dependency in Sox - #260  ),
This pull request is new version of existing pull request #629 
@mthrok I have made the changes to batch and torch script test .
Now taking random input generated from a seed
=> Add flanger to functional.py

test/test_transforms.py
This will prevent this test from breaking when torch.div is updating to throw a runtime error when it would have performed floor division.
=> Updates test_transform.py to no longer perform floor division

docs/source/functional.rst, test/test_sox_compatibility.py, test/torchscript_consistency_impl.py, torchaudio/functional.py
This is a sox dependency reduction task to implement bass (with biquad) filter as #260 using the treble (with biquad) filter as example.
=> Add Bass with Biquad

test/test_librosa_compatibility.py, torchaudio/common_utils.py, torchaudio/kaldi_io.py
This PR
1. ~~Removes compatibility code for `Python < 3.4` from `torchaudio.common_utils`.~~ #691 
2. Moves `IMPORT_KALDI_IO` global variable to `kaldi_io` module because it's only used there and does not seem to be useful elsewhere.
3. Moves `IMPORT_LIBROSA` global variable to test because it's only used in `test_librosa_compatibility.py`.
4. Removes `IMPORT_NUMPY` and `IMPORT_SCIPY` as they are redundant. (If `librosa` is available `numpy` and `scipy` should be available too, else installation is broken and that's not `torchaudio`'s responsibility to watch out such case.)
=> Clean up common_utils

torchaudio/__init__.py, torchaudio/_backend.py, torchaudio/_internal/misc_ops.py, torchaudio/_soundfile_backend.py, torchaudio/_sox_backend.py, torchaudio/sox_effects.py
`check_input` and `audio_normalization` functions defined in `__init__.py`, `_backend.py` and `_soundfilebackend` (duplicated) are referred from multiple modules and cause cyclic module dependencies and preventing modularizing backends. This PR resolve this by putting them in a separate dedicated module `_internal.misc_ops`.
Also change the helper function name from `audio_normalization` (noun) to `normalize_audio` (verb) for consistency.
=> Move I/O related Tensor ops to misc_ops module

torchaudio/backend/__init__.py, torchaudio/backend/common.py, torchaudio/backend/soundfile_backend.py, torchaudio/backend/sox_backend.py
It is strange that `sox_backend` depends on custom classes defined in `soudfile_backend`. This PR introduces `backend.common` module where these custom classes are defined and have both `sox_backend` and `soundfile_backend` depend on it.
=> Put structs common to backends in backend.common

torchaudio/backend/__init__.py, torchaudio/backend/utils.py
Initialize backend in `backend.__init__.py`.
=> Perform backend initialization in `backend.__init__`

test/common_utils.py, test/torchscript_consistency_cpu_test.py
Summary: The previous implementation of parameterized testing worked by modifying test.common_utils inplace.  This doesn't work in general because unittest's contract with test modules is such that it must be able to load the module and run the test itself.  Because the previous implementation needed to load the module and modify it, it is incompatible.
Differential Revision: D21964676
=> Change parameterized testing system to be compatible with unittest

test/test_functional.py, torchaudio/functional.py
PyTorch started to raise errors when performing integer division with `/`. This PR fixes this with `//`.
Closes #713
=> Fix integer division

test/common_utils.py, test/functional_cpu_test.py, test/functional_cuda_test.py, test/functional_impl.py, test/kaldi_compatibility_cpu_test.py, test/torchscript_consistency_cpu_test.py, test/torchscript_consistency_cuda_test.py
`type` used in `common_utils` generates test class definition in `common_utils` and
this modifies the module state after it's imported. This is anti-pattern.
This PR get rid of the related utility functions and define test suite manually.
Follow up #712
=> Get rid of dynamic test suite generation

torchaudio/__init__.py, torchaudio/_internal/module_utils.py, torchaudio/sox_effects/__init__.py, torchaudio/sox_effects/sox_effects.py
`torchaudio.initialize_sox` (and corresponding `torchaudio.shutdown_sox`) is a confusing function because it sounds like this function has to be called to use any sox functionality though it is required only for SoX Effects. This PR proposes to deprecate these functions and direct users to use `torchaudio.sox_effects.init_sox_effects` (and `torchaudio.sox_effects.shutdown_sox_effects`), if necessary.
=> Add deprecation warning to initialize/shutdown_sox

test/test_backend.py, test/test_datasets.py, torchaudio/__init__.py, torchaudio/backend/__init__.py, torchaudio/backend/common.py, torchaudio/backend/no_backend.py, torchaudio/backend/soundfile_backend.py, torchaudio/backend/sox_backend.py, torchaudio/backend/utils.py
1. Do not rely on global variables for backend switch
So that load/save/info/load_wav functions will be torchscript-able
2. Add no_backend module to for the case there is no backend module available
[bonus] This allows the whole codebase importable on systems that do not have torchaudio C++ extension nor soundfile.
=> Refactor backend and not rely on global variables on switching

test/test_models.py
Update the variable locations in the test of wav2letter model. Variables are put inside the test definition.
=> Update wav2letter test

torchaudio/models/_wavernn.py
This is to adjust the spacing and typing of melresnet block #705 .
=> MelResNet spacing and typing adjustment

test/README.md, test/common_utils.py, test/functional_cpu_test.py, test/functional_cuda_test.py, test/kaldi_compatibility_cpu_test.py, test/kaldi_compatibility_cuda_test.py, test/kaldi_compatibility_impl.py, test/test_backend.py, test/test_batch_consistency.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets.py, test/test_io.py, test/test_kaldi_io.py, test/test_librosa_compatibility.py, test/test_sox_compatibility.py, test/test_sox_effects.py, test/test_transforms.py, test/torchscript_consistency_cpu_test.py, test/torchscript_consistency_cuda_test.py, test/torchscript_consistency_impl.py
Address #715 by
1. Introduce test case `TorchaudioTestCase` which by default unsets audio backend, so that each test has to set which audio backend to be used.
2. Set desired backend on each testcase where it's necessary.
=> Refactor test backend

torchaudio/__init__.py, torchaudio/csrc/register.cpp, torchaudio/csrc/typedefs.cpp, torchaudio/csrc/typedefs.h, torchaudio/extension/__init__.py, torchaudio/extension/extension.py
This is a part of PRs to add new "sox_io" backend. https://github.com/pytorch/audio/pull/726
This PR adds `SignalInfo` structure, which is data exchange interface between Python and C++ in coming TorchScript-based sox IO backend.
For the case, where C++ extension is not available (i.e. Windows), this PR also adds dummy class and module that will be substituted.
This logic is implemented in `torchaudio.extension` moduel.
=> Add SignalInfo typedef, and extension module

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py
Should run binary build and upload jobs on tags now and automatically
upload them to the right channel.
Similar to work that was done for vision here: https://github.com/pytorch/vision/pull/2204
=> .circleci: Add functionality to run on tags

test/sox_io_backend/test_info.py, test/sox_io_backend/test_torchscript.py, torchaudio/csrc/register.cpp, torchaudio/csrc/typedefs.cpp, torchaudio/csrc/typedefs.h, torchaudio/extension/extension.py
This PR fixes the wrong member name of SignalInfo introduced in #718. 
- `num_samples` == `num_frames` * `num_channels`.
=> Fix SignalInfo member name to frame

test/test_models.py
Add subclass `common_utils.TorchaudioTestCase` in model test classes.
Related to #705
=> Add subclass in model test classes

.circleci/config.yml, .circleci/config.yml.in
This PR refactors cache generation mechanism by introducing dedicated command
and bust cache on daily basis.
At this moment, Windows unittest job for 3.6 and 3.7 are broken because of
broken scipy but the environment is cached this persists at least until the next week.
As we have nightly build, we do not need to keep cache for one week.
Note: the SciPy distribution seems to be broken, so this PR does not fix the ongoing Windows unittest job failure.
=> Refactor Cache bust mechanism and bust on daily basis

.circleci/unittest/linux/docker/Dockerfile, .circleci/unittest/linux/scripts/setup_env.sh
In #728, linux unit test switches to libsox provided by apt.
For CPU jobs this is fine because all the job steps share the same Docker container,
but on CPU job, each job step runs a script in a new Docker container, so
libsox installed in a step is not available to the subsequent steps.
To fix this, this PR moves the installation of libsox and sox to Docker build.
=> Bake libsox in test base Docker image

torchaudio/csrc/register.cpp, torchaudio/csrc/sox.cpp, torchaudio/csrc/sox.h, torchaudio/csrc/sox_effects.cpp, torchaudio/csrc/sox_effects.h, torchaudio/sox_effects/__init__.py, torchaudio/sox_effects/sox_effects.py
This PR replaces sox effects `init/list/shutdown` functions with Torch Script binding. (SoxEffectsChain is not changed yet.)
I also moved error checking to C++, so the function signature is changed -> BC breaking.
The previous implementation returned `sox_errot_t` enum to Python, which is practically useless so I think this BC breaking does not have an impact.
=> [BC Breaking] Replace sox_effects init/list/shutdown with TS binding

test/sox_io_backend/common.py, test/sox_io_backend/sox_utils.py, test/sox_io_backend/test_info.py, test/sox_io_backend/test_load.py, test/sox_io_backend/test_torchscript.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/register.cpp, torchaudio/csrc/sox_io.cpp, torchaudio/csrc/sox_io.h, torchaudio/csrc/sox_utils.cpp, torchaudio/csrc/sox_utils.h
This is a part of PRs to add new "sox_io" backend. #726 and depends on #718 and #728 .
This PR adds `load` function to "sox_io" backend, which is  tested on the following audio formats;
- `wav`
- `mp3`
- `flac`
- `ogg/vorbis` *
By default, "sox_io" backend returns Tensor with `float32` dtype and the shape of `[channel, time]`. The samples are normalized to fit in the range of `[-1.0, 1.0]`.
Unlike existing "sox" backend, the new `load` function can handle WAV file natively, when the input format is WAV with integer type, (such as 32-bit signed integer, 16-bit signed integer and 8-bit unsigned integer) by providing `normalize=False`, this function can return integer Tensor, where the samples are expressed within the whole range of the corresponding dtype, that is, `int32` tensor for …
=> Add TorchScript-able "load" func to sox_io backend

torchaudio/functional.py
rollback torch.norm() in spectrogram() to v0.4.0 because torch.norm() is very slow in CPU mode as mentioned in following issues:
- https://github.com/pytorch/audio/issues/740
- https://github.com/pytorch/audio/issues/455
=> rollback torch.norm() in spectrogram()

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/run_test.sh, .circleci/unittest/linux/scripts/setup_env.sh, build_tools/setup_helpers/build_third_party.sh, build_tools/setup_helpers/build_third_party_helper.sh, build_tools/setup_helpers/extension.py
This PR adds ogg/vorbis support to binary build.
@seemethere Can we slip this into the next release?
Solves #674
=> Add ogg/vorbis support to binary distribution

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/run_test.sh, .circleci/unittest/linux/scripts/setup_env.sh, build_tools/setup_helpers/build_third_party.sh, build_tools/setup_helpers/build_third_party_helper.sh, build_tools/setup_helpers/extension.py, torchaudio/csrc/sox.cpp, torchaudio/csrc/sox.h
Cherrypicking #750 for 0.6 release.
=> Add vorbis support to 0.6 release. 

test/common_utils.py, test/sox_io_backend/sox_utils.py, test/sox_io_backend/test_info.py, test/sox_io_backend/test_load.py, test/sox_io_backend/test_roundtrip.py, test/sox_io_backend/test_save.py, test/sox_io_backend/test_torchscript.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/register.cpp, torchaudio/csrc/sox_io.cpp, torchaudio/csrc/sox_io.h, torchaudio/csrc/sox_utils.cpp, torchaudio/csrc/sox_utils.h
This is a part of PRs to add new "sox_io" backend. #726 and depends on #718, #728 and #731.
This PR adds `save` function to "sox_io" backend, which can save Tensor to a file with the following audio formats;
- `wav`
- `mp3`
- `flac`
- `ogg/vorbis` *
~~__* Note__ The current binary distribution of torchaudio does not contain `ogg/vorbis` codecs. To handle these files, one needs to build torchaudio from the source.~~
=> Add TorchScript-able "save" func to sox_io backend

test/test_models.py, torchaudio/models/_wavernn.py
This Upsampling block is part of WaveRNN model. Now the test is to validate the output dimensions of this block. Other tests will be added after other blocks are combined.
Related to #446
Stack:
Add MelResNet Block #705  #751 
**Add Upsampling Block #724**
Add WaveRNN Model #735 
Add example pipeline with WaveRNN #749
=> UpsampleNetwork

test/sox_io_backend/test_torchscript.py, test/test_backend.py, test/test_io.py, torchaudio/backend/utils.py
This PR (and dependent PRs) adds a new backend "sox_io" backend.
(So that users can opt-in, but we do not intend to change the default yet.)
The new "sox_io" backend has the following advantages;
- TorchScript-able 
The data process pipeline written using the new backend can be dumped and used from C++.
- Correct
The original "sox" backend had a number of issues,
- #618 #236 Info length and rate returns different
- #430 #252 Save then load would degrade the data
- https://github.com/pytorch/audio/issues/400#issuecomment-615502956 `load` function cannot handle WAV file correctly.
I have added bunch of tests to make sure that the new backend does not have the same issue.
This includes read/write operaions of `wav`, `flac`, `mp3` and `ogg/vorbis` formats. *
This backend can also read `opus`, …
=> Add TorchScript-based SoX I/O backend

test/functional_cpu_test.py, test/kaldi_compatibility_impl.py, test/test_librosa_compatibility.py, test/test_transforms.py, test/torchscript_consistency_impl.py
This PR replaces `torchaudio.load_wav` with `common_utils.load_wav`, which is a wrapper around `scipy.io.wavfile.read`.
This allows each test to not depend on torchaudio's I/O implementation.
=> Replace `torchaudio.load_wav` with `common_utils.load_wav`

.circleci/unittest/linux/scripts/environment.yml
Issue: https://app.circleci.com/pipelines/github/pytorch/audio/2663/workflows/39102954-8aee-48c3-8e1c-6ff8c61b246b/jobs/71492/steps
Explanation: https://github.com/pypa/pip/issues/5247
When we install dependencies with `conda env update --file "${this_dir}/environment.yml" --prune`, `conda` first installs `llvmlite-0.33.0` but after that when `pip` tries to install `llvmlite<0.32.0,>=0.31.0dev0`, `pip` cannot determine which files it should be deleting so the installation process fails.
~~This was caused by pinned `numba` and removing it resolves it.~~
~~@peterjc123 I saw you added this line, but do we need to pin or even include `numba` in test env requirements? It is not directly required by `torchaudio` or its test job, so I think removing it is safe but would like to understand why it …
=> Fix CI: Cannot uninstall a distutils installed project

test/test_models.py, torchaudio/models/_wavernn.py
This is the WaveRNN model. 
Related to #446
Stack:
~~Add MelResNet Block #705, #751~~
~~Add Upsampling Block #724~~
**Add WaveRNN Model #735**
Add example pipeline with WaveRNN #749
=> Add WaveRNN Model

test/README.md
This PR adds instructions around generating waveforms in tests from files and on the fly, as well as contributing new assets.
=> Add Waveforms for Testing Purposes section to test/README.md

torchaudio/backend/sox_io_backend.py, torchaudio/csrc/register.cpp, torchaudio/csrc/sox_io.cpp, torchaudio/csrc/sox_io.h
In #779, we plan to remove `frames_per_chunk` parameter from `save` function, but it will take some time before we can land #779, so we go ahead and remove the parameter first to reduce the conflict caused by interface change.
=> Remove frames_per_chunk argument from save

test/common_utils/data_utils.py, test/test_sox_compatibility.py, test/test_sox_effects.py
Convert mp3 to wav or on the fly generation.
=> Issue 764: Convert mp3 to wav

test/test_sox_effects.py
`test/test_sox_effects.py::Test_SoxEffectsChain::test_lowpass_speed` has some issue on our macOS CI, even though there was no issue at #777 .
While we figure out the fix, we disable this test for macOS.
=> Skip lowpass test on macOS

test/common_utils/sox_utils.py, test/test_sox_compatibility.py
This PR replaces `torchaudio.sox_effects.SoxEffectsChain` in `test_sox_compatibility` with bare `sox` command.
The parity of `torchaudio.sox_effects.SoxEffectsChain` against `sox` command is not tested and it has known issues https://github.com/pytorch/audio/issues/771, therefore it is not appropriate to use this class for testing other functions.
=> Do not use SoxEffectsChain in sox compatibility test

test/test_models.py, torchaudio/models/_wavernn.py
This is to update the variable names in [WaveRNN model](https://github.com/pytorch/audio/pull/735).
Related to #735
=> Update variable names in wavernn model

torchaudio/models/_wavernn.py
This is to update the form of default value in docstring of WaveRNN to match [the form in torchaudio](https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py#L40).
Related to #705 , #724 , #735
=> Update form of default value in docstring

docs/source/backend.rst, docs/source/index.rst, docs/source/sox_effects.rst, docs/source/torchaudio.rst, docs/source/utils.rst, torchaudio/__init__.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py, torchaudio/functional.py, torchaudio/models/wav2letter.py, torchaudio/sox_effects/sox_effects.py, torchaudio/transforms.py, torchaudio/utils/sox_utils.py
- Addresses #549 #638 #786 
- Add `torchaudio` top level module doc
- Separate `torchaudio` top level module doc from `index.html`
- Add `backend` module doc.
- Remove `-> None` from function signature as it adds noise to documentation
- Changed function argument name of `torchaudio.backend.sox_io_backend.save` from `tensor` to `src`, so that it matches with the reset of backends.
- Tweak bunch of docstrings
=> Update documentation and fix docstrings

test/functional_cpu_test.py, test/test_batch_consistency.py, test/test_compliance_kaldi.py, test/test_dataloader.py, test/test_datasets.py, test/test_io.py, test/test_kaldi_io.py, test/test_librosa_compatibility.py, test/test_sox_compatibility.py, test/test_sox_effects.py, test/test_transforms.py
Before the change:
```
grep 'if __name__' -r test
test/test_batch_consistency.py:if __name__ == '__main__':
test/test_kaldi_io.py:if __name__ == '__main__':
test/test_compliance_kaldi.py:if __name__ == '__main__':
test/test_dataloader.py:if __name__ == '__main__':
test/test_sox_compatibility.py:if __name__ == "__main__":
test/test_datasets.py:if __name__ == "__main__":
test/functional_cpu_test.py:if __name__ == '__main__':
test/test_sox_effects.py:if __name__ == '__main__':
test/test_io.py:if __name__ == '__main__':
test/compliance/generate_fbank_data.py:if __name__ == '__main__':
test/compliance/generate_test_stft_data.py:if __name__ == '__main__':
test/test_transforms.py:if __name__ == '__main__':
test/assets/io/generate_opus.py:if __name__ == '__main__': …
```
=> Remove if __name__ == __main__ from test code

test/assets/sox_effect_test_args.json, test/sox_effect/common.py, test/sox_effect/smoke_test.py, test/sox_effect/test_dataset.py, test/sox_effect/test_sox_effect.py, test/sox_effect/test_torchscript.py, test/sox_io_backend/smoke_test.py
Currently all the tests in `sox_io_backend` and `sox_effects` (for new SoX effects implementation) requires additional `sox`, and this prevents running test in environment where `sox` command is not available even though `torchaudio` extension is available (such as fb internal). This PR adds smoke tests for these modules, which just runs functions to see if they do not crash.
=> Add smoke tests to sox_io and sox_effects

test/README.md, test/sox_effect/sox_effects_chain_test.py, test/test_sox_compatibility.py
1. Move misplaced sox compatibility tests (`T,Fade`, `T.Vol`, `T.Vad`) from `test_sox_effects.py` to `test_sox_compatibility.py`
2. Move `test_sox_effects.py` to `test/sox_effect/` where all the other functionalities from `torchaudio.sox_effects` are tested
=> Refactor test_sox_effects

test/sox_io_backend/smoke_test.py, test/utils/test_sox_utils.py, torchaudio/csrc/register.cpp, torchaudio/csrc/sox_utils.cpp, torchaudio/csrc/sox_utils.h, torchaudio/utils/sox_utils.py
Turned out that `libsox` in fbcode only has reader (`libmad`) and not writer (`libmp3lame`), therefor the smoke test added in #806 cannot run as is.
I tried to add skip condition using `sox_utils.list_formats` utility but this function does not care if a format handler has writer or not. (cf. `libsox` does not implement writer for `opus` too)
From the user point of view, and debugging the installation, this is confusing and not very convenient, so this PR splits `torchaudio.utils.sox_utils.list_formats()` into `torchaudio.utils.sox_utils.list_read_formats()` and `torchaudio.utils.sox_utils.list_write_formats()`.
=> [BC Breaking] Split `list_formats()` for read and write

torchaudio/csrc/sox_effects_chain.cpp, torchaudio/csrc/sox_effects_chain.h, torchaudio/csrc/sox_io.cpp
This PR is built on top of #760 , and it merges `sox_io` backend `load`/`save` functions with `sox_effects` on C++ side. No BC breaking as it's C++ internal.
~The number of frames to process at a time (`frames_per_chunk` parameter of `save` function) can be adjusted via `torchaudio.utils.sox_utils.set_buffer_size`, so removed from the function signature.~ Addressed in #780 separately
=> Merge sox effect and sox_io C++ implementation

test/datasets/libritts_test.py, test/datasets/utils_test.py, test/datasets/yesno_test.py, torchaudio/datasets/utils.py
=> Make directory traversal order alphabetical and breadth-first

test/sox_io_backend/smoke_test.py
Buck is not happy when test name contains "-" symbol, and it fails to run these tests.
=> Avoid "-" symbol in test name

test/datasets/libritts_test.py
This is to update the sample rate in libritts_test file.
In [LibriTTS](https://arxiv.org/pdf/1904.02882.pdf):
channel = 1
sample rate = 24 kHz
I use an arbitrary duration value in the test.
Related to #790
=> Update sample rate of libritts test

docs/source/backend.rst, docs/source/index.rst, docs/source/sox_effects.rst, docs/source/torchaudio.rst, torchaudio/__init__.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py, torchaudio/functional.py, torchaudio/models/wav2letter.py, torchaudio/sox_effects/sox_effects.py, torchaudio/transforms.py
- Addresses #549 #638 #786
- Add `torchaudio` top level module doc
- Separate `torchaudio` top level module doc from `index.html`
- Add `backend` module doc.
- Remove `-> None` from function signature as it adds noise to documentation
- Changed function argument name of `torchaudio.backend.sox_io_backend.save` from `tensor` to `src`, so that it matches with the reset of backends.
- Tweak bunch of docstrings
=> Update documentation and fix docstrings (#788)

examples/pipeline_wavernn/main.py, test/test_models.py, torchaudio/models/__init__.py, torchaudio/models/wavernn.py
Remove name underscore of WaveRNN model and its related blocks.
Related to #705 #724 #735 #749
=> Remove underscore of wavernn model

test/datasets/yesno_test.py
All the dummy data generated in YesNo dataset test have the same values, which makes it pointless to perform Tensor comparison. This PR fixes it by adding unique seed values to data generation.
=> Fix seed of yesno dataset test

test/common_utils/__init__.py, test/common_utils/backend_utils.py, test/test_io.py
Now that most of our test cases are backend aware/agnostic,
the use of BACKENDS and BACKENDS_MP3 is anti-pattern.
This change moves these definitions to the legacy test module `test_io` which is 
the only module using these.
If a new backend is added in future, that backend should have separate test suite,
(like the ones in `test/sox_io_backend`) so instead of dynamically listing available
backend in `test_io`, the changed code only checks "sox" backend and "soundfile" backend.
=> Move BACKEDNS and BACKENDS_MP3 to test module from common_utils

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/run_test.sh
Currently macOS CI job takes twice the time of linux unit tests.
This PR uses `pytest-xdist` to run unit tests in parallel on macOS CI job. 
Interestingly applying the same technique to linux unit tests make the test execution longer.
So the change is only applied to macOS.
macOS 27 mins -> 17 mins 😸
linux 14 mins -> 1 hours 😾
=> Run tests in parallel with pytest-xdist

examples/pipeline_wavernn/datasets.py, examples/pipeline_wavernn/main.py
Add libritts dataset option in #749 
Related to #790
=> Add libritts dataset option

setup.py
setuptools warns that it should be imported before Distutils
```
site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
```
=> Fix import order to suppress the setuptools warning

.circleci/unittest/linux/scripts/run_test.sh, test/common_utils/case_utils.py
I am trying to fix the issue C++ extension availability when building/installing torchaudio from source. See https://github.com/pytorch/audio/pull/842 for the detail.
Currently our test suites automatically/silently skip tests on C++ extension if it is not available.
This is nice in local env, but in CI these tests should be enforced and reported as failure if C++ extension is not available.
This PR adds switch for making tests fail if C++ extension is not available.
This should make https://github.com/pytorch/audio/pull/845 fail so that we can debug what is wrong with the current setup.
=> [CI] Make *nix unit test fail if C++ extension is not available

test/common_utils/case_utils.py
There was a flaw in the logic introduced in #847, and now that tests that require C++ extension are skipped all the time. This PR fixes it.
=> Fix skipIfNoExtension

setup.py
Currently `setuptools` assumes that torhcaudio is zip safe and performs
egg (zip) installation when `python setup.py install` (or `pip install .`).
When torchaudio load extension module written for Torchscript, the corresponding
loading function requires the `so` file to be present as an actual file, and this
does not work well with egg installation.
This PR fixes this by setting `zip_safe=False` in setup.py and disable egg
installation, so that `python setup.py install` installs uncompressed files
with regular directory structure.
The following is the error you get when you try to use the package installed with
`python setup.py install`, before this change.
```
import torchaudio
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line …
```
=> Set zip_safe = False to disable egg installation

.circleci/config.yml, .circleci/config.yml.in
There was an issue where binaries from the `pytorch-test` channel were
being installed when smoke testing for the `pytorch-nightly` channel,
this remedies that by only using the channel we're actually supposed to
be testing with.
Resolves https://github.com/pytorch/audio/issues/858
=> .circleci: Only install the binaries from the channel we want

examples/pipeline_wavernn/main.py, examples/pipeline_wavernn/processing.py
This is to add the spectrogram normalization option in [WaveRNN pipeline](https://github.com/pytorch/audio/pull/749).
=> Add spectrogram normalization option

torchaudio/csrc/register.cpp
This PR replaces the raw PyTorch C++ registration mechanism with `TORCH_LIBRARY` macro.
=> Simplify C++ registration with TORCH_LIBRARY

test/torchaudio_unittest/sox_io_backend/info_test.py, test/torchaudio_unittest/sox_io_backend/load_test.py, test/torchaudio_unittest/sox_io_backend/save_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox_utils.cpp
=> Add SPHERE support to "sox_io" backend

.circleci/config.yml, .circleci/config.yml.in
`torchscript_bc_test` which compiles multiple version of `torchaudio` gets OOM errors. This PR fixes it by increasing the CI resource.
=> [CI] Increase resource class to prevent OOM

.circleci/unittest/linux/scripts/environment.yml
Conda environment set up fails for the second time when NumPy version is unspecified.
=> [CI] Fix macOS unittest env setup

test/torchaudio_unittest/sox_io_backend/save_test.py, torchaudio/backend/sox_io_backend.py
Existing implementation doesn't work for FLAC format.
=> Fix incorrect extension parsing

test/torchaudio_unittest/sox_io_backend/save_test.py
Looks like `sox` command is doing something elaborated for filing the default compression value for `mp3` and cannot find a way to recreate the exact behavior. So removing the test for consistency for default compression value.
=> Remove default compression level test for mp3

.circleci/config.yml, .circleci/config.yml.in
When running smoke test, proper way to install conda package is to
install from workspace, instead of installing from archive.
Otherwise the dependencies are not properly installed
https://github.com/conda/conda/issues/1884
For this, we pass the whole `conda-bld` directory from
conda package build job to upload job then smoke test job.
`torchaudio` does not have a mandatory third-party python package dependency,
so this was not an issue.
See also https://github.com/pytorch/text/pull/803
=> [CI] Install conda package from workspace

.circleci/config.yml, .circleci/config.yml.in, .circleci/unittest/linux/scripts/environment.yml
Upstream is on 9.4.1 and we were experiencing issues when conda-build
was attempting to check for overlinking and failed out due to some files
not existing in xcode 9.0
Should fix issues for macOS builds
Similar to https://github.com/pytorch/vision/pull/2633
=> .circleci: Bump xcode workers to 9.4.1

docs/source/datasets.rst, test/torchaudio_unittest/datasets/tedlium_test.py, torchaudio/datasets/__init__.py, torchaudio/datasets/tedlium.py
Hi!
So this is my pull request for adding tedlium support (all 3 releases of tedlium) reference to https://github.com/pytorch/audio/issues/765.
The code is not yet finished (still need to add test, read the phonetic dictionaries of each release, proper formatting) but I wanted to create the PR to get some feedback on the way I read/iterate tedlium files and if the torchaudio manteiners are okay with it or have an idea on how to improve it. This way I make sure the core of the datasetloader is good to merge and I can start working on the test or change it before coding the tests. I will explain how I iterate through the dataset now.
Tedlium dataset (all releases) is composed of `.sph` and `.stm` files. These files are divided in the root folder in two different folders:
```
sph/
stm/
``` …
=> Add tedlium dataset (all 3 releases)

packaging/pkg_helpers.bash
Default to using the `cpu` directory since the base one is not reliable
similar to https://github.com/pytorch/text/pull/981
=> packaging: Use cpu directory by default

torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py
Allows for passing of `pathlib.Path` `filepath` to sox_io functions.
See #902.
For type union docstrings I used (str/pathlib.Path), as I found this pattern was used in the `kaldi_io` methods (for str/FileDescriptor). 
There may be a better pattern though?
=> Add pathlib.Path support to sox_io backend

test/torchaudio_unittest/functional/functional_cpu_test.py, torchaudio/functional.py
The default parameters for creating Mel filterbanks can result in some mel features always being zero.
This PR is to warn that this is occurring.
This resembles the following issue:
https://github.com/librosa/librosa/issues/478
The unit tests can be run as follow:
```
pytest -k TestCreateFBMatrix test/torchaudio_unittest/functional/functional_cpu_test.py
```
=> Issue warning when a Mel filter bank bin is empty

.circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/run_test.sh
This reverts commit 1ecbc249b5eed3a2e0e765ac0046e2bf9c231884.
Reason: The macOS CI jobs are stuck with xdist recently.
**Note** some macOS CI unittest jobs are still failing at environment setup which is not caused by this PR and is going to be fixed by a separate PR.
=> [CI] Disable xdist in macOS unittest in CI

test/torchaudio_unittest/backend_test.py, test/torchaudio_unittest/common_utils/wav_utils.py, test/torchaudio_unittest/io_test.py, test/torchaudio_unittest/soundfile_backend/common.py, test/torchaudio_unittest/soundfile_backend/info_test.py, test/torchaudio_unittest/soundfile_backend/load_test.py, test/torchaudio_unittest/soundfile_backend/save_test.py, torchaudio/__init__.py, torchaudio/backend/__init__.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py
As a part of the "sox" backend sunset plan (#903), we add a "soundfile" backend that is compatible with the "sox_io" backend.
This PR contains;
- The implementation of the new "soundfile" backend.
- The function and global flag to switch the behavior of "soundfile" backend.
No new public backend is added. We provide a switch to change the interface/behavior of "soundfile" backend.
- Test for the new backend.
The default behavior of "soundfile" backend is not changed. The users who want to opt-in the new "soundfile" interface can do so by `torchaudio.backend.utils.use_soundfile_legacy_interface(False)` before changing the backend to "soundfile".
In 0.8.0 release, the "soundfile" backend will use this interface by default, and users can still use the legacy one with …
=> Add soundfile compatibility backend 

torchaudio/functional.py
master: 
```
$ python test/test_sox_compatibility.py TestFunctionalFiltering.test_phaser_sine
Fail to import hypothesis in common_utils, tests are not derandomized
.
Ran 1 test in 9.838s
$ python test/test_batch_consistency.py TestFunctional.test_phaser
Fail to import hypothesis in common_utils, tests are not derandomized
.
Ran 1 test in 46.989s
OK
```
fastephaser1:
```
$ python test/test_sox_compatibility.py TestFunctionalFiltering.test_phaser_sine
Fail to import hypothesis in common_utils, tests are not derandomized
.
Ran 1 test in 5.924s
OK
$ python …
```
=> Suggested changes to speed up phaser

docs/source/datasets.rst, torchaudio/datasets/cmuarctic.py, torchaudio/datasets/commonvoice.py, torchaudio/datasets/gtzan.py, torchaudio/datasets/librispeech.py, torchaudio/datasets/libritts.py, torchaudio/datasets/ljspeech.py, torchaudio/datasets/speechcommands.py, torchaudio/datasets/tedlium.py, torchaudio/datasets/vctk.py, torchaudio/datasets/yesno.py
Currently the documentation page does not list constructor arguments or overwrote `__getitem__` methods. This PR fixes it.
(Note: the annotation is broken form the beginning and I cannot fix it.)
Example:
=> Update docstrings/documentations of all the datasets

examples/source_separation/utils/__init__.py, examples/source_separation/utils/dataset/__init__.py, examples/source_separation/utils/dataset/utils.py, examples/source_separation/utils/dataset/wsj0mix.py, test/torchaudio_unittest/example/souce_sepration/wsj0mix_test.py
#897
- Add wsj0mix dataset
- Add test to `test/torchaudio_unittest`
=> Add wsj0mix dataset

torchaudio/datasets/vctk.py
For the consistency with the other dataset implementation, changing VCTK_092 to return plain tuple.
@Abhi011999 Heads up. I advised you to use `namedtuple` for better usability, but I have to change it to the regular tuple for the consistency with the others. Sorry for any inconvenience this could cause.
=> Make VCTK_092 return regular type for the consistency

packaging/pkg_helpers.bash
Following the review on https://github.com/pytorch/text/pull/1037, apply the same change on `torchaudio`.
Note: This commit should also go to release branch.
=> Update package script to use UPLOAD_CHANNEL env

torchaudio/__init__.py, torchaudio/sox_effects/sox_effects.py
Make the sox deprecations explicit about the future version, at which they are removed.
@mattip I was working on updating deprecation decorators and took the opportunity to solve the issue you were facing. Not sure how doc works are organized, but when we build versioned docs and if we are building it from `release/0.7`, then it will be reflected.
=> Make removal version explicit for sox deprecations

test/torchaudio_unittest/sox_effect/dataset_test.py
Some tests are failing on very specific environments and we believe it's related to PyTorch/Python internal. See https://github.com/pytorch/pytorch/issues/46409 for the detail. For the time being, we disable the corresponding test.
=> Skip failing tests on macOS Python 3.6/3.7

docs/requirements.txt
Currently there is no version specification for `sphinx` in docs and `pip install -r requirements.txt` would install the version that produces the corrupted rendering for function signatures. This issue is fixed by using `2.4.4`, which is [the same version as PyTorch](https://github.com/pytorch/pytorch/blob/master/docs/requirements.txt#L1)
*Note*: This commit should also go to master branch.
Before
After
=> Fix doc rendering

.circleci/torchscript_bc_test/common.sh, .circleci/unittest/linux/scripts/run_style_checks.sh, .circleci/unittest/linux/scripts/setup_env.sh
In [Vision-2372](https://github.com/pytorch/vision/issues/2372) we fixed the clang-format version. @mthrok [proposed](https://github.com/pytorch/vision/pull/2872#issuecomment-714495595) to do the same in audio.
=> Fixing clang-format version to what PyTorch uses.

test/torchaudio_unittest/datasets/speechcommands_test.py, torchaudio/datasets/speechcommands.py
Add SpeechCommands train/valid/test split. This follows the convention established in [gtzan](https://github.com/pytorch/audio/blob/master/torchaudio/datasets/gtzan.py#L1014).
=> Add SpeechCommands train/valid/test split

docs/source/backend.rst, test/torchaudio_unittest/backend_test.py, torchaudio/__init__.py, torchaudio/backend/utils.py
Refer to #903 for the overview of planned I/O changes.
* Change the default backend from `"sox"(deprecated)` to `"sox_io"`
* Change the default interface of `"soundfile"` backend to the one identical to `"sox_io"` backend.
* Update documentations
* Re-order backends (default first)
* Update overhaul timeline (removed 0.7.0)
* Simplify `"soundfile"` backend description
=> Switch the default backend to the ones with new interfaces

torchaudio/_internal/fft.py, torchaudio/compliance/kaldi.py, torchaudio/functional.py
Update `torch.rfft` (deprecated) to use the equivalent of `torch.fft.rfft` but without importing `torch.fft`.
Also, update power computation of complex value tensor to use complex type tensor.
=> Update torch.rfft to torch.fft.rfft and complex tensor

docs/source/torchaudio.rst
The sox_effects utilities are removed from top-level module (in [#977](https://github.com/pytorch/audio/pull/977/files#diff-d0f09e250b950133e187b5e43cac6f7693afb38c550b657b604e8c9aa0b1d5e1)), but the documentation was not updated.
**Before:** https://pytorch.org/audio/0.7/torchaudio.html
**After:**
=> [Doc] Remove sox_effects util from top level module

docs/source/functional.rst
This PR applies the grouping in functional doc similar to #1004
Before: https://pytorch.org/audio/0.7/functional.html
After:
=> [Doc] Update functional.rst to group filterings

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/linux/scripts/setup_env.sh, .circleci/unittest/windows/scripts/setup_env.sh
- Enable GPU tests for all the PRs as we are seeing cases where CI jobs are failing due to bug or setup failure.
- Fix GPU jobs where environment variable were not passed from configuration
=> Run GPU test for all PRs and fix setup

.circleci/build_docs/build_docs.sh, .circleci/build_docs/commit_docs.sh, .circleci/build_docs/install_wheels.sh, .circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py
This creates a job to build docs and push them. The basic idea is to reuse the install part of the ~unittest~ smoke_test jobs, and then do
```
pushd doc
pip install -r requriements.txt
build html
popd
```
Then a separate step commits the built documentation, checks out the gh-pages branch, copies the rendered documentation into the correct directory, commits it, and pushes the result to the branch.
Things I don't understand about the config.yml, I hope I did it right
~- how do the unittest_linux_cpu jobs know not to run if the build job fails? There is no `requires` clause~
- git push hopefully will JustWork when a PR is merged, although it will fail when done on a fork (like when people submit a PR). Should I limit the job to only run on nightly to avoid the problem?
=> build docs and push to branch in CI

test/torchaudio_unittest/datasets/yesno_test.py, torchaudio/datasets/yesno.py
Relates to #950 .
Conversion added in the `__init__` function to convert Path object to string.
For adding a unit test should I refactor [existing one](https://github.com/pytorch/audio/blob/5e54c770b41bbdb7b228fe511b364f3f2aa96a88/test/torchaudio_unittest/datasets/yesno_test.py#L39) like below 
```python
def test_yesno_util(dataset):
...  comparison code
def test_yesno_str():
dataset = yesno.YESNO(self.root_dir)
test_yesno_util(dataset)
def test_yesno_path():
dataset = yesno.YESNO(Path(self.root_dir))
test_yesno_util(dataset)
```
@vincentqb could you review these changes
=> YesNo Dataset Pathlib change

README.md
Sorry for my sudden PR.
I've just started using this project, and while I was reading the README, I noticed that `PyTorch` and `Pytorch` are not written consistently.
If this is a deliberate change, I apologize for my misunderstanding. 
However, If my understanding is correct, I would like to suggest changing the notation from `Pytorch` to `PyTorch`, just in case.
Thank you very much for your consideration.
Closes #1030
=> Correct notation fluctuation in README.md

test/torchaudio_unittest/datasets/speechcommands_test.py, torchaudio/datasets/speechcommands.py
Relates to #950 
Made some changes in speechcommand tests
In the existing one both `testSpeechCommands` and `testSpeechCommandsNone` are equivalent as the default argument for `subset` is **None**. So removed the `testSpeechCommandsNone` test
- Factored the common comparison in all tests into `_testSpeechCommands`
- Existing  `testSpeechCommands` is now `testSpeechCommands_str`
- Added new `testSpeechCommands_path`
- train,valid,test functions changed to use the common comparison code
@vincentqb could review these changes.
Do we need separate Path testing for train,valid,test subset ? I think it is not needed as we are already testing the Path functionality using whole dataset .
=> Add pathlib support for SPEECHCOMMANDS

.circleci/build_docs/commit_docs.sh
The fix in #1034 got a little further in the [document commit job](https://app.circleci.com/pipelines/github/pytorch/audio/3893/workflows/23a3e829-9592-499a-8445-acf0884f0179/jobs/117250), but there was another mistake: the documentation lives in the top-level directory not inside `docs`. This PR should fix it. Also fix for first-time creation of the directories if they do not exist.
=> Fix doc commit script 2

test/torchaudio_unittest/datasets/tedlium_test.py, torchaudio/datasets/tedlium.py
Relates to #950 
- Factored the common comparison in all tests into `_test_tedlium`
- `path` test only for release1
=> Add pathlib support for TEDLIUM

test/torchaudio_unittest/sox_effect/sox_effect_test.py, torchaudio/sox_effects/sox_effects.py
Relates to #950 
For unit test copied the test for , I copied the existing one and passed Path object .
Didn't do any factoring as it fetching parameters of test case
=> Add Pathlib support for 'apply_effects_file'

torchaudio/sox_effects/sox_effects.py
cc #1048
(Out of scope for this PR: the lint test should pick unused dependencies where relevant and possible.)
=> remove unused imports in sox_effects

.circleci/unittest/linux/scripts/setup_env.sh, test/torchaudio_unittest/sox_effect/dataset_test.py, third_party/CMakeLists.txt
Sox effect functions and subprocess cause issues like #1021. 
In this PR, I added the tests that mimic this issue. This test properly fails in my development env (see the log bellow), however, it somehow does not fail in our CI. Furthermore, all the tests in `test/torchaudio_unittest/sox_effects/dataset_test.py` can fail with segmentation fault on my local env, but it does not happen in our CI. My environment is very similar to the CI settings (Docker/Ubuntu + Anaconda), and I can reproduce the issue on my working env but I have not figured out the key difference between my local env and CI.
What are common to these failure cases include;
* Run `sox_effects` in subprocess.
* Subprocesses are launched with `fork` method.
What we know is that;
* With `fork` method, setting …
=> Temporarily Disable OpenMP support for libsox

torchaudio/functional/functional.py
Tiny docstring typo - double "a"
=> Fix typo in docstring

torchaudio/csrc/sox_effects.cpp, torchaudio/csrc/sox_effects.h, torchaudio/csrc/sox_io.cpp, torchaudio/csrc/sox_io.h
This replaces how optional arguments are processed in C++ code by using `c10::optional`.
=> Use c10:optional in optional arguments

README.md
The only assumption I made was that when referring to dimensions, "channel" was able to be more than one. Let me know if that is not the case, and then I can change it back.
Edit: 
I only changed the README, so the test failures do not appear related to anything I did.
=> Fix multiple grammar and spelling mistakes in README

test/torchaudio_unittest/sox_effect/dataset_test.py, third_party/CMakeLists.txt
Currently `libsox` on Linux is compiled with GPU OpenMP and it interferes with the version PyTorch uses (Intel in case of binary distribution). This PR disables OpenMP support for `libsox`, while we investigate the way to use the same OpenMP as PyTorch's version.
=> Cherry-pick: Temporarily Disable OpenMP support for libsox (#1026)

test/torchaudio_unittest/datasets/utils_test.py, torchaudio/datasets/commonvoice.py
CommonVoice requests a user agreement before downloading, see [here](https://commonvoice.mozilla.org/en/datasets).
- raise an error if url is not None
- raise an error if download is True, and a warning if False
This should be cherry picked for 0.7.1.
=> no longer download CommonVoice directly

test/torchaudio_unittest/datasets/utils_test.py, torchaudio/datasets/commonvoice.py
This PR cherry picks #1018 for 0.7.1
cc @seemethere
=> [Cherry-pick for 0.7.1] no longer download CommonVoice directly

docs/source/datasets.rst, docs/source/functional.rst, torchaudio/functional/filtering.py, torchaudio/functional/functional.py, torchaudio/sox_effects/sox_effects.py, torchaudio/utils/sox_utils.py
=> [DOC] Add missing modules and minor fixes

build_tools/setup_helpers/extension.py, test/torchaudio_unittest/sox_io_backend/info_test.py, test/torchaudio_unittest/sox_io_backend/load_test.py, test/torchaudio_unittest/sox_io_backend/save_test.py, third_party/CMakeLists.txt, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox_io.cpp, torchaudio/csrc/sox_utils.cpp
This PR adds AMR-NB (R/W) and AMR-WB (R only) support to "sox_io" backend.
On my mac, I was getting the following error which I had thought was ABI issue, but turned out that opencore-amr support with dynamic loading was accidentally enabled.
<details><summary>error</summary>
```
% python -c 'import torchaudio'
File "<string>", line 1, in <module>
File "/Users/moto/Development/torchaudio/torchaudio/__init__.py", line 1, in <module>
from . import extension
File "/Users/moto/Development/torchaudio/torchaudio/extension/__init__.py", line 5, in <module>
_init_extension()
File "/Users/moto/Development/torchaudio/torchaudio/extension/extension.py", line 12, in _init_extension
_init_script_module(ext)
File …
```
=> Add AMR-NB/WB support to "sox_io" backend

test/torchaudio_unittest/common_utils/sox_utils.py, test/torchaudio_unittest/soundfile_backend/load_test.py, test/torchaudio_unittest/sox_io_backend/load_test.py, third_party/CMakeLists.txt, third_party/patch/libsox.patch
When it comes to `mp3` format detection, `libsox` only depends on the file extension. (See #1040)
This PR adds header-based format detection to `mp3`.
Relates to #1040 
~Should go to `0.7.1` release.~ Will ask users to test with nightly build.
=> Add support for loading mp3 files without extension to "sox_io" backend

.circleci/config.yml, .circleci/config.yml.in
This change is necessary for the PRs against release branch to use PyTorch RC for testing.
=> Hard code package channel for release branch

torchaudio/datasets/commonvoice.py
After https://github.com/pytorch/audio/pull/1075 is merged, this PR disallows `download=True`.
=> [0.7.1] Disallow download=True in CommonVoice

test/torchaudio_unittest/datasets/utils_test.py, torchaudio/datasets/commonvoice.py
This reverts commit 09a6fca18a9de33bb8e3c365d171bc82bbc5ee2b.
See #1077 for the agenda.
=> Revert "no longer download CommonVoice directly (#1018)"

torchaudio/functional/functional.py
Hi, I found that the function "detect_pitch_frequency" is inserted twice times to list __all__.  [line 1](https://github.com/pytorch/audio/blob/19fc580da97baf179395bb257647c5c25b993e42/torchaudio/functional/functional.py#L19), [line 2](https://github.com/pytorch/audio/blob/19fc580da97baf179395bb257647c5c25b993e42/torchaudio/functional/functional.py#L27) . So I just remove one of them.
`
__all__ = [
"spectrogram",
"griffinlim",
"amplitude_to_DB",
"DB_to_amplitude",
"compute_deltas",
"create_fb_matrix",
"create_dct",
"compute_deltas",
"detect_pitch_frequency",
"DB_to_amplitude",
"mu_law_encoding",
"mu_law_decoding",
"complex_norm",
"angle",
"magphase",
"phase_vocoder",
"detect_pitch_frequency",
'mask_along_axis',
'mask_along_axis_iid',
'sliding_window_cmn',
]
`
=> Remove twice coded line on __all__

.circleci/build_docs/commit_docs.sh, .circleci/config.yml, .circleci/config.yml.in
Continuation of gh-1049, gh-1041, gh-1034, gh-1031, gh-1006 to automate the docs build and push the result to the gh-pages branch. We cannot use the checkout step since it will force push-via-ssh, which will fail. Instead re-use the git checkout from the `build_docs` step.
Also remove the "designate_upload_channel" step which is for uploading wheels, which is not necessary here.
=> remove checkout step from upload

torchaudio/datasets/librispeech.py, torchaudio/datasets/libritts.py, torchaudio/datasets/speechcommands.py, torchaudio/datasets/yesno.py
Hello @vincentqb,
I wanted to take an initial stab at this. I have made a minor modification for 
Looks like `tedlium`, `ljspeech` and `vctk` (VCTK_092) don't have `walk_files`
cc https://github.com/pytorch/audio/issues/1051
=> Using Path and glob instead of walk_files

test/torchaudio_unittest/batch_consistency_test.py, torchaudio/functional/functional.py
=> Update calls to torch.stft to have return_complex=True

.circleci/config.yml, .circleci/config.yml.in
The nightly task [ran but failed](https://app.circleci.com/pipelines/github/pytorch/audio/4135/workflows/4d0ea223-9e2e-47c4-95b3-3140a60c9f8d/jobs/127799). The debug line to show the contents of `doc` should have been `docs` instead. It did, however confirm the existance of the `docs` directory, so the PR removes the debug cruft so the script hopefully will run to completion.
<details>
<summary>Log output</summary>
```
#!/bin/bash -eo pipefail
set -ex
echo $PWD
ls ~/workspace
ls ~/workspace/doc
tag=${CIRCLE_TAG:1:5}
target=${tag:-master}
.circleci/build_docs/commit_docs.sh ~/workspace $target
+ echo /root/project
/root/project
+ ls /root/workspace
archives	    README.md
build_tools	    requirements.txt
CODE_OF_CONDUCT.md  setup.py
docs		    test
examples	    third_party
LICENSE …
```
=> remove buggy debug cruft

.circleci/config.yml, .circleci/config.yml.in
Continuation of gh-1093: the script is located in the repo, which is in `~/workspace`.
Is there a way to trigger the nightly build after merging this so the cycles of trial and error can move faster?
=> script is not in PWD

test/torchaudio_unittest/datasets/commonvoice_test.py, test/torchaudio_unittest/datasets/utils_test.py, torchaudio/datasets/commonvoice.py
After #1080, this PR 
* removes downloading feature and logics 
* [BC-breaking] expects the dataset directory to be provided by users as `root` argument
* then deprecate the related constructor arguments
API-wise, it is not BC-braking, but users have to change the root directory they give to `root` argument.
|              |  `root` argument | Directory where data set is expected |
|--------|------------------|------------------------------------------------------|
| Before: |`<root_dir>`         | `<root_dir>/CommonVoice/<VERSION>/<LANGUAGE>` |
| After: |`<root_dir>`         | `<root_dir>` |
If you were using, `root="/data", url="english", version="cv-corpus-4-2019-12-10"`, then you need to change the `root` to `/data/CommonVoice/cv-corpus-4-2019-12-10/en`, (and you can should the `url` …
=> [BC-Breaking] Remove execution path for download=True and clean up

torchaudio/datasets/vctk.py
Remove walk_files from VCTK dataset
Fixes:
#1051
#1069
=> VCTK Using Path and glob instead of walk_files 

torchaudio/datasets/cmuarctic.py, torchaudio/datasets/commonvoice.py, torchaudio/datasets/ljspeech.py, torchaudio/datasets/utils.py, torchaudio/sox_effects/sox_effects.py
I have also addressed your comments on torch.random https://github.com/pytorch/audio/pull/1022#issuecomment-738500681. 
Fixes #1081
=> Remove redundant dataset utilities 

test/torchaudio_unittest/README.md
Docs seem to have an old path to the `sox_effects` tests. PR updates them.
=> Fix `sox_effects` test path in docs

.circleci/config.yml, .circleci/config.yml.in
There's an issue with the CUDA 11.0 package for conda with
conda-package-handling that relates to https://github.com/conda/conda-package-handling/issues/71
This should fix issues with the conda smoke testing we encountered previously.
=> .circleci: Install the CPU package for pytorch

test/torchaudio_unittest/kaldi_compatibility_impl.py
I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue when I was parsing/generating from the TensorFlow—and now PyTorch—codebases: inconsistent use of `Args:` and `Arguments:` in its docstrings. It is easy enough to extend my parsers to support both variants, however it looks like `Arguments:` is wrong anyway, as per:
- https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
- https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
- …
=> [*.py] Rename "Arguments:" to "Args:"

setup.py
This PR makes `python setup.py clean` actually use the custom-defined the clean class.
=> Use custom clean function to clean

test/torchaudio_unittest/datasets/commonvoice_test.py, test/torchaudio_unittest/datasets/yesno_test.py
=> Clean up Dataset test CommonVoice and YesNo

third_party/CMakeLists.txt
In some environment, where audio devices are available, sox's build script pick it up automatically and it causes undefined symbol error. This PR disables them.
=> Explicitly disable audio devices in sox build

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/functional/functional_cuda_test.py, test/torchaudio_unittest/functional/functional_impl.py, torchaudio/functional/functional.py
=> Fix nan gradient by using native complex abs op

torchaudio/csrc/transducer.cpp
Update the data pointers in RNN-T loss to remove deprecation warnings
cc #1137, HawkAaron/warp-transducer#83
=> Update data pointer in RNN-T loss

.circleci/unittest/linux/scripts/install.sh, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/case_utils.py, test/torchaudio_unittest/soundfile_backend/load_test.py, test/torchaudio_unittest/sox_io_backend/load_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/pybind.cpp, torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects.h, torchaudio/csrc/sox/effects_chain.cpp, torchaudio/csrc/sox/effects_chain.h, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h, torchaudio/sox_effects/sox_effects.py
=> Support in-memory decoding in load function

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/librosa_compatibility_test.py
=> Replace pytest's paremeterization with parameterized 

test/torchaudio_unittest/README.md
I couldn't find docs to install the package elsewhere (maybe I missed something?)
Also, it might be worth pointing to the testing READMEs directly from the root README, e.g. within the contributing guidelines. It took me a bit to find it ;). Happy to do that in this PR if needed.
=> DOC Add instruction to install parametrized package

.circleci/unittest/linux/scripts/run_test.sh
Test for file-like object support is causing segmentation fault.
This is impacting PRs so disable it temporarily.
=> Temporarily disable fileobj

build_tools/setup_helpers/extension.py, setup.py, third_party/CMakeLists.txt, third_party/transducer/CMakeLists.txt, torchaudio/csrc/sox/register.cpp, torchaudio/csrc/transducer.cpp
This PR cleans up build process by
* Decoupling the registration of sox and transducer, using `TORCH_LIBRARY_FRAGMENT` macro.
* Instead of linking `libwarprnnt.a` from the build directory use the install directory, where other libsox related libraries are found.
When `BUILD_TRANSDUCER` is false-y value
* Do not build the external transducer
* Do not build the transducer binding (exclude it from the list of sources)
---
Remaining tweak for build (not in this PR)
* move the sox-related stuff to the dedicated directory under `third_directory` #1161 
* CXX11 ABI
* Hide symbols
* Add switch to exclude prototype from package
=> Clean up transducer build

.flake8, tox.ini
=> Merge flake8 configurations

docs/source/index.rst, docs/source/transducer.rst
Add prototype RNN transducer loss to the documentation. This will need to be guarded off from releases.
cc #1137
=> Add documentation for RNN transducer

.circleci/config.yml, .circleci/config.yml.in
Follow up of #1161. CircleCI cache directory was not updated and this is causing nightly to fail.
=> Fix third party download cache config

.circleci/unittest/linux/scripts/run_test.sh
This reverts commit 84966ae132f8c04ede2a9365324388f3948a1841.
The segfault issue which was surely happening on the Friday is now gone. I suspect that it was caused by some specific environment. To get the signal, re-enabling the test again.
=> Revert "Temporarily disable fileobj tests (#1168)"

build_tools/setup_helpers/extension.py
With this change, `BUILD_TRANSDUCER=1 python setup.py build_ext` now sees `-D_GLIBCXX_USE_CXX11_ABI=` in the compilation command. (Note: sox is C-only so it is not relevant to sox build process)
```
[ 98%] Building CXX object transducer/CMakeFiles/warprnnt.dir/submodule/src/rnnt_entrypoint.cpp.o
cd /scratch/moto/torchaudio/build/temp.linux-x86_64-3.8/third_party/transducer && /home/moto/ccache/lib/c++  -DRNNT_DISABLE_OMP -I/scratch/moto/torchaudio/third_party/transducer/submodule/include  -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC   -o CMakeFiles/warprnnt.dir/submodule/src/rnnt_entrypoint.cpp.o -c /scratch/moto/torchaudio/third_party/transducer/submodule/src/rnnt_entrypoint.cpp
```
See also: https://github.com/pytorch/text/pull/931
=> [Build] Set proper C++ ABI

.circleci/config.yml, .circleci/config.yml.in, test/torchaudio_unittest/soundfile_backend/save_test.py, test/torchaudio_unittest/sox_io_backend/save_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/pybind.cpp, torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects_chain.cpp, torchaudio/csrc/sox/effects_chain.h, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
This adds file object support to `save` function.
Also this PR disables TP binary cache, as it seems to cause an occasional build error.
See #1115
=> Support file-like object in save func

torchaudio/compliance/kaldi.py
This is the implementation for https://github.com/pytorch/audio/issues/1057
Implementation is taken from [julius/resample.py](https://github.com/adefossez/julius/blob/main/julius/resample.py) and adapted for consistency with the previous implementation. See the issues linked above for a comparison in speed.
Output should be exactly the same as I changed the default parameters to match those of the previous implementation.
=> Simpler and faster resampling

torchaudio/datasets/yesno.py
Implementation for the `YesNo` dataset. 
cc: @mthrok 
Fixes: #910 
The initial plan is to refactor the datasets (first part of the PR). Based on the complexity will create subsequent PRs.
=> [Refactor][Dataset] YesNo implementation

packaging/pkg_helpers.bash
torchaudio can work with any version of pytorch so let's strip the
pytorch version suffix to denote that
=> packaging: Always strip version suffix for pytorch

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/librosa_compatibility_test.py
This PR replaces the use of pytest with unittest.
Follow up from https://github.com/pytorch/audio/pull/1177/files#r560532884
=> Remove pytest imports in test code

setup.py
This PR removes alleged support to Python 2.7 in `setup.py`.
Closes  #477
=> Update setup.py to remove 2.7 ref

.circleci/config.yml, .circleci/config.yml.in, .circleci/unittest/linux/docker/build_and_push.sh
Changing the test Docker image for GPU tests to use Nvidia Docker `devel` image. This is necessary for #1187.
=> Update GPU test image to development

third_party/sox/CMakeLists.txt
This PR 
1. redirects build logs for sox and its dependencies to file so that build log becomes simpler.
2. Tweak `third_party/sox/CMakeLists.txt` for improved readability.
=> Clean up sox/CMakeLists and build log

test/torchaudio_unittest/soundfile_backend/common.py, test/torchaudio_unittest/soundfile_backend/info_test.py, test/torchaudio_unittest/sox_io_backend/info_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/register.cpp
Closes https://github.com/pytorch/audio/issues/1173
This PR adds a `bits_per_sample` attribute to `AudioMetaData` as returned by `info()`, with support for both `sox_io` and `SoundFile`. As SoundFile does not expose the bit depth directly, it is inferred from the `subtype` field as suggested in https://github.com/pytorch/audio/issues/1173.
`bits_per_sample` is left to 0 for lossy formats or when it cannot be inferred.
CC @mthrok
=> Add bits_per_sample to info

.circleci/unittest/linux/scripts/run-clang-format.py, .circleci/unittest/linux/scripts/run_style_checks.sh, torchaudio/csrc/pybind.cpp, torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects_chain.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/legacy.cpp, torchaudio/csrc/sox/legacy.h, torchaudio/csrc/sox/register.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h, torchaudio/csrc/transducer.cpp
clang-format job was checking if there is a difference after `clang-format` command  was used. This overlooked the case where the `clang-format` command was not found. This PR fixes it and fix C++ lint issue.
See example of failure case.
https://app.circleci.com/pipelines/github/pytorch/audio/4686/workflows/487fc3d8-037a-4662-b251-2f6ae4292d13/jobs/150112
=> Fix clang-format

test/torchaudio_unittest/soundfile_backend/info_test.py, test/torchaudio_unittest/sox_io_backend/info_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/pybind.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/register.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
This PR adds support for file-like object to `info` function of `sox_io` backend and `soundfile` backends.
See also #1115
=> Support file-like object in info

test/torchaudio_unittest/sox_io_backend/load_test.py, torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects_chain.cpp, torchaudio/csrc/sox/utils.cpp
In #1158 file-like object support was added to `load` function.
The code works an object that implements `read` protocol `read(size: int) -> bytes`.
The implementation expected that the `read` method will always returns the `bytes` with the exact requested length, but that should not be required.
This PR relax it with couple of tweaks.
1. Introduce `read_fileobj` helper function that calls `read` and retry until the requested length is fetched / EOF is reached.
1. Mark explicitly the end of file object read, and will not call the method again once it reaches the EOF.
1. Tweak the behavior around file opening (reading header and initializing decoder) so that buffer size can be changed, and  it works fine on tiny audio data.
=> Fix load from file object for small files and shorter bytes

test/torchaudio_unittest/sox_io_backend/save_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
=> Add target `dtype` argument to `save` function for sox backend

test/torchaudio_unittest/soundfile_backend/info_test.py, test/torchaudio_unittest/sox_io_backend/info_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/register.cpp
This PR adds `encoding` attribute to the `AudioMetaData` class and make `info` function returns `encoding` as well.
In the legacy backend implementations, this information was available in sox backend, but in new backends, we do not expose the native structure of libsox directly, so we use `str` class to represent the encoding. See #1184 for the specification.
Resolves #1184
=> Add encoding attribte to info

test/torchaudio_unittest/sox_io_backend/smoke_test.py
Add smoke test for file object support in "sox_io" backend.
See also #1115
=> Add smoke test for sox_io fileobj

test/torchaudio_unittest/sox_effect/smoke_test.py, test/torchaudio_unittest/sox_effect/sox_effect_test.py, torchaudio/csrc/pybind.cpp, torchaudio/sox_effects/sox_effects.py
The underlying implementation is same as `load` function. (both use `apply_effects_fileobj`) So this is just registering the C++ implementations, modifying frontend and adding test.
See also #1115
=> Support file-like object in apply_effects_file

torchaudio/transforms.py
This PR updated `SpectralCentroid` transform to accept `window_fn` and `wkargs` instead of `window`, for consistency with the other transforms.
CC @mthrok
=> Update SpectralCentroid to accept window_fn and wkwargs

torchaudio/csrc/sox/effects_chain.cpp
[`sox_format_t.tell_off`](https://fossies.org/dox/sox-14.4.2/structsox__format__t.html#a2016a9fa839f3139e3c2f64381b0c445) should be representing current offset in file, but there are cases it does not. This was causing segmentation fault in some cases. This PR fixes it by replacing it with `ftell` call and add extra check so that if the same thing should happen, it will throw runtime error instead of segmentation fault.
See also: [internal test log](https://www.internalfb.com/intern/testinfra/diagnostics/1125900086940494.281474997971466.1611950392/)
=> Fix segfault by calling ftell in place of tell_off

torchaudio/csrc/sox/effects_chain.cpp
Fixes https://github.com/pytorch/audio/issues/1223.
```
>>> import torchaudio
################################################################################
################################################################################
>>> effects = [['gain', '-n'], ['pitch', '1'], ['rate', '16000'], ['foo', '1']]
>>> waveform, sample_rate = torchaudio.load('knu1.mp3')
>>> waveform2, sample_rate2 = torchaudio.sox_effects.apply_effects_tensor(waveform, sample_rate, effects, channels_first=True)
File "<stdin>", line 1, in <module>
File "/Users/prabhatroy/Documents/pytorch/audio/torchaudio/sox_effects/sox_effects.py", line 153, in apply_effects_tensor
tensor, sample_rate, effects, channels_first)
RuntimeError: Unsupported effect: foo
>>> 
```
=> Fixed seg fault caused by passing random effect to apply_effects_tensor

.circleci/unittest/linux/scripts/run_test.sh
So that when a test fails in flaky manner, we can look into the difference.
=> Print CPU info before running unit test

torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
`sox_encodinginfo_t` is the structure used to communicate the encoding with `libsox`.
This structure is constructed/used in the following scenarios;
1. Pass Tensor object to `libsox` buffer.
2. Construct Tensor object from `libsox` buffer.
3. Save Tensor object to file or file-like object.
Originally, all the three cases used the same logic `get_encodinginfo(format string, Tensor dtype) -> sox_encodinginfo_t` but as I work on #1226 , I figured that it is better to use different logics for 1&2 and 3.
This PR makes the distinguish clearer.
For 1&2, the helper function is renamed to `get_tensor_encodinginfo` and it only takes `Tensor dtype` as argument (because Tensor is always raw, uncompressed format like WAV).
For 3, I renamed the function to `get_encodinginfo_for_save`. This function …
=> Refactor `get_encodinginfo` logic

torchaudio/csrc/sox/effects_chain.cpp
Fix the warning of mixed integer type. See also https://github.com/pytorch/audio/issues/1229#issuecomment-772652248
```
/scratch/moto/torchaudio/torchaudio/csrc/sox/effects_chain.cpp: In function ‘int torchaudio::sox_effects_chain::{anonymous}::fileobj_input_drain(sox_effect_t*, sox_sample_t*, size_t*)’:
/scratch/moto/torchaudio/torchaudio/csrc/sox/effects_chain.cpp:357:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (num_consumed > priv->buffer_size) {
~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/scratch/moto/torchaudio/torchaudio/csrc/sox/effects_chain.cpp:369:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
if (num_refill < num_consumed) {
~~~~~~~~~~~^~~~~~~~~~~~~~
```
=> Fix mixed signed/un-signed types in comparison

CMakeLists.txt, torchaudio/csrc/CMakeLists.txt
- Fix option name `BUILD_TORCHAUDIO_PYTHON_EXTENSION`
- Fixes for libtorchaudio
=> Small fixes for CMakeLists

torchaudio/datasets/speechcommands.py
In the test set of SpeechCommands v2 [1], some files have the form
"xxx.wav.wav".
[1] https://storage.googleapis.com/download.tensorflow.org/data/speech_commands_test_set_v0.02.tar.gz
=> SpeechCommands: fix for the test set

docs/Makefile, docs/source/backend.rst, docs/source/conf.py, torchaudio/_internal/module_utils.py, torchaudio/backend/common.py, torchaudio/backend/sox_io_backend.py, torchaudio/sox_effects/sox_effects.py
Similar to what was done in `torchvision` https://github.com/pytorch/vision/pull/3290
This PR fixes sphinx warnings and sets the 
```py
napoleon_numpy_docstring = False
napoleon_google_docstring = True
```
for sphinx to issue warnings when the wrong parameter syntax is used.
The warnings are now turned into errors. Note: sphinx will now stop compilation at the first warning/error it sees; if we relied on sphinx>=8, we could use the `--keep-going` option to let it finish.
=> DOC Fix sphinx warnings and turn warnings into errors

test/torchaudio_unittest/backend/sox_io/common.py, test/torchaudio_unittest/backend/sox_io/roundtrip_test.py, test/torchaudio_unittest/backend/sox_io/save_test.py, test/torchaudio_unittest/backend/sox_io/torchscript_test.py, test/torchaudio_unittest/common_utils/sox_utils.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/sox/effects_chain.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
The current release version's "sox_io" backend's `save` function changes the encoding of the audio file based on the dtype of the Tensor. For example, if the dtype is "float32", then it will be saved as 32bit floating point PCM. This behavior was taken from [SciPy's `scipy.io.wavefile.write` function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html#scipy-io-wavfile-write). However it was pointed out that this is inconvenient for torchaudio users. Because most torchaudio's functionality works on float32 Tensor yet, the common audio formats typically retains only 16 bit, such as 16 bit signed integer PCM.
To resolve the inconvenience while keeping the functionality to support different encodings, this PR 
1. Add `encoding` and `bits_per_sample` parameters to …
=> Add encoding and bits_per_sample option to save function

test/torchaudio_unittest/librosa_compatibility_test.py
Resolves #1262 
I've gone off piste from the steps laid out in the issue. Rather than splitting things out as a test and using parameterize, I decided to maintain more control by using unittest.subTest. I wanted to be able to generate lots of different variants, restrict them down to the relevant parameters for each component, and then remove any resultant duplicates (so as to cut down the test time), as well as maintaining the test skip on TravisCI. Trying to do all this in a decorator for parameterize was messy, so hopefully this approach is better. I'm concerned that it might just be over engineered for what you need though, and more difficult to understand than the dumb approach. Let me know what you think, I can drop back to doing the recommended way if you would like.
The change was …
=> Improve MelSpectrogram librosa compatibility test

docs/source/_templates/layout.html
Together with #1272 this will allow selecting between versions of the documentation. Once this is merged and a nightly build pushes docs to master, the version selection will appear on the master docs.
@brianjo
=> Make the version a link to /versions.html

test/torchaudio_unittest/backend/sox_io/save_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h, torchaudio/csrc/sox/utils.cpp
Addresses https://github.com/pytorch/audio/issues/1264.
=> Added GSM format support to soxio's save function

torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects.h, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
After https://github.com/pytorch/pytorch/commit/a9f5e7229e92259bc44eb9898c04eaf200c7f81f was merged into upstream pytorch the passing of
references within torch c extension functions is no longer allowed. This
just removes the reference and passes by value instead.
=> torchaudio: Fix c extension compilation

test/torchaudio_unittest/backend/sox_io/info_test.py, test/torchaudio_unittest/backend/sox_io/save_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h, torchaudio/csrc/sox/utils.cpp
With [advice & help](https://github.com/pytorch/audio/pull/1271#issuecomment-780040899) from @mthrok, added `htk` format to sox_io's save function & info test.
htk is a single channel 16-bit PCM format used by HTK, a toolkit for building Hidden Markov Model speech processing tools.
=> Add HTK format support to sox_io's save & info

.circleci/config.yml, .circleci/config.yml.in, .circleci/regenerate.py, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/setup_env.sh, .circleci/unittest/windows/scripts/environment.yml, .circleci/unittest/windows/scripts/install.sh, .circleci/unittest/windows/scripts/setup_env.sh, packaging/pkg_helpers.bash, packaging/torchaudio/meta.yaml, setup.py
(cherry picked from commit 1b7ee833f5b43337dfc27763aa2bd1fb93f8a34c)
=> Add Python 3.9 support

test/torchaudio_unittest/common_utils/sox_utils.py
`--bits` is being provided twice by mistake & sox is unable to handle it well & produces a warning.
For example,
```
sox -V3 --no-dither -R --bits 16 --rate 8000 --null --channels 1 --bits 16 --encoding gsm /tmp/tmp08b_xoao/torchaudio_unittest.backend.sox_io.info_test.TestInfo.test_gsm/data.gsm synth 1 sawtooth 1
sox:      SoX v14.4.2
Input File     : '' (null)
Channels       : 1
Sample Rate    : 8000
Precision      : 16-bit
Endian Type    : little
Reverse Nibbles: no
Reverse Bits   : no
sox WARN formats: gsm can't encode GSM to 16-bit
```
=> Remove duplicate --bits parameter while invoking sox

test/torchaudio_unittest/common_utils/sox_utils.py
This reverts commit 93950302cbcad5c94386f0e77c58c4ca77f0a0af as per [comment](https://github.com/pytorch/audio/pull/1287#issuecomment-782348049). All tests pass with or without.
=> Revert "Remove duplicate --bits command line parameter (#1287)"

test/torchaudio_unittest/backend/sox_io/info_test.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h
With @mthrok's help, the following tasks were completed in this PR:
1. Added info test for GSM.
2. Moved the function `get_encoding` from `torchaudio/csrc/sox/io.cpp` to `torchaudio/csrc/sox/types.cpp`.
=> Add GSM encoding support to info

CONTRIBUTING.md
Seems like there's a typo in `CONTRIBUTING.md` - tests depend on `parameterized`, not `parametrized`
=> Fix test dependency typo

torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/effects.h, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/io.h
This PR cherry-picks a0446251ef7c2806fe36c601631fcae54667318d on top of master, by taking into account the changes from #1285
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/51319
We were going out of our way to accommodate `IValue::to<Tensor>` returning a copy of the inner Tensor. `IValue::toTensor` is capable of returning a reference without copying, so if we use it directly, we can allow kernels that want to take `Tensor &` to do so!
As a bonus, we get reduced build times.
ghstack-source-id: 121378961
Reviewed By: bhosmer
Differential Revision: D26138549
fbshipit-source-id: b0f830527da360c542c815bef2f7e1692615b32a
=> Remove reference_cast in make_boxed_from_unboxed_functor (pytorch/pytorch#51319)

test/torchaudio_unittest/backend/soundfile/common.py, test/torchaudio_unittest/backend/soundfile/save_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/sox_io_backend.py
Addresses https://github.com/pytorch/audio/issues/1258.
=> Added encoding and bits_per_sample to soundfile's backend save()

third_party/sox/CMakeLists.txt, third_party/sox/patch/sox.patch
Ever since the file-like object support was added in #1158, the test
was occasionally failing in CI. This PR fixes this.
The failing tests exhibit flakiness in the following three areas;
1. `info_test`
For `mp3` and `vorbis` formats, the number of reported frames were most times zero (this is due to the container format), but occasionally, the test reported a correct number. It should be always reporting the same number.
2. `load_test`
The shape of the Tensor loaded with `load` function occasionally had different number of frames than what actually the file has.
3. `save_test`
The saved data occasionally lacked some frames at the end.
unix system, all Python environment
When opening file (for both read and write), `libsox` initializes the dedicated data structure called `sox_format_t`, …
=> Fix fileobj I/O un-deterministic behavior

test/torchaudio_unittest/backend/soundfile/common.py, test/torchaudio_unittest/backend/soundfile/save_test.py, torchaudio/backend/_soundfile_backend.py, torchaudio/backend/sox_io_backend.py
(cherry picked from commit b8fd5e9458e2bf2c9ad158df2d03b1db640c0f7b)
=> Added encoding and bits_per_sample to soundfile's backend save() (#1274)

test/torchaudio_unittest/backend/sox_io/save_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/types.cpp, torchaudio/csrc/sox/types.h, torchaudio/csrc/sox/utils.cpp
(cherry picked from commit 490a53e5601bd71dfddbb3789958f5a18a08f475)
=> Add GSM format support to sox_io's save function (#1275)

0.7.0/backend.html, 0.7.0/compliance.kaldi.html, 0.7.0/datasets.html, 0.7.0/functional.html, 0.7.0/genindex.html, 0.7.0/index.html, 0.7.0/kaldi_io.html, 0.7.0/models.html, 0.7.0/py-modindex.html, 0.7.0/search.html, 0.7.0/sox_effects.html, 0.7.0/torchaudio.html, 0.7.0/transforms.html, 0.7.0/utils.html
Swap the static text "0.7.0" version for a link to the versions.html page
@brianjo
=> change 0.7.0 documentation to use a version selector

torchaudio/csrc/sox/utils.cpp
When compiling torchaudio with `-Werror,-Wuninitialized`, we would get compilation errors due to `dummy` not being initialized as follows.
```
pytorch/audio/torchaudio/csrc/sox/utils.cpp:179:53: error: variable 'dummy' is uninitialized when used here [-Werror,-Wuninitialized]
ptr[i] = SOX_SAMPLE_TO_FLOAT_32BIT(buffer[i], dummy);
```
This PR fixes it by initializing it to zero.
=> Fix uninitialised variable in sox/utils.cpp

third_party/sox/CMakeLists.txt, third_party/sox/patch/sox.patch
Cherry picked the commit ef55f39 from #1297
=> Fix fileobj I/O un-deterministic behavior (#1297)

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/setup_env.sh
Numpy is a dependency of pytorch so we should let it get resolved as it
install pytorch
=> .circleci: Let numpy get installed as dependency

torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/overdrive.cpp, torchaudio/functional/filtering.py
New PR for overdrive C++ extension similar to lfilter . Relates to #580 ( old PR )
=> Overdrive cpp extension

torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
Some audio formats like `gsm` does not have valid frame numbers when opened. But `libsox` can properly handle these audios, so checking if `length > 0` is not necessary and too strict.
=> Removed check_length from validate_input_file()

torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
Some audio formats like `gsm` does not have valid frame numbers when opened. But `libsox` can properly handle these audios, so checking if `length > 0` is not necessary and too strict.
(cherry picked from commit 086467a17259dad2dd23ff5707b43e0dceb713ff)
=> Removed check_length from validate_input_file() (#1312)

docs/source/functional.rst, docs/source/transforms.rst, torchaudio/functional/functional.py
Closes #1314. This will need to be cherry-picked in 0.8, #1317.
=> Add missing functionals and transform to docs.

.circleci/config.yml, .circleci/config.yml.in
Addresses https://github.com/pytorch/audio/pull/1316#issuecomment-786345978
Docs are currently built but the artifacts aren't published so they generated html files aren't accessible. This PR fixes that.
=> Publish artifacts on build_docs CircleCI job to get rendered html files

torchaudio/backend/common.py
Question: I think the docstring is leaking Sphinx tags. Should we remove them?
=> Update AudioMetaData docstring with encoding values

test/torchaudio_unittest/common_utils/data_utils.py, test/torchaudio_unittest/functional/batch_consistency_test.py
The `batch_consistency_test.py` files check that behavior is consistent on batches vs. items, but the current infrastructure does this with batches of identical items. This approach may miss bugs related to data leakage between items within a batch, for example #994.
This PR makes changes `functional/batch_consistency_test.py` so (most) batches are generated with items that are not identical, then the entire batch is passed to the consistency check. Batch sizes are parameterized so tests are generated for single-item and three-item batches. I've also changed the white noise generator to generate different data in each channel (rather than duplicating one wave), and the consistency check now checks both inputs and outputs, to detect inconsistencies with in-place operations.
I am still …
=> Apply functional batch consistency tests to batches of different items

docs/source/functional.rst
Adds subcategory to functional documentation, file `filtering` so that it's easier to see the separation in utilities and feature extractions.
=> Add subcategories to functional documentation

torchaudio/backend/common.py
Makes `AudioMetaData` print-friendly.
Closes #1323
=> Add AudioMetaData.__str__ override

test/torchaudio_unittest/backend/sox_io/info_test.py, test/torchaudio_unittest/backend/sox_io/load_test.py, test/torchaudio_unittest/backend/sox_io/roundtrip_test.py, test/torchaudio_unittest/backend/sox_io/save_test.py, test/torchaudio_unittest/backend/sox_io/smoke_test.py, test/torchaudio_unittest/backend/sox_io/torchscript_test.py, test/torchaudio_unittest/backend/utils_test.py, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/case_utils.py, test/torchaudio_unittest/datasets/tedlium_test.py, test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/sox_effect/dataset_test.py, test/torchaudio_unittest/sox_effect/smoke_test.py, test/torchaudio_unittest/sox_effect/sox_effect_test.py, test/torchaudio_unittest/sox_effect/torchscript_test.py, test/torchaudio_unittest/utils/sox_utils_test.py, third_party/CMakeLists.txt, torchaudio/_internal/module_utils.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/pybind.cpp, torchaudio/csrc/sox/utils.h, torchaudio/csrc/utils.cpp, torchaudio/functional/functional.py, torchaudio/sox_effects/__init__.py, torchaudio/sox_effects/sox_effects.py, torchaudio/utils/__init__.py, torchaudio/utils/sox_utils.py
support functionality to exclude libsox from C++ extension, so that we can eventually support C++ extension on Windows
- change behavior of `BUILD_SOX=0` to exclude libsox from being built + bound, different from the current implementation (dynamic build if =0)
- construct functions to detect whether or not libsox is built, to appropriately handle functions and unittests requiring sox. previously, this was tested using detection of C++ extension since libsox and extension were always built together, but this will no longer be the case
testing: `pytest torchaudio_unittest` for both `BUILDSOX=0` and `BUILDSOX=1` cases
=> Make sox selective

test/torchaudio_unittest/functional/librosa_compatibility_test.py, test/torchaudio_unittest/librosa_compatibility_test.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Add `mel_scale` option enabling the htk or slaney mel scale, see [here](https://github.com/pytorch/audio/pull/426#discussion_r375998053) for discussion and [librosa](https://librosa.github.io/librosa/_modules/librosa/core/time_frequency.html#mel_frequencies).
Relates #589, [internal](https://www.internalfb.com/intern/diff/D20895257/), (#608?), (#259 for mel-hz functional)
=> enable mel_scale option

build_tools/setup_helpers/extension.py, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/case_utils.py, test/torchaudio_unittest/functional/batch_consistency_test.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, torchaudio/_internal/module_utils.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/utils.cpp, torchaudio/functional/functional.py
support functionality to compile without kaldi, similar to #1338
=> make kaldi selective

test/torchaudio_unittest/functional/sox_compatibility_test.py, test/torchaudio_unittest/transforms/sox_compatibility_test.py
=> Refactor sox compatibility test

test/torchaudio_unittest/functional/librosa_compatibility_test.py
Closes #1346 
I've parameterized the `test_create_fb` test, as mentioned in #1346:
> We'd like to use parameterized for the functional librosa compatibility test [here](https://github.com/pytorch/audio/blob/master/test/torchaudio_unittest/functional/librosa_compatibility_test.py#L77). This will make it easier to know which option is failing.
> 
> cc [comment](https://github.com/pytorch/audio/pull/593/files#r585724895)
=> Parameterize librosa compatibility test

test/torchaudio_unittest/functional/batch_consistency_test.py
This PR adds a number of miscellaneous changes to `functional/batch_consistency_test.py` . They are as follows:
- Parameterize `test_sliding_window_cmn` so separate tests are generated  (also extract the test naming function).
- `F.sliding_window_cmn` should take a spectrogram, so replace the wave with a spectrogram. (Related to this, `F.sliding_window_cmn` currently refers to its spectrogram parameter as  [`waveform`](https://github.com/pytorch/audio/blob/master/torchaudio/functional/functional.py#L888). Would you like me to change it to `spec`?)
- Set the manual seed in a couple of places it was missing.
- Tweak the VAD consistency tests by using longer samples for the random test, and using lower thresholds for the file test. **This now causes many of the VAD tests to fail.**
This has …
=> Use parametrize and set random seed in functional batch consistency test 

test/torchaudio_unittest/functional/functional_impl.py
Add unit tests to verify the shape of output tensors for `lfilter` for variety of input Tensor shapes.
=> adding test for lfilter shape

docs/source/backend.rst, docs/source/torchaudio.rst, test/torchaudio_unittest/backend/utils_test.py, test/torchaudio_unittest/compliance/generate_fbank_data.py, test/torchaudio_unittest/compliance_kaldi_test.py, torchaudio/backend/no_backend.py, torchaudio/backend/soundfile_backend.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py
Testing Steps:
Run entire test suite. 
I am getting one failure locally, but it doesn't look related to these changes. 
Seems to have to do with imprecision of floating point arithemetic. Let me know if you want me to relax the threshold slightly -- it may be that the tests do not fail on CI build. (edit: I actually don't see the tests running on checks). 
Let me know what you think. Thanks!
=> Remove deprecated load_wav functions from backends

CONTRIBUTING.md, README.md
remove `BUILD_SOX=0` segment from CONTRIBUTING.md following #1338, which changes the behavior of `BUILD_SOX=0`
=> remove instructions for building sox from source

test/torchaudio_unittest/functional/batch_consistency_test.py, test/torchaudio_unittest/functional/librosa_compatibility_test.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
=> BC-Breaking: Remove deprecated `normalized` argument from griffinlim

torchaudio/csrc/sox/effects_chain.cpp
`SOX_SIGNED_16BIT_TO_SAMPLE` and `SOX_SIGNED_32BIT_TO_SAMPLE` uses left shift on signed integers, which is UB.
This PR replaces them (and other sox macros for `uint8` and `float` as well) with Tensor operations.
=> Replace sox conversion macros with Tensor op

test/torchaudio_unittest/backend/soundfile/info_test.py, test/torchaudio_unittest/backend/soundfile/save_test.py, test/torchaudio_unittest/backend/sox_io/save_test.py, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/parameterized_utils.py
Modify unittest name generation to remove tuples syntax (parentheses) from test names
Example:  `<TestCaseFunction test_sphere_16000_1_('PCM_24', 24)>` --> `<TestCaseFunction test_sphere_16000_1_PCM_24_24>`
=> Fix invalid test names generation

torchaudio/functional/functional.py
`F.sliding_window_cmn` appears to take a spectrogram as input, of shape `(..., freq, time)`. However, the name of the argument is `waveform`. I discussed this briefly with @mthrok [here](https://github.com/pytorch/audio/pull/1341#issuecomment-789406548) and [here](https://github.com/pytorch/audio/pull/1315#issuecomment-787478374). This PR changes the name of this argument to `specgram`. Since this is a BC-breaking change, I've opened a separate pull request. 
The output tensor also appears to be a spectrogram of the same shape as the input, so I've renamed that too, and updated the specification in the docstring.
=> BC-Breaking: Rename `waveform` tensor in `F.sliding_window_cmn`

test/torchaudio_unittest/functional/torchscript_consistency_impl.py
Add TorchScript test for `F.phase_vocoder`
Test plan
1. Go to test folder `cd test`
2. Run `pytest torchaudio_unittest/functional/torchscript_consistency_cpu_test.py -k phase_vocoder`
=> Add TorchScript test for `F.phase_vocoder`

torchaudio/functional/functional.py
Changed docstring for the input specgram from (..., freq, time) to (..., time, freq) as highlighted in issue #1380.
=> Fixed docstring of `sliding_window_cmn` to fix #1380

CONTRIBUTING.md
Closes https://github.com/pytorch/audio/pull/343
This PR updates the contributing guide to include bounty and CLA info
=> Updated contributing guide

test/torchaudio_unittest/compliance_kaldi_test.py
https://github.com/pytorch/audio/issues/680
=> Replace torch.assert_allclose with assertEqual from pytorch

test/torchaudio_unittest/functional/functional_cpu_test.py
remove use of `name_func` from `functional_cpu_test.py` to unblock torchaudio import
=> Fix functional_cpu_test test name generation

torchaudio/csrc/transducer.cpp, torchaudio/prototype/transducer.py
Move input checks for RNNT from Python to C++
RNN Transducer Loss Issue: #1240
=> Migrate transducer input checks to C++

test/torchaudio_unittest/backend/sox_io/load_test.py, torchaudio/backend/sox_io_backend.py, torchaudio/csrc/sox/utils.cpp
Cherry-pick #1389 for dot release 0.8.1
cc @seemethere
=> [0.8.1] Add support for 24-bit signed LPCM wav in sox_io backend (#1389)

torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
Removed unused helper function "get_dtype_from_str". 
To test, ran  `pytest torchaudio_unittest` after running `BUILD_SOX=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py develop`.  I saw no changes in # of failures before and after the change. 
`=================================== 1285 failed, 1193 passed, 2754 skipped, 1 xfailed, 22 warnings in 336.89s (0:05:36) ====================================`
=> Remove unused helper function

torchaudio/datasets/yesno.py
The length of the checksum for the YESNO dataset is inconsistent with the specified algorithm (MD5) and its value does not correspond to the other supported algorithm (sha256).
This PR updates the hash to the correct sha256 value.
=> Fix checksum for the YESNO dataset

.clang-tidy
This change is same as PR #1401. This is created as the reference PR is unable to be merged in master
=> Fix .clang-tidy

.gitignore, CMakeLists.txt, build_tools/setup_helpers/extension.py, cmake/LoadHIP.cmake, test/torchaudio_unittest/backend/soundfile/save_test.py, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/case_utils.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
This PR adds support for building pytorch audio in ROCM. We currently disable 5 tests. There is still more work to be done but with the changes in this PR, we can build and test pytorch audio on ROCM.
=> [ROCM] add rocm support

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/functional/functional_cuda_test.py, test/torchaudio_unittest/functional/functional_impl.py, test/torchaudio_unittest/functional/librosa_compatibility_test.py, test/torchaudio_unittest/functional/torchscript_consistency_cpu_test.py, test/torchaudio_unittest/functional/torchscript_consistency_cuda_test.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/batch_consistency_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_cpu_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_cuda_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
This PR supersedes #758 and includes further updates.
See #1337 for the overview.
1. `F.phase_vocoder` accepts Tensor with complex dtype.
* The implementation path has been updated from #758 so that they share the same code path by internally converting the input Tensor to complex dtype and performing all the operation on top of it.
* Adopted `torch.polar` for simpler Tensor generation from magnitude and angle.
2. Updated tests
* librosa compatibility test for complex dtype and pseudo complex dtype
* Extracted the output shape check test and moved it to functional so that it will be tested on all the combination of `{CPU | CUDA} x {complex64 | complex128}`
* TorchScript compatibility test for `F.phase_vocoder` and `T.TimeStretch`.
* batch consistency test for `T.TimeStretch`. …
=> Make `F.phase_vocoder` and `T.TimeStretch` handle complex dtype

test/torchaudio_unittest/transforms/autograd_test_impl.py, test/torchaudio_unittest/transforms/librosa_compatibility_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
This PR adds `return_complex` argument to 
- `F.spectrogram`
- `T.Spectrogram`
- ~`T.MelSpectrogram`~
Note: Since `MelSpectrogram` performs scale conversion on real valued power spectrogram (R->R function), `return_complex` is not added to it.
TODO:
Part of #1337 
Previous discussion #1009
=> Add `return_complex` to F.spectrogram and T.Spectrogram

test/torchaudio_unittest/functional/librosa_compatibility_test.py
unit test comparing librosa and torchaudio's numerical results for resampling was not correct -- resampling with a larger range of input data can result in numerical differences of greater than atol=1e-02 in the unit test, which is not enough to claim compatibility
=> Remove an invalid resample comparison unit test

torchaudio/functional/functional.py
Removing the `repeat` function and replacing groups convolution with regular convolution can lower the size of kernel, and is more memory friendly. 
Can also have some performance gain, probably.
=> Refactor implementation of F.compute_deltas

.circleci/regenerate.py
This PR fixes an issue pointed out by [Bandit](https://bandit.readthedocs.io/en/latest/) w.r.t. using `autoescape=False` with a Jinja2 environment to avoid cross-site scripting vulnerabilities.
Bandit output:
```
>> Issue: [B701:jinja2_autoescape_false] Using jinja2 templates with autoescape=False is dangerous and can lead to XSS. Use autoescape=True or use the select_autoescape function to mitigate XSS vulnerabilities.
Severity: High   Confidence: High
Location: ./.circleci/regenerate.py:213
More Info: https://bandit.readthedocs.io/en/latest/plugins/b701_jinja2_autoescape_false.html
```
=> Fixed jinja2 environment autoescape to enable select extensions

torchaudio/datasets/utils.py
This PR fixes an issue pointed out by [Bandit](https://bandit.readthedocs.io/en/latest/) w.r.t. auditing opened URLs for permitted schemes.
Bandit output:
```
>> Issue: [B310:blacklist] Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected.
Severity: Medium   Confidence: High
Location: ./torchaudio/datasets/utils.py:32
More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen
31          req = urllib.request.Request(url, method="HEAD")
32          url_size = int(urllib.request.urlopen(req).info().get("Content-Length", -1))
33          if url_size == start_byte:
```
=> Fixed URLContext response leak

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/functional/functional_cuda_test.py, test/torchaudio_unittest/functional/functional_impl.py
Merges lfilter and spectrogram classes together in the common implementation and modifies the cpu and gpu test definitions accordingly
=> refactors functional test

.circleci/unittest/linux/scripts/run_test.sh
This code was added as a part of investigation of inconsistent behavior
of file-like object support. Now the investigation is done and this code
does not provide much insight yet adds a bunch of lines to the log, so
this PR removes it.
=> Do not print CPU info before running tests

README.md
This PR adds Windows build instructions for the repo. The repo does not compile without using the [MSVC x64 toolset](https://docs.microsoft.com/en-us/cpp/build/how-to-enable-a-64-bit-visual-cpp-toolset-on-the-command-line?view=msvc-160#use-vcvarsallbat-to-set-a-64-bit-hosted-build-architecture). The given instructions in the PR is the same way in which the Windows builds are triggered for PRs in the repo. As the instructions for Windows builds were missing, I figured it would be good to add them in the README.
=> Added Windows build instructions

test/torchaudio_unittest/functional/autograd_impl.py
related to #1441 
Use short input sequences to avoid time out error on ci as `gradcheck` and `gradgradcheck` are very time comsuming.
=> Shortening lfilter autograd tests input size

test/torchaudio_unittest/transforms/autograd_test_impl.py, torchaudio/functional/functional.py
Get rid of pseudo complex type in `F.griffinlim`.
Part of #1337 
`griffinlim` is tested
- ✅ TorchScript on CPU/CUDA for `float32` and `float64`
- ✅ `librosa` consistency on CPU
- ✅ Batch consistency on CPU
**TODO**
<details><summary>script</summary>
```bash
#!/usr/bin/env bash
OMP_NUM_THREADS=1 numactl --membind 0 --cpubind 0 python -m timeit -s """
import torch
import torchaudio;
batch_size = 32
num_channels = 1
num_freq = 201
num_frames = 400
torch.manual_seed(0);
spec = torch.randn(batch_size, num_channels, num_freq, num_frames, dtype=torch.float32, device='cpu');
griffinlim = torchaudio.transforms.GriffinLim()
""" """
griffinlim(spec)
"""
```
</details>
| device |           master (8d2eeb1)           |                This PR                | …
=> Adopt native complex dtype in griffnlim

test/torchaudio_unittest/functional/batch_consistency_test.py
As mentioned in #1348 and #1449, the VAD function trims the input tensor to the first instance of voice activity on any channel or item. Trimming batches this way may be undesirable as the item with earliest activity will dominate, but either way, the batch behaviour does not match the itemwise behaviour.
The functional VAD batch consistency tests currently pass out of coincidence, but they specify incorrect behaviour. This PR removes these tests.
Closes #1449
=> Remove VAD from batch consistency tests

torchaudio/functional/functional.py
=> Add deprecation warnings to functions for complex

test/torchaudio_unittest/transforms/autograd_test_impl.py
=> Add autograd test for T.AmplitudeToDB

test/torchaudio_unittest/functional/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py
This PR adds step to save/load TorchScript object while testing TorchScript compatibility.
Part of #1337
=> Save/load TorchScript object in test

test/torchaudio_unittest/transforms/autograd_test_impl.py
**UPDATE**
Due to the conversion from cartesian coordinate to polar coordinate, `F.phase_vocoder` (and `T.TimeStretch`) is not differentiable everywhere.
---
Part of #1337 
~Looks like `rate=0.7` is not differentiable to second degree.~
~Let's see what are the value ranges of `rate`, that are differentiable to second degree.~
`T.TimeStretch` manipulates spectrogram in polar coordinate.
The angle conversion from Cartesian to Polar (`atan2(Img, Real)`) does not have a 
nice differentiability around `(x=0, y=0)` and `theta = +/- pi`, therefore `T.TimeStrech` is not differentiable there.
**TODO**
-> Yes it does. In fact the adaptation of complex Tensor makes the TimeStretch work with rate in range 0.8 ~ 1.3.
-> Filed the issue for `rate=0.7` pytorch/pytorch#55557
=> Add autograd test to T.TimeStretch (and F.phase_vocoder)

examples/pipeline_wav2letter/README.md
In line [151-160](https://github.com/pytorch/audio/blob/master/examples/pipeline_wav2letter/main.py#L151) and Line [437](https://github.com/pytorch/audio/blob/fb3ef9ba427acd7db3084f988ab55169fab14854/examples/pipeline_wav2letter/main.py#L437) of main.py, the default value of `dataset-root` and `dataset-folder-in-archive` will be None, which prevents `main.py` from knowing where the dataset is actually in the computer and loading it.
Moreover, `n-hidden-channels 2000` has not been defined in `main.py`, so it needs to be removed.
Erro log:
```bash
python main.py \
--reduce-lr-valid \
--dataset-train train-clean-100 train-clean-360 train-other-500 \
--dataset-valid dev-clean \
--batch-size 128 \
--learning-rate .6 \
--momentum .8 \
--weight-decay .00001 \
--clip-grad 0. \
--gamma .99 \ …
```
=> fix: dataset-root and dataset-folder-in-archive flag is empty

torchaudio/transforms.py
Add missing `"Vol"` and `"ComputeDeltas"` transforms to `__all__` in `transforms.py`
=> Add missing transforms to __all__

test/torchaudio_unittest/functional/functional_cpu_test.py, test/torchaudio_unittest/functional/functional_cuda_test.py, test/torchaudio_unittest/functional/functional_impl.py
- Refactor functional test logic into one place, `functional_impl.py`
- Tidy imports
Local test plan:
`cd test && pytest torchaudio_unittest/functional`
=> Refactor functional test

.circleci/config.yml, .circleci/config.yml.in, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/post_process.sh, .circleci/unittest/linux/scripts/run_test.sh, .circleci/unittest/windows/scripts/install.sh, .circleci/unittest/windows/scripts/post_process.sh, .circleci/unittest/windows/scripts/run_test.sh
Circle CI can display coverage report nicely.
Doc: https://circleci.com/docs/2.0/code-coverage/
https://201041-90321822-gh.circle-artifacts.com/0/test/htmlcov/index.html
This way, we can get rid of `codecov`, yet can have coverage report available all the time.
Thoughts? @fmassa @cpuhrsch
=> Remove codecov and store coverage on CCI

docs/source/conf.py
This PR adds GA support to torchaudio. We just rely on the native support from the theme (https://github.com/pytorch/pytorch_sphinx_theme/pull/110)
=> Add Google Analytics support

torchaudio/sox_effects/sox_effects.py
=> Clarify `sox_effects.apply_effects_tensor` as CPU-only in Doc

test/torchaudio_unittest/transforms/autograd_test_impl.py
=> Add autograd test for T.MelScale

examples/pipeline_wav2letter/README.md, examples/pipeline_wav2letter/main.py
This PR reports the %WER reached with the wav2letter pipeline in the README.
- fix zero error rates reported.
- rename output variables for readability.
- update readme with refreshed and more representative output. report word error rate.
=> Add WER to readme in wav2letter pipeline

test/torchaudio_unittest/transforms/autograd_test_impl.py
Autograd tests for Transforms #1414
=>  Adding test for T.SlidingWindowCmn

test/torchaudio_unittest/functional/functional_impl.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, torchaudio/functional/functional.py
As reported in #1478, `TimeMasking` performs in-place operations that modifies the input tensor. This is also the case for `FrequencyMasking`. 
This PR modifies the algorithm to not perform in-place operations on the input tensor and adds checks in the unit test to ensure that the input tensor is not being changed.
(Resolves #1478)
=> Ensure axis masking operations are not in-place

.circleci/config.yml, .circleci/config.yml.in
All macOS CI jobs were failing at `brew`.
The issue was the macOS version `10.13`, which is no longer supported by `brew`.
The macOS version is indirectly controlled by `xcode` version as listed [here](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions).
Updating the `xcode` to `"12.0"` as in PyTorch core bump macOS version to `10.15` and it resolves the issue.
`Python 3.9` is still failing but it's packaging issue on upstream, which needs to be resolved separately.
=> Update xcode version in CI macOS jobs.

torchaudio/functional/functional.py, torchaudio/transforms.py
@anjali411 I noticed that there are missing deprecation warnings. The style of message is same as the other ones in #1445.
=> Add deprecation warnings to magphase and ComplexNorm

CMakeLists.txt, build_tools/setup_helpers/extension.py, test/torchaudio_unittest/rnnt/rnnt_loss_cuda_test.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/rnnt/gpu/compute.cu, torchaudio/csrc/rnnt/gpu/compute_alphas.cu, torchaudio/csrc/rnnt/gpu/compute_betas.cu, torchaudio/csrc/rnnt/gpu/gpu_kernel_utils.cuh, torchaudio/csrc/rnnt/gpu/gpu_kernels.cuh, torchaudio/csrc/rnnt/gpu/gpu_transducer.h, torchaudio/csrc/rnnt/gpu/half.cuh, torchaudio/csrc/rnnt/gpu/kernel_utils.h, torchaudio/csrc/rnnt/gpu/kernels.h, torchaudio/csrc/rnnt/gpu/math.cuh
Summary: In #1479, we added support for CPU RNNT loss. This PR adds a GPU version of RNNT loss
Differential Revision: D28128853
=> Add GPU RNNT Loss

torchaudio/compliance/kaldi.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Expose the `rolloff` parameter in resampling functions, which is can be used to control the degree of anti-aliasing and amount of high frequencies being filtered out in resampling.
cc #1487
=> Add rolloff param to resampling

test/torchaudio_unittest/functional/functional_impl.py, torchaudio/functional/functional.py
Add warning and suggestion when the frequency inputs to the resample function are not integer values
cc #1487
=> Add warning for non-integer resampling frequencies

docs/source/models.rst, test/torchaudio_unittest/models_test.py, torchaudio/models/__init__.py, torchaudio/models/deepspeech.py
- Add Documentation related to module models
- Add documentation to model `DeepSpeech`
- Add Unit-test to `DeepSpeech`
- Add model `DeepSpeech` according to its paper [Deep Speech: Scaling up end-to-end speech recognition](https://arxiv.org/abs/1412.5567)
Relates to https://github.com/pytorch/audio/issues/446
=> Add vanilla DeepSpeech model

test/torchaudio_unittest/transforms/autograd_test_impl.py
Context: #1414
I combined these two transforms in one test because they're actually the same [`_AxisMasking` transform](https://github.com/pytorch/audio/blob/c2740644ee31d29861d3d9977a43af1e71779054/torchaudio/transforms.py#L856), but just on different axis. I even thought of testing the `_AxisMasking` directly, but decided against it because it's not part of the API.
Test fails without the `_DeterministicWrapper` likely due to random behaviour [here](https://github.com/pytorch/audio/blob/c2740644ee31d29861d3d9977a43af1e71779054/torchaudio/functional/functional.py#L792).
=> Add autograd tests for TimeMasking/FrequencyMasking

test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, torchaudio/transforms.py
Added a check in __pre_scriptable__ method for MelScale to make that self.n_stft is not None at the time of scripting.
See https://github.com/pytorch/audio/issues/1454 for details.
=> Melscale torchscript bugfix

torchaudio/functional/functional.py, torchaudio/transforms.py
The kernel used for resampling computations is the same for a given set of resampling parameters, but is currently being recomputed every call to `resample`. To make computation more efficient for `transforms.Resample`, we can precompute the kernel and pass it in to the function instead.
Follow-ups:
- arbitrary source resampling transforms
- [BC-breaking] do not move kernel device and dtype during computation
cc #1487
=> Precompute transforms.Resample kernel

test/torchaudio_unittest/compliance_kaldi_test.py, test/torchaudio_unittest/transforms/transforms_test.py, torchaudio/compliance/kaldi.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Add kaiser window as an option for resampling
Jupyter notebook of some results [kaiser_resampling__1_.pdf](https://github.com/pytorch/audio/files/6497164/kaiser_resampling__1_.pdf)
cc #1487
=> Add kaiser window support to resampling

test/torchaudio_unittest/common_utils/case_utils.py
Since the update of Xcode, some of HTTP tests are failing on macOS, due to `reqests.get` fails to establish a connection to local server. 
Attempted fix
- [did not work]Changing port from 8000 to 20576.
- ✅ Increase start up wait time from 1.0 to 2.0.
=> Make HTTP fetch test more reliable

test/torchaudio_unittest/transforms/transforms_test_impl.py, torchaudio/transforms.py
Issue a warning if `n_stft` is unitialized or zero in construction.
https://github.com/pytorch/audio/issues/1511
=> [#1511] Add deprecation warning to MelScale for unset weight

torchaudio/functional/functional.py, torchaudio/transforms.py
Initially, the kernel used for resampling was computed only after it was fed a waveform, and it would be initialized to be of the same device and dtype as the input waveform that is resampled. In a later change, we cached the resampling kernel in `transforms.Resample`, since kernel computation is significant and redundant when using a given set of resampling parameters. 
To maintain the original behavior would require moving the cached kernel to the device and dtype of the input waveform every time `transforms.Resample` is called, and this could result in unintended side effects; running a CPU transforms on CUDA inputs would have overhead from constantly moving a cached CPU kernel to CUDA, and the expectation is that the user will manually move the transforms themself to the correct …
=> [BC-Breaking] Avoid moving resampling kernel device and dtype moves

test/torchaudio_unittest/rnnt/torchscript_consistency_cpu_test.py, test/torchaudio_unittest/rnnt/torchscript_consistency_cuda_test.py, test/torchaudio_unittest/rnnt/torchscript_consistency_impl.py, test/torchaudio_unittest/rnnt/utils.py, torchaudio/csrc/CMakeLists.txt, torchaudio/csrc/rnnt/autograd.cpp, torchaudio/csrc/rnnt/compute.cpp, torchaudio/csrc/rnnt/compute.h, torchaudio/prototype/rnnt_loss.py
- move RNNT loss autograd function to C++
- add torchscriptability tests
cc #1240
=> Torchscriptable RNNT Loss

test/torchaudio_unittest/functional/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
add torchscriptiibility test for `F.resample`
=> Add F.resample torchscript test

torchaudio/compliance/kaldi.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Improve resampling documentation
cc #1487
=> Improve resampling documentation

test/torchaudio_unittest/transforms/sox_compatibility_test.py, torchaudio/functional/filtering.py, torchaudio/transforms.py
This PR:
* adds warning when input tensor has more than two dimensions
* updates docstring for Vad transform module and function
Reviewer note:
Please check the wording of the warning message
This should bring the conversation in #1348 to a conclusion, while broader design discussions are still happening in #1468
=> Update VAD docstring and check for input shape length

test/torchaudio_unittest/transforms/batch_consistency_test.py
Replace IO function torchaudio.load() usage in test by on-the-fly generated white noise
=> Remove IO function from batch_consistency_test

test/torchaudio_unittest/backend/sox_io/info_test.py, test/torchaudio_unittest/backend/sox_io/load_test.py, test/torchaudio_unittest/backend/sox_io/save_test.py, torchaudio/csrc/sox/effects.cpp, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h
Add file path in error messages of I/O operations #1503
cc @mthrok
=> Add file path to io errors

.circleci/config.yml, .circleci/regenerate.py, packaging/pkg_helpers.bash
This PR adds wheels for rocm. It is based on this PR for pytorch vision(https://github.com/pytorch/vision/pull/3575) that adds rocm wheels . 
It works by creating a rocm version of the binary_linux_wheel build jobs that use pytorch/manylinux-rocm instead of manylinux-cuda102.
=> [ROCm] add rocm wheels

torchaudio/compliance/kaldi.py
Deprecating `torchaudio.compliance.kaldi.resample_waveform`, which is exactly same as `torchaudio.functional.resample`.
=> Deprecate kaldi resample

test/torchaudio_unittest/compliance_kaldi_test.py, test/torchaudio_unittest/functional/functional_impl.py, test/torchaudio_unittest/transforms/transforms_test_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
- return the original waveform when original and new sampling rates are the same for resample
- add unit tests for identity case
- remove a unit test that tests compatibility against kaldi's resample, since it is being deprecated
=> Ensure resampling identity is unchanged

.gitmodules, examples/libtorchaudio/.gitignore, examples/libtorchaudio/CMakeLists.txt, examples/libtorchaudio/README.md, examples/libtorchaudio/build.sh, examples/libtorchaudio/speech_recognition/CMakeLists.txt, examples/libtorchaudio/speech_recognition/README.md, examples/libtorchaudio/speech_recognition/build_pipeline_from_fairseq.py, examples/libtorchaudio/speech_recognition/build_pipeline_from_huggingface_transformers.py, examples/libtorchaudio/speech_recognition/parse_librispeech.py, examples/libtorchaudio/speech_recognition/parse_voxforge.py, examples/libtorchaudio/speech_recognition/transcribe.cpp, examples/libtorchaudio/speech_recognition/transcribe_list.cpp
Add C++ example using Wav2Vec2.0 model.
=> Add speech recognition C++ example

docs/source/functional.rst, torchaudio/functional/functional.py, torchaudio/transforms.py
- move `functional.resample` under Utility section
- reformat `Notes:` sections
=> Reformat resample docs

torchaudio/functional/functional.py, torchaudio/transforms.py
In 0.9.0, we are adding `return_complex=False` to spectrogram operation, so that users can choose whether they receive the resulting complex-valued tensor in pseudo complex tensor (real dtype with an extra dimension for real/imaginary parts) or native complex tensor (torch.cfloat / torch.cdouble).
Spectrogram operation returns raw, complex-valued tensor only when `power=None`. If `power` has some number, it returns the corresponding norm of the raw complex element. (such as power spectrogram) In this case, the value is always represented with real type, and there is no need to represent them in complex number.
The current version (0.9-RC1) checks if `return_complex=True` when `power is not non`. However, this does not align well with the use case. Users expecting power-spectrogram should …
=> Ignore return_complex when returning real-valued tensor in spectrogram.

test/torchaudio_unittest/compliance_kaldi_test.py, test/torchaudio_unittest/functional/batch_consistency_test.py, test/torchaudio_unittest/functional/functional_impl.py
Move resample tests from kaldi_compliance to functional, since we are deprecating kaldi's resample_waveform function and it is also standard to unit test in functional.
Follow up: 
- simplify sample rates in tests https://github.com/pytorch/audio/pull/1520#discussion_r636475527
=> Migrate kaldi resample tests to functional

test/torchaudio_unittest/rnnt/autograd_cpu_test.py, test/torchaudio_unittest/rnnt/autograd_cuda_test.py, test/torchaudio_unittest/rnnt/autograd_impl.py, test/torchaudio_unittest/rnnt/numpy_transducer.py
This PR
- adds to autograd test from carolineechen/audio#2 with `reuse_logits_for_grads=False` and `float32`.
- fixes numpy RNNTL implementation by avoiding inplace operation.
Follow-up noted below:
- Remove `reuse_logits_for_grads=True` for now see https://github.com/pytorch/audio/pull/1536. This is used for performance but requires `mark_dirty`, see https://github.com/vincentqb/audio/pull/10.
=> RNN Transducer Loss Autograd Test

torchaudio/functional/functional.py
=> Set removal version of pseudo complex support

docs/source/_static/css/override.css, docs/source/conf.py
Currently, hyperlinks created inside of PyTorch doc section title are not rendered correctly. (see https://github.com/pytorch/pytorch_sphinx_theme/issues/115)
When I was adding `bibtex` extension, I was placing the bibliography inside of `pytorch.article` (docstring) which suffers from the same rendering issue above. I added `override.css` to workaround this, but later I decided to put all the reference at the bottom of each page, which is outside of `pytorch.article` (docstring), so it no longer suffers from this, and the workaround of override CSS is not necessary.
=> Remove override CSS

.circleci/config.yml, .circleci/config.yml.in, test/torchaudio_unittest/common_utils/case_utils.py
In response to [https://github.com/pytorch/audio/issues/1552](https://github.com/pytorch/audio/issues/1552)
- Update the skipIfNoCuda decorator to raise an error if the TORCHAUDIO_TEST_FORCE_CUDA variable is set but CUDA is not available
- Update CI to use TORCHAUDIO_TEST_FORCE_CUDA in gpu unittests
=> Update skipIfNoCuda decorator/Force GPU tests run in GPU CIs

torchaudio/transforms.py
Resolves #1570 
Mel scale frequency is in general defined/used on power spectrogram and as far as we know, it is not defined for raw (complex value) spectrogram. When `power=None`, `MelSpectrogram` fails because of extra dimension (when using pseudo complex) or type mismatch between float and cfloat (when using native complex).
This PR changes type annotation so that power is only float.
@carolineechen Can you review? I think we can cherry-pick this to 0.9. Aldo Do you think this should be labeled BC-breaking? `power=None` never worked, so it does not break anything.
=> Update MelSpectrogram power annotation

torchaudio/functional/functional.py, torchaudio/models/conv_tasnet.py, torchaudio/models/deepspeech.py, torchaudio/models/wav2letter.py, torchaudio/models/wav2vec2/model.py, torchaudio/models/wavernn.py, torchaudio/prototype/rnnt_loss.py, torchaudio/transforms.py
Add name of paper before bibtex reference to make docstring readable to user of help command in python. This needs to be cherry-picked for release 0.9.
Follow-up to [comment](https://github.com/pytorch/audio/pull/1550#discussion_r646705780).
=> [Cherry-picked 0.9] Add name of paper before reference.

.circleci/config.yml, .circleci/regenerate.py
Port pytorch/vision#3998 and pytorch/vision#4053 so that adding a tag will trigger a documentation build-and-upload. The problem was that the upload depends on both the wheel and the build_docs builds, but those did not have the correct filter so they were not running.
Similar to pytorch/text#1332
It would be nice to see this merged before the next tag event, to make sure the docs are now building (the last few tags did not generate docs), although #1568 already generated the 0.9 docs.
=> fix tag build so it triggers prerequisites

README.md
PyTorch picks up the correct NumPy version, so it is not necessary to install separately.
=> Remove NumPy dependency from README

test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py
It seems that the return value of intermediate layer has been changed. 
The fixed assertion is redundant so we can remove it if there are too many changes on transformer side, but let's see how it goes.
=> Fix HF wav2vec2 integration test

torchaudio/__init__.py
removed the following items from `__all__`
'save_encinfo',
'sox_signalinfo_t',
'sox_encodinginfo_t',
'get_sox_option_t',
'get_sox_encoding_t',
'get_sox_bool',
'SignalInfo',
'EncodingInfo',
=> Remove residuals for removed modules

.circleci/unittest/linux/scripts/install.sh
The CMake integration of PyTorch core seems to have some issue after torch==1.10.0.dev20210619.
~While this is being worked on, we resort to PyTorch 1.9 for testing and binary build.~
Update: After https://github.com/pytorch/pytorch/pull/60403 Linux GPU conda is working. I updated the PR to pin Linux/macOS CPU test.
Binary builds and Windows testing are still broken.
=> Temporarily pin nightly version on Linux/macOS CPU unittest

.circleci/config.yml, .circleci/config.yml.in
The CUDA 10.1 was dropped from binary distribution in April.
Due to this #1583 fails to compile in GPU tests.
Update this so that the latest nightly is pulled correctly.
However latest nightly is exhibiting the issue with CMake-based build and GPU tests fail for another reason.
I will apply the hot fix separately, so that the hot fix is easy to revert later.
=> Update unit test CUDA to 10.2

.circleci/unittest/linux/scripts/install.sh
When hot fix was applied in #1598, it was only applied to CPU jobs.
This is because I looked at the nightly build, saw green lights on GPU unit test jobs, 
and thought that GPU jobs were somehow recovered.
It turned out, however, that GPU unit tests were fetching CUDA 10.1 binaries from April.
Because the PyTorch core dropped binary distribution for CUDA 10.1.
The unit test job was updated in #1605 to use CUDA 10.2. The GPU tests are now
picking up the latest nightly and failing because of broken CMake integration as expected.
This PR applies the same hot fix as in #1598 to GPU unit tests, so that they pass.
=> [HOT FIX] Temporarily pin nightly version on Linux GPU unit test

CONTRIBUTING.md, test/torchaudio_unittest/README.md
Here are the changes I made:
- Add optional installation instructions to CONTRIBUTING.md
- Remove duplicated installation information in test/torchaudio_unittest/README.md  (since we already direct people to CONTRIBUTING.md
- Fix the link to backend io tests in test/torchaudio_unittest/README.md
=> Update the installation and testing instructions.

build_tools/setup_helpers/extension.py
followup: RNNT loss needs to fall back onto CPU if compiled with GPU/USE_CUDA=1 but GPU is not available during run
=> Expose USE_CUDA in build

.circleci/config.yml, .circleci/config.yml.in, .circleci/torchscript_bc_test/environment.yml, .circleci/unittest/windows/scripts/environment.yml, packaging/pkg_helpers.bash
No longer needed for Python 3.9
Relates to https://github.com/pytorch/vision/pull/4082
=> ci: Remove mentions of conda-forge for Python 3.9

torchaudio/prototype/rnnt_loss.py
`gradients` variable is not accessed in Python code
=> Remove gradient variable from RNNT Loss Python code

torchaudio/backend/soundfile_backend.py
The test for backend/soundfile/save_test.py::TestFileObject::test_fileobj_flac is not working correctly. Please refer to #1592 for more details.
closes #1592
=> [BC-Breaking] Default to PCM_16 for flac on soundfile backend

test/torchaudio_unittest/backend/soundfile/save_test.py
Allow the test `soundfile.save_test::TestFileObject:test_fileobj_flac` to run in the Rocm stack.
=> Remove skipIfRocm from soundfile.save_test test_fileobj_flac

docs/source/models.rst, torchaudio/models/__init__.py, torchaudio/models/_utils.py, torchaudio/models/wavernn.py
Closes #776.
Offers pertained weight for WaveRNN with 8 bits waveform mode and trained on LJSpeech.
Following the convention [here](https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py#L53).
=> Add pretrained weights for wavernn

test/torchaudio_unittest/backend/sox_io/info_test.py, test/torchaudio_unittest/common_utils/sox_utils.py, torchaudio/csrc/sox/io.cpp, torchaudio/csrc/sox/utils.cpp, torchaudio/csrc/sox/utils.h, torchaudio/utils/sox_utils.py
torchaudio.info currently relies on a buffer of hardcoded size 4KB.
As a consequence, it doesn't work for files with headers larger than 4KB,
which is possible for ogg files, for instance. Here, we make the size of
torchaudio.info's buffer configurable to work for such files.
=> Make buffer size for function info configurable

test/torchaudio_unittest/functional/autograd_impl.py, test/torchaudio_unittest/functional/functional_impl.py, torchaudio/csrc/lfilter.cpp, torchaudio/functional/filtering.py
resolves #1528 , relates to #1561 
This merge add the ability to apply multiple filters in `F.lfilter`. 
When the input shape is `(..., time)`, if the shape of filter coefficients is `(number_of_filters, filter_order)`, the shape of output will be `(...., number_of_filters, time)`, which is the input shape *plus* one additional dimension from the filters. 
Before feeding to the cpp backend, the python frontend first duplicate the input `number_of_filters`  times and stacking them to form a shape of `(...., number_of_filters, time)`.
The cpp backend assume the shape of `waveform` and  `*_coeffs` are `(batch, number_of_filters, time)` and `(number_of_filters, filter_order)` (before are just `(batch, time)` and `(filter_order,)`). Different filters is applied parallelly at the second …
=> feat: lfilter with filterbanks support

README.md
###Typo/Grammatic Fixes:
> 'built' instead of second 'build' on line 67.
> 'achieved' instead of 'achieve' on line 83
> grammatic restructuring of sentence on line line 147.
=> fix typos and sentence structure in README.md

test/torchaudio_unittest/transforms/batch_consistency_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/transforms_test.py, test/torchaudio_unittest/transforms/transforms_test_impl.py, torchaudio/transforms.py
Rebases #1571; addresses #1569:
"In 0.9.0 we are deprecating the lazy behavior of MelScale because it can make an invalid TorchScript object and it does not align with the design of torchaudio. Now in master branch, we can remove the implementation."
=> Remove lazy behavior from MelScale

.gitmodules, examples/libtorchaudio/CMakeLists.txt, examples/libtorchaudio/speech_recognition/CMakeLists.txt, examples/libtorchaudio/speech_recognition/build_pipeline_from_fairseq.py, examples/libtorchaudio/speech_recognition/build_pipeline_from_huggingface_transformers.py, examples/libtorchaudio/speech_recognition/greedy_decoder.py
For ASR example with Wav2Vec2, I added some C++ based CTC decoder without language model. This should practically yield the same result as greedy decoding which can be implemented in Python very easily. For the purpose of example, this Python implementation is good enough, and it reduces compilation time and make the example simpler.
TODO:
=> Replace simple_ctc with Python greedy decoder

torchaudio/functional/functional.py
Example: replace `axis != 1 and axis != 2` with `axis not in [1, 2]`
=> Simplify axis value checks

torchaudio/transforms.py
Added example for [Resample](https://pytorch.org/audio/stable/transforms.html#torchaudio.transforms.Resample) as mentioned in [this issue](https://github.com/pytorch/audio/issues/1564)
=> added example for Resampler

torchaudio/transforms.py
Summary:
- The ``normalization`` parameter is changed to ``normalize`` in torch.load. Fix those in the example codes.
- Assign transform to an intermediate variable in the examples.
=> Fix examples in transforms

torchaudio/prototype/tacotron2.py
I found that there is a glitch at the `__forward__` method of Tacotron2 _Postnet.
The correct implementation to reference is [here](https://github.com/NVIDIA/DeepLearningExamples/blob/5a8521ee05934170ace0243f62e81cd7d7774fbd/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/model.py#L173).
=> Fix Tacotron2 Postnet forward

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, CONTRIBUTING.md, examples/pipeline_tacotron2/text/numbers.py, test/torchaudio_unittest/example/tacotron2/test_text_preprocessing.py
The tests for `example/pipeline_tacotron2` are moved to `test/torchaudio_unittest/example/tacotron2` in #1625. This PR also moves the text preprocessing tests into `test/torchaudio_unittest/tacotron2` so it will be run automatically by CI.
=> Refactor text preprocessing tests in Tacotron2 example

CONTRIBUTING.md, README.md
- Move convention section from README.md to CONTRIBUTING.md
- Changed `n_mel` to `n_mels` since all related variables in [functional](https://github.com/pytorch/audio/blob/master/torchaudio/functional/functional.py) and (transforms)[https://github.com/pytorch/audio/blob/master/torchaudio/transforms.py] are called `n_mels`.
- For `n_freq`, there are two exceptions ([1](https://github.com/pytorch/audio/blob/f5dbb0021b7c6b4681c55e9ebe9b601faa1fd4da/torchaudio/functional/functional.py#L380) and [2](https://github.com/pytorch/audio/blob/9a0e70ea6699e311c8f4e0c7a52d7042ce16b8b9/test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py#L99)) calling it `n_freqs`.
- `min_freq` and `max_freq` are changed to `f_min` and `f_max` are used …
=> Update and move convention section to CONTRIBUTING.md

examples/pipeline_wavernn/README.md, examples/pipeline_wavernn/inference.py, examples/pipeline_wavernn/processing.py, examples/pipeline_wavernn/wavernn_inference_wrapper.py
This example takes in an example from LJSPEECH and transform it into a mel spectrogram. The inference function of WaveRNN should be able to transform the mel spectrogram back to it's original waveform.
The implementation if ported from [here](https://github.com/fatchord/WaveRNN/blob/master/models/fatchord_version.py#L169).
@mthrok we may want to discuss whether to put [the inference function](https://github.com/pytorch/audio/pull/1637/files#diff-2f1a2a7054ae6468415baac0a5a6c4d7e40a36350942d65c8ba0ba3b469c47a4R181) into the core library since in the current form, it is not torchscriptable.
=> Add an inference example for wavernn

docs/source/datasets.rst, test/torchaudio_unittest/datasets/cmudict_test.py, torchaudio/datasets/__init__.py, torchaudio/datasets/cmudict.py
Adding the [CMUDict dataset](http://www.speech.cs.cmu.edu/cgi-bin/cmudict?stress=-s&in=) for mapping English words into phonemes. Currently, we have two intended usage: 
(1) This can be used for the Tacotron2 pipeline for training a TTS model base on phonemes instead of characters.
(2) This can also be used to train a model that [maps each word to phonemes](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43264.pdf).
Question:
How should we deal with the punctuation? For example,
```
!EXCLAMATION-POINT  EH2 K S K L AH0 M EY1 SH AH0 N P OY2 N T
"CLOSE-QUOTE  K L OW1 Z K W OW1 T
"DOUBLE-QUOTE  D AH1 B AH0 L K W OW1 T
"END-OF-QUOTE  EH1 N D AH0 V K W OW1 T
```
=> Add CMUDict dataset

examples/pipeline_wavernn/datasets.py, examples/pipeline_wavernn/inference.py, examples/pipeline_wavernn/main.py, examples/pipeline_wavernn/wavernn_inference_wrapper.py
If flake8 is run in `examples/pipeline_wavernn`, then we will get the following messages:
```bash
datasets.py:1:1: F401 'os' imported but unused
datasets.py:5:1: F401 'torchaudio' imported but unused
inference.py:4:1: F401 'torch.nn.functional as F' imported but unused
main.py:4:1: F401 'signal' imported but unused
main.py:12:1: F401 'torch.nn' imported but unused
wavernn_inference_wrapper.py:3:2: W291 trailing whitespace
wavernn_inference_wrapper.py:10:2: W291 trailing whitespace
wavernn_inference_wrapper.py:13:2: W291 trailing whitespace
wavernn_inference_wrapper.py:37:1: E302 expected 2 blank lines, found 1
wavernn_inference_wrapper.py:160:29: E128 continuation line under-indented for visual indent
wavernn_inference_wrapper.py:245:33: E128 continuation line under-indented for visual …
```
=> Refactor coding style for wavernn example

torchaudio/datasets/cmudict.py
It appears that there will be an error for the current `torchaudio.datasets.CMUDict` due to using the wrong data loading encoding. According to [this](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/text/cmudict.py#L23), we should use `latin-1` as the encoding method for loading CMUDict data.
=> Fix encoding of CMUDict data reading

torchaudio/extension/extension.py
Simplifies the mechanism to find the pass of the `_torchaudio` extension module.
See D29989551 for the context.
=> Simplify extension initialization

test/torchaudio_unittest/rnnt/autograd_impl.py, test/torchaudio_unittest/rnnt/rnnt_loss_impl.py, test/torchaudio_unittest/rnnt/utils.py, torchaudio/csrc/rnnt/autograd.cpp, torchaudio/csrc/rnnt/compute.cpp, torchaudio/csrc/rnnt/compute.h, torchaudio/csrc/rnnt/cpu/compute.cpp, torchaudio/csrc/rnnt/gpu/compute.cu, torchaudio/prototype/rnnt_loss.py
following discussion in [#1532](https://github.com/pytorch/audio/pull/1532#discussion_r647660456) and #1536, we are removing the `reuse_logits_for_grad` option for RNNT loss, as this results in modifying inputs in place and is not the usual behavior of a loss function
=> Remove reuse_logits_for_grads option for RNNTL

.circleci/unittest/linux/scripts/run_style_checks.sh, examples/interactive_asr/__init__.py, examples/libtorchaudio/speech_recognition/parse_voxforge.py, examples/source_separation/conv_tasnet/__init__.py, examples/source_separation/conv_tasnet/train.py, examples/source_separation/utils/__init__.py, examples/source_separation/utils/dataset/__init__.py, examples/source_separation/utils/dataset/utils.py
I've also fixed the flake8 errors.
Here is an copy of the original errors:
```bash
interactive_asr/__init__.py:1:1: F401 '.utils' imported but unused
interactive_asr/__init__.py:1:1: F401 '.vad' imported but unused
libtorchaudio/speech_recognition/parse_voxforge.py:10:121: E501 line too long (126 > 120 characters)
libtorchaudio/simplectc/tests/test_decode.py:77:1: W293 blank line contains whitespace
libtorchaudio/simplectc/tests/test_decode.py:160:121: E501 line too long (136 > 120 characters)
libtorchaudio/simplectc/setup.py:7:1: F401 'setuptools.find_packages' imported but unused
libtorchaudio/simplectc/simple_ctc/__init__.py:28:1: F401 '.decoder.BeamSearchDecoder' imported but unused
source_separation/utils/dataset/__init__.py:1:1: F401 '.utils' imported but unused …
```
=> Add style checks on example files on CI

test/torchaudio_unittest/rnnt/autograd_impl.py, test/torchaudio_unittest/rnnt/rnnt_loss_impl.py, test/torchaudio_unittest/rnnt/utils.py, torchaudio/csrc/rnnt/autograd.cpp, torchaudio/csrc/rnnt/compute.cpp, torchaudio/csrc/rnnt/compute.h, torchaudio/csrc/rnnt/cpu/compute.cpp, torchaudio/csrc/rnnt/gpu/compute.cu, torchaudio/csrc/rnnt/gpu/gpu_kernels.cuh, torchaudio/csrc/rnnt/gpu/gpu_transducer.h, torchaudio/csrc/rnnt/gpu/kernels.h, torchaudio/csrc/rnnt/options.h, torchaudio/prototype/rnnt_loss.py
Note: merge after #1610
Remove `fused_log_softmax` option and keep the behavior of the default `True` option. `fused_log_softmax=False` option was only relevant when `reuse_logits_for_grads=True`, but this behavior is no longer supported after #1610.
=> Remove fused_log_softmax option from RNNT Loss

torchaudio/prototype/rnnt_loss.py
contains changes from #1610 #1615, merge after
=> Improve RNNT Loss docstrings

examples/pipeline_tacotron2/README.md, examples/pipeline_tacotron2/datasets.py, examples/pipeline_tacotron2/train.py, examples/pipeline_tacotron2/utils.py
This ports the training script from [here](https://github.com/NVIDIA/DeepLearningExamples/blob/5a8521ee05934170ace0243f62e81cd7d7774fbd/PyTorch/SpeechSynthesis/Tacotron2/train.py).
Here are the things that are different:
- The melspectrogram are also changed to using torchaudio's implemenation
- The data loading part has been changed to using torchaudio's dataset
- tensorboard support are added
- Multi-gpu codes are ported from apex to torch.distributed
=> Add tacotron2 training script

torchaudio/datasets/cmudict.py
The property doc noe appears [here](https://290922-90321822-gh.circle-artifacts.com/0/docs/datasets.html#torchaudio.datasets.CMUDict.symbols) (which it does not appear [originally](https://pytorch.org/audio/main/datasets.html#torchaudio.datasets.CMUDict)).
=> Add documentation for CMUDict's property

.circleci/config.yml, .circleci/config.yml.in, setup.py
To test
```
conda install -y pytorch=1.8.1 torchvision=0.9.1 torchaudio=0.8.1 torchtext=0.9.1 cpuonly -c pytorch-lts
```
Then run `python -c "import torchaudio; print(torchaudio.__version__)" `
Output should be `0.8.1`
=> Update version setup.py for LTS

test/torchaudio_unittest/models/tacotron2/model_test_impl.py, torchaudio/prototype/tacotron2.py
Tacotron2 inference method ported from [nvidia](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/model.py).
Here are the things that are changed:
- Implemented the `infer` method for Tacotron2
- jit consistency test and output shape test for this `infer` method
- [This line is changed](https://github.com/pytorch/audio/pull/1648#issue-699091717) because `decoder_early_stopping` is by default True and it is an error from the last commit.
- Some of the variable names are also renamed for consistency ([here](https://github.com/pytorch/audio/pull/1648/files#diff-8b8ec57192b9aaeb99a9ec5e709c977771b31b49fe7ddc6704c2128cf161a00eR642) and [here](https://github.com/pytorch/audio/pull/1648/files#diff-001793fb337f116c66a3e7f3869a18012a618ab079df93d …
=> Add Tacotron2 inference method

packaging/torchaudio/meta.yaml
BUILD_VERSION gets set by upstream scripts and should be available
whenever we're attempting to build audio in conda environments.
This solves the issue where conda packages appeared to be building a
development version instead of the actual version we were targeting
Closes #1696 
=> packaging: Ensure we're propagating BUILD_VERSION

docs/source/index.rst, docs/source/refs.bib, docs/source/tacotron2.rst, torchaudio/prototype/tacotron2.py
As discussed https://github.com/pytorch/audio/pull/1693#discussion_r687074068, I've created a separate documentation page for prototype functionalities.
[Here](https://297118-90321822-gh.circle-artifacts.com/0/docs/tacotron2.html) is the resulting documentation.
=> Add prototype page to docs

test/torchaudio_unittest/rnnt/rnnt_loss_impl.py, torchaudio/csrc/rnnt/cpu/compute.cpp, torchaudio/csrc/rnnt/gpu/compute.cu
Previously, forward calls to `RNNTLoss` or `rnnt_loss` would fail with a `cannot call get_autograd_meta() on undefined tensor` error when `requires_grad=False`. This PR resolves this issue so that forward calls can be made even when the logits do not have `requires_grad=True`.
=> RNNT Loss remove null grads

examples/pipeline_tacotron2/inference.py
- the `wavernn_vocode` called on line 327 is missing the `wavernn_checkpoint_name` argument, this PR fixes this
- also refactored the function call `griffin_lim_vocode` on line 338 so that it is more readable
=> Fix Tacotron2 inference example

third_party/kaldi/CMakeLists.txt
When building torchaudio from source, `get_version.sh` from kaldi is executed everytime,
which results in kaldi-bindings to be always rebuilt.
This commit add "if" guard to the part so that they are not always executed.
=> Guard Kaldi's version generation

torchaudio/_internal/module_utils.py, torchaudio/backend/soundfile_backend.py
Summary:
Add additional check of libsndfile when soundfile is needed.
Address https://github.com/pytorch/audio/issues/1687
No functional change
Test steps:
1. Setup
Install soundfile: $ pip install soundfile
delete libsndfile: $ conda remove libsndfile
2. Repro the error
(audio) [bowangbj@devgpu006.pnb1 ~/local/audio] python
Python 3.9.6 (default, Jul 30 2021, 16:35:19) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchaudio
/data/users/bowangbj/audio/torchaudio/_internal/module_utils.py:87: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
$conda install -c conda-forge libsndfile
3. Fix the error …
=> Add additional guard to libsndfile

docs/source/functional.rst, docs/source/transforms.rst
Following discussion from https://github.com/pytorch/audio/pull/1711#discussion_r691372056, add subsections in pytorch docs for transforms similar to functional
=> Add sections to transforms docs

torchaudio/transforms.py
Added Example for [Fade Transform](https://pytorch.org/audio/stable/transforms.html#torchaudio.transforms.Fade) as mentioned in [this issue](https://github.com/pytorch/audio/issues/1564).
=> Added example for Fade transform

docs/source/models.rst, examples/pipeline_wavernn/inference.py, examples/pipeline_wavernn/wavernn_inference_wrapper.py, test/torchaudio_unittest/models/models_test.py, torchaudio/models/wavernn.py
As discussed in #1651 
The training part of the WaveRNN seems to support two loss functions -- CrossEntropy and MolLoss
(https://github.com/pytorch/audio/blob/main/examples/pipeline_wavernn/losses.py). Currently the inference code only supports the model trained with CrossEntropy since there is no pretrained model trained with MolLoss to test it out yet.
=> Refactor WaveRNN infer and move to codebase

third_party/kaldi/CMakeLists.txt, torchaudio/csrc/CMakeLists.txt
It's wrong to depend on `${TORCH_LIBRARIES}` as it pulls in explicit
`libcuda.so.1` dependency, which violates the assumption that GPU
accelerated libraries should be loadable with no NVIDIA drivers installed
Instead, make it depend on `torch` target, which includes all necessary
Torch C++ API dependences
=> Fix CUDA build logic for _torchaudio.so

.circleci/config.yml, .circleci/config.yml.in, packaging/build_conda.sh, packaging/build_wheel.sh, packaging/pkg_helpers.bash, packaging/torchaudio/meta.yaml
Remove some obsolete conditions about CUDA-10.0 from pkg_helpers.sh.
Use `USE_CUDA` instead of `FORCE_CUDA` in pkg_helpers
Do not define `NO_CUDA_PACKAGE` in `build_wheel.sh` and `build_cuda.sh`
TODO: Fix Windows CUDA builds
=> Enable Linux wheel/conda GPU package builds

.circleci/config.yml, .circleci/config.yml.in
Downloading CUDA-11.1 from conda-forge takes a while
=> Increase no_output_timeout to 20m for WinConda

examples/pipeline_wavernn/main.py
We saw that in [this commit](https://github.com/pytorch/audio/commit/e061b268d284a6f43acc44314b83ec6ffe58e91a#diff-a473ab6313da91f82a155edc91015cd96b4867cff38d9dd63bf75dfd411281b3), we ported mel spectrogram from librosa to torchaudio. However this port misses a parameter norm.
[This internal link](https://colab.research.google.com/drive/18d1xOp3x4EEgsa_OIZRYaKB7k_Mig12m?usp=sharing) shows that by adding the `norm='slaney'` parameter to `torchaudio.transforms.MelSpectrogram`, we are able to maintain the original transform (`torchaudio.transforms.Spectrogram` +  `LinearToMel`).
=> Fix WaveRNN training example

examples/pipeline_tacotron2/datasets.py, examples/pipeline_tacotron2/text/text_preprocessing.py, examples/pipeline_wavernn/wavernn_inference_wrapper.py, examples/source_separation/utils/dataset/wsj0mix.py, examples/source_separation/utils/metrics.py, torchaudio/backend/soundfile_backend.py, torchaudio/backend/sox_io_backend.py, torchaudio/backend/utils.py, torchaudio/datasets/gtzan.py, torchaudio/datasets/speechcommands.py, torchaudio/datasets/tedlium.py, torchaudio/datasets/utils.py, torchaudio/datasets/vctk.py, torchaudio/functional/filtering.py, torchaudio/functional/functional.py, torchaudio/models/conv_tasnet.py, torchaudio/models/wav2vec2/components.py, torchaudio/models/wav2vec2/model.py, torchaudio/models/wav2vec2/utils/import_fairseq.py, torchaudio/sox_effects/sox_effects.py, torchaudio/transforms.py
standardize optional type representation in docstrings:
- type `T` with default value: `T, optional`
- type `Optional[T]`: `T or None`
- type `Optional[T]` with default value: `T or None, optional`
=> Standardize optional types in docstrings

test/torchaudio_unittest/common_utils/data_utils.py, test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py
Put the random audio data generated by `get_whitenoise()` utility function onto the proper device, rather than defaulting to cpu.
Additionally, fix any test failures that arise from this change.
=> Put output tensor on proper device in `get_whitenoise()`

torchaudio/csrc/pybind/sox/effects.cpp, torchaudio/csrc/pybind/sox/io.cpp
Preparation for splitting `libtorchaudio` and `_torchaudio`.
When two libraries are compiled separately, and each code does
`#include <sox.h>` independently, two copies of libsox's static global
variables (`sox_globals_t`) are created.
Our code should be referring to the same instance. To achieve this,
`_torchaudio` should be accessing the global variable defined in
`libtorchaudio` via the custom utility functions, and it should not
directly use `sox_get_globals`.
=> Update the way to access libsox global config

.circleci/unittest/linux/scripts/install.sh, packaging/pkg_helpers.bash, packaging/torchaudio/meta.yaml
* Pin MKL to 2021.2.0
Fixes https://github.com/pytorch/pytorch/issues/62424
* Apply the same  constraint for conda builds
Use less-than-equals constraint to avoid dependency conflicts for
python-3.6 environment
=> Pin MKL to 2021.2.0 (#1655)

torchaudio/csrc/pybind/sox/effects.cpp, torchaudio/csrc/pybind/sox/effects_chain.cpp, torchaudio/csrc/pybind/sox/io.cpp
* Fix comparison between signed and unsigned integer expressions
```
../../torchaudio/csrc/pybind/sox/effects.cpp:59:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
return (bufsiz > kDefaultCapacityInBytes) ? bufsiz
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
../../torchaudio/csrc/pybind/sox/io.cpp:47:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
return (bufsiz > kDefaultCapacityInBytes) ? bufsiz
```
* Remove unused variable
```
../../torchaudio/csrc/pybind/sox/effects_chain.cpp:131:10: warning: unused variable ‘buffer_size’ [-Wunused-variable]
auto buffer_size = priv->buffer_size;
^~~~~~~~~~~
```
=> Fix linting

.circleci/config.yml, .circleci/config.yml.in
CCI says circleci/python:3.8 is deprecaetd. Migrating to cimg/python:3.8.
> CircleCI’s latest pre-built container images were designed from the ground up to help your team build more reliably.
> Our new images were built specifically for continuous integration projects and they are our most deterministic, performant, and efficient images yet.
> As of Dec 31, 2021, legacy images will no longer be supported on CircleCI.
Related links
- https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic
- https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
- https://circleci.com/docs/2.0/next-gen-migration-guide
=> Migrate CircleCI docker image

CMakeLists.txt, build_tools/setup_helpers/extension.py, examples/libtorchaudio/CMakeLists.txt, torchaudio/__init__.py, torchaudio/_extension.py, torchaudio/csrc/CMakeLists.txt
This PR splits the extension module (`_torchaudio.so`) into non-Python part (`libtorchaudio.so`) and Python wrapper around it (`_torchaudio.so`).
Overview of changes
- cmake always builds libtorchaudio (the core implementation)
- `BUILD_LIBTORCHAUDIO` option is removed from CMake.
The new assumptions around the library discoverability
- In regular OSS workflow (`pip`/`conda`-based binary installation), both `libtorchaudio.so` and `_torchaudio.so` are present.
In this case,`libtorchaudio.so` has to be loaded manually with `torch.ops.load_library` and/or `torch.classes.load_library` otherwise importing `_torchaudio` would not be able to resolve the symbols defined in `libtorchaudio.so`.
- When `torchaudio` is deployed with PEX format (single zip file)
- We expect that`libtorchaudio.so` …
=> Split extension into non-Python and Python wrapper libraries

test/torchaudio_unittest/transforms/batch_consistency_test.py
The current batch consistency tests don't consider the inter-batch operation. If the transform contains inter-batch operation then the test should be failed. In the current implementation the inputs are repeated, hence the inter-batch operation may not be reflected.
=> Refactor batch consistency test in transforms

docs/source/models.rst
Cleans up categories in models.
Before
After
=> Fix indentation and grouping

test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py, test/torchaudio_unittest/models/wav2vec2/model_test.py, torchaudio/models/wav2vec2/components.py, torchaudio/models/wav2vec2/model.py
Originally, `extract_features` method was returning the result from
passing the input waveform to convolutional feature extractor module.
The features commonly used in downstream tasks are outputs from intermediate
layers of transformer block in encoder.
This commit update the behavior of `extract_features` to allow selectively
retrieve such features.
The previous behavior can be achieved with
`Wav2Vec2Model.feature_extractor(waveform)`.
=> [BC-Breaking] Update `extract_features` of Wav2Vec2Model

test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py, test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py, test/torchaudio_unittest/models/wav2vec2/model_test.py
Spin-off from my working branch;
Apply tweak around the test names so that it's easier to see which tests are failing.
before: `test_import_finetuned_model_2`
after:  `test_import_finetuned_model_2_wav2vec2_large_lv60k`
=> Tweak test name by appending factory function name

test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py, torchaudio/models/wav2vec2/utils/import_huggingface.py
Previously, when testing wav2vec models from HF transformers, all the model were
instantiated as `Wav2Vec2ForCTC` class, while some of them were supposed to be
`Wav2Vec2Model`.
Fixing this revealed that model importer cannot correctly handle `Wav2Vec2Model` import.
This PR fixes these issues.
=> Fix HF model integration

test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py, torchaudio/models/wav2vec2/components.py, torchaudio/models/wav2vec2/model.py, torchaudio/models/wav2vec2/utils/import_fairseq.py, torchaudio/models/wav2vec2/utils/import_huggingface.py
[BC-Breaking] Move fine-tune specific module out of wav2vec2 encoder
Previously, the Linear module (called `readout`), used for an ASR fine-tuning task, was placed in encoder module. Conceptually, the encoder has nothing to do with a module specific to fine-tuning / downstreaming task.
The problems here are that;
1. encoder can be also used in pretraining phase, which does not require such a module.
2. The choice of Linear module is arbitral, and it is inconvenient for users to have hard-coded module structure in encoder.
Therefore this commit moves the Linear module out the encoder, and places it as `aux` attribute of `Wav2Vec2Model`. (as a result `Wav2Vec2Model` has `feature_extractor`, `encoder` and `aux` moduels)
An alternative approach is to define another module and place …
=> [BC-Breaking] Move fine-tune specific module out of wav2vec2 encoder

.circleci/config.yml, .circleci/config.yml.in
It's the culprit that torch.cuda.is_available() always return False.
https://app.circleci.com/pipelines/github/pytorch/audio/7395/workflows/a1a046b3-d808-468b-be9c-30db30244d44/jobs/339150
It's the first PR to enable unit tests with cuda on windows
@malfet @mthrok 
It's verified in
https://app.circleci.com/pipelines/github/pytorch/audio/7396/workflows/058b3c2c-8421-40c2-915c-a8441deac091/jobs/339245
=> update windows gpu image from previous to stable

torchaudio/_extension.py, torchaudio/csrc/CMakeLists.txt
It's a supplement of #1752, which fixes an error while build audio on Windows with CUDA
The change has been verified in install torchaudio step of 
https://app.circleci.com/pipelines/github/pytorch/audio/7405/workflows/5ac1303e-ac19-4180-8327-75fd7f8cdcac/jobs/340152.
And I verified it locally as well
=> set libtorchaudio suffix as pyd on Windows

CMakeLists.txt
With this PR, audio could be build on Windows with CUDA now.
It's from https://github.com/pytorch/audio/pull/1777
I've verified it locally.
=> Enable audio build on Windows with CUDA

docs/source/models.rst, test/torchaudio_unittest/models/wav2vec2/fairseq_integration_test.py, test/torchaudio_unittest/models/wav2vec2/huggingface_intergration_test.py, test/torchaudio_unittest/models/wav2vec2/model_test.py, torchaudio/models/__init__.py, torchaudio/models/wav2vec2/__init__.py, torchaudio/models/wav2vec2/components.py, torchaudio/models/wav2vec2/model.py, torchaudio/models/wav2vec2/utils/import_fairseq.py, torchaudio/models/wav2vec2/utils/import_huggingface.py
Previously, factory functions of wav2vec2 only generated the architecture
for the fine-tuning architecture used in wav2ve2 paper for ASR task.
That is, pre-training architecture + Linear module, and it did not
provide a straightforward way to generate architectures for pre-training.
The goal of the original implementation was to allow the inference of
wav2vec2 in non-Python environment via TorchScript. Now we would like to
expand it to pre-training/fine-tuning and HuBERT model as well.
Therefore, we need to have factory functions for both pre-training and
fine-tuning. This commit introduces new factory functions and separate
functions for pre-training and fine-tuning.
1. New functions for ASR fine-tuning.
We introdcue `wav2vec2_asr_XXX` functions which generates the architecture
used for …
=> [BC-Breaking] Split pretraining and finetuning factory functions

torchaudio/models/wav2vec2/model.py
=> [doc] Fix return type of wav2vec2 model

test/torchaudio_unittest/models/wav2vec2/model_test.py
Skipping the failing `test_finetune_torchscript_4_hubert_asr_xlarge` on Windows. 
Failure log https://app.circleci.com/pipelines/github/pytorch/audio/7480/workflows/8f04fd1e-6add-4be6-975d-98701dd81fbd/jobs/347505
The issue is reported here https://github.com/pytorch/pytorch/issues/65776
=> Skip hubert_asr_xlargeTS test on Windows

examples/libtorchaudio/speech_recognition/build_pipeline_from_fairseq.py, examples/libtorchaudio/speech_recognition/build_pipeline_from_huggingface_transformers.py, test/torchaudio_unittest/models/wav2vec2/model_test.py
Cherry-pick dc17160ac88404a6afc8f25fa6b83c560617146f which landed in `fbsync` branch via D31302450. (Corresponding export is in #1817)
Closes #1817
=> [fbsync] torchaudio: torch.quantization -> torch.ao.quantization

torchaudio/models/wav2vec2/components.py
Replacing drop out from functional to module based so that the architecture is a bit clearer.
https://github.com/pytorch/audio/pull/1776#pullrequestreview-759070914
=> Replace dropout with Dropout

examples/hubert/utils/feature_utils.py
In ``torchaudio.compliance.kaldi.mfcc``, given an 1-second torch tensor of shape `(1, 16000)`, the shape of the MFCC feature is `(98, 13)`. 
To make ``torchaudio.transforms.MFCC`` consistent with the one above, add the melkwargs settings to match the output shape.
=> Add melkwargs setting for MFCC in HuBERT pipeline

docs/requirements.txt
Resolves;
```
$ make html
Running Sphinx v3.5.4
making output directory... done
Exception occurred:
File "/opt/_internal/cpython-3.8.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.4 (/opt/_internal/cpython-3.8.1/lib/python3.8/site-packages), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})
The full traceback has been saved in /tmp/sphinx-err-jaxom3j2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error
``` …
=> Update requirements.txt for doc build

.github/workflows/bandit.yml, tools/retrieve_prs.py
refer to https://github.com/pytorch/vision/pull/4626
=> Refactor collecting-PR script for release note

.github/workflows/integration-test.yml, test/integration_tests/conftest.py
This PR adds integration test CI jobs.
It also adds custom `--use-tmp-hub-dir` option so that pre-trained weights (some of them are larger than 1GB) are deleted after each test. This should avoid the failure where CI runs out of the disk space.
Since we expect the integration job to download huge files, the test is only ran with Python 3.8.
=> Run integration tests on CI

.github/process_commit.py, .github/workflows/pr-labels.yml
I found it hard to recall which labels are primary and which are secondary. This PR changes the bot to include that in the message.
```
% python .github/process_commit.py cbf267c357a7574d9382ffcace75089dc2798295
Hi @mthrok
You merged this PR, but the category labels are missing.
Please add a primary label (`bug fix`, `example`, `other`, `prototype`, `new feature`, `BC-breaking`, `deprecation`, `improvement`) and a secondary label (`module: ops`, `style`, `module: tests`, `other`, `build`, `module: docs`, `perf`, `module: models`, `module: datasets`, `module: pipelines`, `module: I/O`).
```
```
% python .github/process_commit.py 8c78273be11f05b8b77ba24f0764829b7b404b7b
```
=> Update PR label notifier

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, .github/workflows/codeql.yml, .github/workflows/integration-test.yml, setup.py
This PR changes the build process so that the third party code are fetched automatically when `setup.py` is invoked.
This is to allow
1. `build_sdist` to contain the third party library codes, so that source code distribution created at the time release tag is created is complete.
2. It makes it possible to do `pip install https://github.com/pytorch/audio.git`.
Example: https://colab.research.google.com/drive/1hK-WfiIKDTgccOmbdPwMd-b9LTA8Yg0n?usp=sharing
```
!pip install 'cmake>=3.18' ninja
!pip install --verbose git+https://github.com/mthrok/audio.git@auto-source
```
~Note:~
~I am changing all the CI test job to use `pip install ...` in place of `python setup.py ...`, following the movement around PEP 517 (interesting read https://bernat.tech/posts/pep-517-518/), but I leave the …
=> Fetch third party sources automatically

test/torchaudio_unittest/functional/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/autograd_test_impl.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Following the plan #1337, this PR drops the support for pseudo complex type from `F.spectrogram` and `T.Spectrogram`. It also deprecates the use of `return_complex` argument.
=> [BC-Breaking] Drop pseudo complex support from spectrogram

test/torchaudio_unittest/functional/functional_impl.py, test/torchaudio_unittest/functional/librosa_compatibility_test_impl.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py, test/torchaudio_unittest/transforms/autograd_test_impl.py, test/torchaudio_unittest/transforms/batch_consistency_test.py, test/torchaudio_unittest/transforms/torchscript_consistency_impl.py, torchaudio/functional/functional.py, torchaudio/transforms.py
Following the plan #1337, this PR drops the support for pseudo complex type from `F.phase_vocoder` and `T.TimeStretch`.
=> [BC-Breaking] Drop pseudo complex support from phase_vocoder / TimeStretch

test/integration_tests/conftest.py, torchaudio/_internal/__init__.py, torchaudio/pipelines/_tts/impl.py, torchaudio/pipelines/_tts/utils.py, torchaudio/pipelines/_wav2vec2/impl.py
This commit changes all the `torch.hub` network utility functions to
be imported from `torchaudio._internal`, so that later we can replace
the function within fbcode.
Supersedes #1959
See also [D32078361](https://phabricator.intern.facebook.com/D32078361)
=> Consolidate network utils

.circleci/build_docs/build_docs.sh, CONTRIBUTING.md, docs/requirements-tutorials.txt, docs/requirements.txt, docs/source/conf.py
With the introduction of TTS tutorial (#1973), it takes more than couple of minutes
to build documentation. This commit makes the doc build process defaults to
not build tutorials.
https://422851-90321822-gh.circle-artifacts.com/0/docs/auto_examples/wav2vec2/index.html
To build tutorials one can use environment variable `BUILD_GALLERY=1`,
and set `GALLERY_PATTERN=...` to filter the tutorials to build.
This `GALLERY_PATTERN` is same approach as in `tutorials` repo.
https://github.com/pytorch/tutorials/blob/cbf2238df0e78d84c15bd94288966d2f4b2e83ae/conf.py#L75-L83
Also this commit dynamically parse the subdirectory of `examples/gallery` so that when a new category of examples are added, it will automatically parsed.
=> Tweak doc build

docs/source/_templates/layout.html
This commit adds colab/download/source link to tutorials, like in `pytorch/tutorials` repo.
Since the upstream `pytorch-sphinx-theme` does not provide the interface for this, I added a hack to update URL after the document is ready.
The hack might stop working if there is some update in `pytorch-sphinx-theme`.
=> Add Colab/Download/Github link similar to tutorials

docs/requirements.txt
The hack introduced in #1969 could break if upstream theme changes its HTML or Javascript.
To prevent our documentation from randomly break, this commit fixes the commit of the them.
=> Fix pytorch_sphinx_theme version

examples/gallery/tts/tacotron2_pipeline_tutorial.py, examples/gallery/wav2vec2/forced_alignment_tutorial.py, examples/gallery/wav2vec2/speech_recognition_pipeline_tutorial.py
It turned out that generated tutorials can embed the audio if the following conditions are met.
This commit changes how audio samples are shown in tutorials so that they become playable in doc.
1. There is only one `IPython.display.Audio` call in a cell
2. `IPython.display.Audio` is the last function called in the cell
3. Audio format is `wav`
(`flac` can be embedded as well, but browsers (Chrome/Safari) won't play it)
Ref: https://stackoverflow.com/a/33109647
*Before*
*After*
=> Embed audio samples in generated tutorials

docs/source/index.rst, examples/tutorials/audio_data_augmentation_tutorial.py, examples/tutorials/audio_datasets_tutorial.py, examples/tutorials/audio_feature_augmentation_tutorial.py, examples/tutorials/audio_feature_extractions_tutorial.py, examples/tutorials/audio_io_tutorial.py, examples/tutorials/audio_resampling_tutorial.py
This commit ports Audio I/O tutorials from tutorials repo.
The tutorials are placed under the new `Getting Started` section, and the index page is updated a bit.
*Current*
https://pytorch.org/audio/main/index.html
*After*
https://426860-90321822-gh.circle-artifacts.com/0/docs/index.html
Note: I cannot `import boto3` on M1 Mac. I think it's an issue with the binary signature (`killed 9`). So the doc build process will not work on M1 Mac.
=> Port Audio I/O tutorials

_config.yml
To address https://github.com/pytorch/audio/issues/1996
=> Fix Wav2Vec2ASRBundle document page

.circleci/unittest/linux/scripts/install.sh, .circleci/unittest/windows/scripts/install.sh, .github/workflows/codeql.yml, setup.py
Cherry-picking
- ~#2050 Fix for TORCH_CUDA_ARCH_LIST~
**UPDATE**: Since #2050 has no merge conflict, I pushed it to the release branch directly.
- #1966 Fetch third party sources automatically
The later is so that the source distribution on GitHub contains all the sources required to build torchaudio.
=> [release/0.10] Cherry pick #1966 to release/0.10

.circleci/config.yml, .circleci/config.yml.in
Ppdate circle ci torchaudio/pytorch versions for release
=> Set release version and base PyTorch version for 1.11 pytorch release

torchaudio/functional/functional.py
`torch.complex32` is disabled in PyTorch release 1.11. The PR removed the `complex32` data type support in `torchaudio.functional.griffinlim` in torchaudio's 0.11 release.
=> [Release 0.11] Remove complex32 dtype in griffinlim

setup.py
As in #1901: "fix the version number in `setup.py` so that if users check out the release tag and build torchaudio manually, the version is correct".
=> [release 0.12] Remove alpha from version number

.circleci/config.yml, .circleci/config.yml.in
Sets release version to 0.12 and base PyTorch version to 1.12 in CircleCI config files in preparation for release.
=> [release 0.12] Set release version and base PyTorch version

.circleci/unittest/windows/scripts/install.sh
The version of MKL that is installed alongside PyTorch has been bumped
to 2022.1 and it is causing issue.
This commit pins the previous version
=> [release 0.12] Pin MKL to 2020.04

.circleci/config.yml, .circleci/config.yml.in
Lint style has diverged since fb-internal lint engine has been changed.
It's no longer relevant on release branch, so disabling it.
=> [release 0.12] Disable lint CI signal on release

torchaudio/backend/sox_io_backend.py
Loading and querying file-like object is not possible to use the fallback
mechanism introduced in https://github.com/pytorch/audio/pull/2419 because file-like objects are not seekable.
This commit add special case handling to mp3.
For filelike object mp3 input, it was required to pass `format="mp3"`
because libsox did not auto detect the format.
With the transition of mp3 handling from libsox to ffmpeg, the logic
is to let the ffmpeg handle it without waiting for libsox to fail,
if the `format="mp3"`
=> Add special case for mp3 filelike object

.github/workflows/build-m1-binaries.yml, packaging/pkg_helpers.bash
Summary:
Adding conda builds for M1
Pull Request resolved: https://github.com/pytorch/audio/pull/2473
Differential Revision: D37151454
fbshipit-source-id: 0108b937a4c7048bd4bb03b2b5a367704d7b78cc
=> Adding conda builds for M1 (#2473)

_config.yml
Modules that start with underscore are not shown in source.
Before:
- https://pytorch.org/audio/0.12.0/_modules/torchaudio/io/_stream_reader.html#StreamReader
After:
- https://mthrok.github.io/audio/0.12.0/_modules/torchaudio/io/_stream_reader.html#StreamReader
=> Include private module files to doc source

.github/workflows/build-m1-binaries.yml
Summary:
Making sure we are picking correct release branch
Ref: https://github.com/pytorch/vision/pull/6168
Pull Request resolved: https://github.com/pytorch/audio/pull/2489
Differential Revision: D37160145
fbshipit-source-id: 3e4a2208cbe47f85147573159f9adb8d6a824956
=> Making sure we are picking correct release branch (#2489)

packaging/pkg_helpers.bash
Fix torchaudio build channel for the release
Please refere to: https://github.com/pytorch/text/pull/1940
=> Fix torchaudio build channel for the release

examples/asr/librispeech_ctc_decoder/inference.py
This pull request contains code that I added to the librispeech_ctc_decoder inference.py example to evaluate if pytorch 2.0 compile() optimizations can help this model. To summarize, my findings are:
- torch.inference_mode() had to be replaced by torch.no_grad()
- I couldn't use compile() with dynamic tensor sizes (yet).
- Passing the 'lengths' parameter to the wav2vec2 model also breaks the compilation.
- Overall, there's a ~10% performance improvement using CUDA, and up to 38% on CPU, but this is currently achievable only by padding all samples to make sure tensor sizes are equal, and this hurts performance.
=> Experimenting with Pytorch 2.0 compile() optimizations on wav2vec2 models

.circleci/config.yml, .circleci/regenerate.py
[Release only changes] Remove python 3.11 from circleci unit tests
Similar to: https://github.com/pytorch/vision/commit/dd5e8a48cdfa4bb20d5d382214ca30325c049944
=> [Release only changes] Remove python 3.11 from circleci unit tests

.circleci/config.yml, .circleci/config.yml.in, docs/source/hw_acceleration_tutorial.ipynb, examples/tutorials/streamwriter_advanced.py
Summary:
Fix build_doc job
https://app.circleci.com/pipelines/github/pytorch/audio/15217/workflows/ce50b317-a59e-4741-b8d2-59129420deb8
- build.ffmpeg.html might not exist when IPython notebook is processed. Changing to main doc URL.
- Fix bash cell syntax in HW tutorial
- Fix C++ doc
- Fix duplicated target name in streamwriter tutorial
Pull Request resolved: https://github.com/pytorch/audio/pull/3125
Reviewed By: xiaohui-zhang
Differential Revision: D43724078
Pulled By: mthrok
fbshipit-source-id: ea7d46ec5e377cf2fbd7c3798df57da73750ac5c
=> [Cherry-pick release/2.0] Fix doc build (#3125)

test/torchaudio_unittest/io/stream_writer_test.py, torchaudio/csrc/ffmpeg/stream_writer/stream_writer.cpp
Summary:
Some audio encoders expect specific, exact number of samples described as in `AVCodecContext.frame_size`.
The `AVFrame.nb_samples` is set for the frames passed to `AVFilterGraph`, but frames coming out of the graph do not necessarily have the same numbr of frames.
This causes issues with encoding OPUS (among others).
This commit fixes it by inserting `asetnsamples` to filter graph if a fixed number of samples is requested.
Note:
It turned out that FFmpeg 4.1 has issue with OPUS encoding. It does not properly discard some sample. We should probably move the minimum required FFmpeg to 4.2, but I am not sure if we can enforce it via ABI. Work around will be to issue an warning if encoding OPUS with 4.1. (follow-up)
Pull Request resolved: https://github.com/pytorch/audio/pull/3204 …
=> [Cherry-pick 2.0.1] Properly set #samples passed to encoder (#3204)

test/torchaudio_unittest/models/decoder/ctc_decoder_test.py, torchaudio/models/decoder/_ctc_decoder.py
Summary:
Currently, creating CTCDecoder object by passing a language model to `lm` argument without assigning it to a variable elsewhere causes `RuntimeError: Tried to call pure virtual function "LM::start"`.
According to discussions on PyBind11, (
https://github.com/pybind/pybind11/discussions/4013 and https://github.com/pybind/pybind11/pull/2839
) this is due to Python object garbage-collected by the time it's used by code implemented in C++. It attempts to call methods defined in Python, which overrides the base pure virtual function, but the object which provides this override gets deleted by garbage collrector, as the original object is not reference counted.
This commit fixes this by simply assiging the given `lm` object as an attribute of CTCDecoder class.
Address …
=> [Cherry-pick 2.0.1] Fix virtual function issue with CTC decoder (#3230)

test/torchaudio_unittest/backend/dispatcher/ffmpeg/info_test.py, test/torchaudio_unittest/backend/dispatcher/ffmpeg/load_test.py, test/torchaudio_unittest/backend/dispatcher/ffmpeg/save_test.py, torchaudio/_backend/utils.py, torchaudio/io/_compat.py
Summary:
In dispatcher mode, FFmpeg backend does not handle file-like object, and C++ implementation raises an issue.
This commit fixes it by normalizing file-like object to string.
Pull Request resolved: https://github.com/pytorch/audio/pull/3243
Reviewed By: nateanl
Differential Revision: D44719280
Pulled By: mthrok
fbshipit-source-id: 9dae459e2a5fb4992b4ef53fe4829fe8c35b2edd
=> [Cherry-pick] Fix path-like object support in FFmpeg dispatcher (#3243, #3248)

torchaudio/models/wav2vec2/components.py
Summary:
Replace the attention computation with `torch.nn.functional.scaled_dot_product_attention` to improve running efficiency.
Pull Request resolved: https://github.com/pytorch/audio/pull/3253
Differential Revision: D44800353
Pulled By: nateanl
fbshipit-source-id: 41550d868c809099aadbe812b0ebe2c38121efb8
=> [Cherry-pick] Use scaled_dot_product_attention in Wav2vec2/HuBERT's SelfAttention (#3253)

torchaudio/models/wav2vec2/wavlm_attention.py
Summary:
Fix https://github.com/pytorch/audio/issues/3219.
`torch.nn.MultiheadAttention` will throw an error if `torch.no_grad()` and mask are both given. The pull request fixes it by replacing the forward method with `torch.nn.functional.scaled_dot_product_attention`.
Pull Request resolved: https://github.com/pytorch/audio/pull/3252
Differential Revision: D44798634
Pulled By: nateanl
fbshipit-source-id: abfa7fb84b7bd71848a92ab26da5a5f0f095c665
=> [Cherry-pick] Use scaled_dot_product_attention in WavLM attention (#3252, #3265)

.circleci/config.yml, .circleci/config.yml.in, .circleci/unittest/windows/scripts/install.sh, .circleci/unittest/windows/scripts/set_cuda_envs.sh, packaging/build_conda.sh
Summary:
Remove temp channel for python 3.11, simplify logic around cuda
Pull Request resolved: https://github.com/pytorch/audio/pull/3250
Differential Revision: D44788219
fbshipit-source-id: 421ff9e0bf1818b41e395708cc4589d4a9c865bd
=> Remove temp channel for python 3.11, simplify logic around cuda (#3250)

packaging/torchaudio/meta.yaml
Summary:
Similar to what we used to have here:
https://github.com/pytorch/test-infra/pull/3896/files
Pull Request resolved: https://github.com/pytorch/audio/pull/3302
Reviewed By: nateanl
Differential Revision: D45574845
fbshipit-source-id: 142c35dfd811a5f5c170dcd082bec8d055edd9cb
=> Add older mkl build contraint only (#3302)

torchaudio/models/wav2vec2/components.py
Reference in fairseq: https://github.com/facebookresearch/fairseq/blob/main/fairseq/data/data_utils.py#L489
=> Fix type casting issue in mask length calculation

torchaudio/functional/_alignment.py
Optimizes merge_tokens method as discussed in #3614
close #3614
=> Optimize merge_tokens method

torchaudio/prototype/models/__init__.py
In file: __init__.py, the list named `__all__` contains an undefined name which can result in errors when this module is imported. I removed the undefined name (`conv_tasnet_base`) from the list. For more information regarding `__all__`, please read about [importing fields from a package](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).  
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve …
=> Remove an undefined name

torchaudio/datasets/utils.py
Resolves https://github.com/pytorch/audio/issues/3621
=> Fix logging in dataset download utilities

.github/workflows/build_docs.yml
Currently, nightly documentation is pushed automatically for each commit and on daily basis.
For release, automating it is tricky because we need to ensure that the version number is properly updated.
(removing alpha suffix at branch cut time and updating minor version at minor release)
For this reason, in release/2.1 we used manual-trigger to build and deploy doc for release.
This commit back port it to main.
For each release, once the version number is updated, running build_doc job from GHA will deploy the documentation automatically.
=> Add automated doc flow for release

docs/source/conf.py
Change the stable version specified in `docs/source/conf.py` so that breadcrumbs display correctly on TorchAudio documentation pages. I tested on the nightly build using the docs build preview, and tested on the release by building locally on my MBP. See attached screenshots.
=> Fix breadcrumbs for v2.1

src/libtorchaudio/pybind/pybind.cpp, src/libtorchaudio/utils.cpp, src/libtorchaudio/utils.h, src/torchaudio/_backend/utils.py, src/torchaudio/_extension/__init__.py, src/torchaudio/_extension/utils.py, src/torchaudio/io/_playback.py, src/torchaudio/io/_stream_reader.py, src/torchaudio/io/_stream_writer.py, src/torchaudio/utils/ffmpeg_utils.py, test/torchaudio_unittest/common_utils/__init__.py, test/torchaudio_unittest/common_utils/case_utils.py, test/torchaudio_unittest/io/stream_reader_test.py, test/torchaudio_unittest/io/stream_writer_test.py
Summary:
Update the logic to initialize FFmpeg extension so that it's not initialized until the user code accesses any attribute.
- Utilizes lazy module mechanism.
- Get rid of decorators for failure message (simply rely on the lazy initialization mechanism)
Now that all the attributes in `torchaudio.io` are importable without side-effect.
Differential Revision: D50193749
=> Simplify the logic to initialize FFmpeg

src/libtorchaudio/sox/effects.cpp, src/libtorchaudio/sox/io.cpp, src/libtorchaudio/sox/pybind/pybind.cpp, src/torchaudio/_backend/sox.py, src/torchaudio/_backend/utils.py, src/torchaudio/_extension/__init__.py, src/torchaudio/_extension/utils.py, src/torchaudio/backend/_sox_io_backend.py, src/torchaudio/functional/functional.py, src/torchaudio/sox_effects/sox_effects.py, src/torchaudio/utils/sox_utils.py, test/torchaudio_unittest/backend/dispatcher/sox/load_test.py, test/torchaudio_unittest/backend/sox_io/load_test.py, test/torchaudio_unittest/common_utils/case_utils.py
Differential Revision: D50197331
=> Simplify the logic to initialize sox

src/torchaudio/pipelines/_wav2vec2/impl.py
Address #3347 
The `encoder_layer_norm_first` should be set to `True` for the Large model of WavLM.
=> Fix WAVLM_LARGE bundle

setup.py
So that release engineering team does not have to manually remove prototype-related things in each release
=> Do not autoremove prototype in release branch

test/torchaudio_unittest/backend/dispatcher/dispatcher_test.py, test/torchaudio_unittest/backend/dispatcher/ffmpeg/save_test.py, test/torchaudio_unittest/backend/dispatcher/sox/save_test.py, torchaudio/_backend/backend.py, torchaudio/_backend/ffmpeg.py, torchaudio/_backend/soundfile.py, torchaudio/_backend/sox.py, torchaudio/_backend/utils.py
Differential Revision: D50367721
Pull Request resolved: https://github.com/pytorch/audio/pull/3662
=> Cherry-pick 2.1.1: Support compression level in i/o dispatcher backend

src/torchaudio/models/decoder/__init__.py
Summary: Fix __all__ in `torchaudio.models.decoder`
Differential Revision: D50602496
=> Fix cuctc module

src/torchaudio/functional/filtering.py, test/torchaudio_unittest/transforms/sox_compatibility_test.py, test/torchaudio_unittest/transforms/transforms_test_impl.py
fix #3668 
Return empty result when not `has_triggered`.
Zeroed wav audio added to unit test.
=> Fix vad to return zero output for zero input

.github/scripts/unittest-linux/run_test.sh, .github/scripts/unittest-windows/run_test.sh
PyTorch lightening is having issue with the nightly PyTorch. Let the other tests still run.
=> Make pytest run ignoring the ones with collection error

.github/workflows/build_docs.yml
Back port from release/2.1 branch.
Need to git-fetch source code to get the version number dynamically
=> Fix release doc deployment

.github/workflows/build_wheels_macos.yml
Fix an issue after https://github.com/pytorch/audio/pull/3583 . Remove reference to nightly branch for macos x86 builds
=> Fix typo in release only chnanges - remove nightly branch for MacOS x86

.github/workflows/build-wheels-m1.yml
=> Use oidc for wheel workflows, remove aws credentials

.github/workflows/build-wheels-m1.yml, .github/workflows/build_wheels_aarch64_linux.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_macos.yml, .github/workflows/build_wheels_windows.yml
This is not needed anymore after https://github.com/pytorch/test-infra/pull/4865.
=> Remove AWS credentials on workflows

.github/workflows/build-conda-m1.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/ffmpeg.yml
There is a new label for our macOS runners: "macos-m1-stable". All runners labeled "macos-m1-12" should be switched to "macos-m1-stable". [Here](https://fb.workplace.com/groups/pytorch.dev.perf.infra.teams/permalink/7546708885348237/) you can find more detailed info.
=> Migrate the macOS runners label from macos-m1-12 to macos-m1-stable

src/libtorchaudio/forced_align/cpu/compute.cpp, src/libtorchaudio/forced_align/gpu/compute.cu
This PR addresses https://github.com/pytorch/audio/issues/3747. The lengths of `targets` and `log_probs` should be reversed.
=> Fix document for forced_align method

src/libtorio/ffmpeg/stream_reader/stream_processor.h, src/libtorio/ffmpeg/stream_reader/stream_reader.cpp, src/libtorio/ffmpeg/stream_reader/stream_reader.h, src/libtorio/ffmpeg/stream_writer/encode_process.cpp, src/libtorio/ffmpeg/stream_writer/encode_process.h, src/libtorio/ffmpeg/stream_writer/stream_writer.cpp, src/libtorio/ffmpeg/stream_writer/stream_writer.h, src/libtorio/ffmpeg/stream_writer/types.h
Summary: `c10::optional` was switched to be `std::optional` after PyTorch moved to C++17. Let's eliminate `c10::optional`, if we can.
Reviewed By: albanD
Differential Revision: D57294285
=> [codemod] c10::optional -> std::optional in pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_processor.h +20

docs/source/libtorio.stream_reader.rst, docs/source/libtorio.stream_writer.rst, src/libtorchaudio/rnnt/autograd.cpp, src/libtorchaudio/rnnt/compute.cpp, src/libtorchaudio/rnnt/compute.h, src/libtorchaudio/rnnt/cpu/compute.cpp, src/libtorchaudio/rnnt/gpu/compute.cu
Summary: `c10::optional` was switched to be `std::optional` after PyTorch moved to C++17. Let's eliminate `c10::optional`, if we can.
Reviewed By: albanD
Differential Revision: D57294284
=> [codemod] c10::optional -> std::optional in pyspeech/experimental/csrc/decoders/TransducerDecoder.h +20

src/libtorchaudio/sox/effects.cpp, src/libtorchaudio/sox/effects.h, src/libtorchaudio/sox/io.cpp, src/libtorchaudio/sox/io.h, src/libtorchaudio/sox/types.cpp, src/libtorchaudio/sox/types.h, src/libtorchaudio/sox/utils.cpp, src/libtorchaudio/sox/utils.h, src/libtorchaudio/utils.cpp, src/libtorchaudio/utils.h, src/libtorio/ffmpeg/ffmpeg.cpp, src/libtorio/ffmpeg/ffmpeg.h, src/libtorio/ffmpeg/pybind/pybind.cpp, src/libtorio/ffmpeg/stream_reader/buffer/chunked_buffer.cpp, src/libtorio/ffmpeg/stream_reader/buffer/chunked_buffer.h, src/libtorio/ffmpeg/stream_reader/buffer/unchunked_buffer.cpp, src/libtorio/ffmpeg/stream_reader/buffer/unchunked_buffer.h, src/libtorio/ffmpeg/stream_reader/post_process.cpp, src/libtorio/ffmpeg/stream_reader/post_process.h, src/libtorio/ffmpeg/stream_reader/stream_processor.cpp
Summary: `c10::optional` was switched to be `std::optional` after PyTorch moved to C++17. Let's eliminate `c10::optional`, if we can.
Reviewed By: albanD
Differential Revision: D57294298
=> [codemod] c10::optional -> std::optional in pytorch/audio/src/libtorchaudio/sox/effects.cpp +20

.github/workflows/build-conda-m1.yml, .github/workflows/build-conda-windows.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/build_conda_linux.yml, .github/workflows/build_docs.yml, .github/workflows/build_wheels_aarch64_linux.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_windows.yml, .github/workflows/ffmpeg.yml, .github/workflows/lint.yml, .github/workflows/unittest-linux-cpu.yml, .github/workflows/unittest-linux-gpu.yml, .github/workflows/unittest-macos-cpu.yml, .github/workflows/unittest-windows-cpu.yml, .github/workflows/unittest-windows-gpu.yml
```
for i in .github/workflows/*.yml; do sed -i -e s#@main#@release/2.4# $i; done
```
```
find . | grep .yml | xargs sed -i "s/test-infra-ref: main/test-infra-ref: release\/2.4/g"
```
=> [Release only] release 2.4 changes

.github/workflows/build_wheels_linux.yml
Add xpu linux wheel build for torchaudio to complete xpu nightly wheels build after PR https://github.com/pytorch/test-infra/pull/5489 landed. Works for https://github.com/pytorch/pytorch/issues/114850
=> Add xpu linux wheel build into torchaudio build matrix

docs/source/refs.bib, src/libtorchaudio/lfilter.cpp, src/torchaudio/functional/filtering.py
This PR update the backpropagation computation of `DifferentiableIIR`.
The update is based on my recent work (https://arxiv.org/abs/2406.05128), which uses just one `DifferentiableIIR::apply` instead of two to compute the gradients for both input and `a_coeffs`. The algorithm has been tested in [torchlpc](https://github.com/yoyololicon/torchlpc). 
Below is the benchmark to version 2.4.1 `lfilter`.
The backward computation runs slightly faster especially when using just one thread.
```
[-------------- IIR filter -------------]
|  forward  |  backward
1 threads: ------------------------------
[32, 256]   |    404.0  |   1104.5
[32, 1024]  |    694.3  |   1783.2
[32, 4096]  |   2637.1  |   6579.2
2 threads: ------------------------------
[32, 256]   |    381.5  |   1110.2
[32, 1024]  | …
```
=> feat: reduce computations in backprop of `lfilter`

src/libtorchaudio/cuctc/include/ctc_prefix_decoder.h, src/libtorchaudio/cuctc/include/ctc_prefix_decoder_host.h, src/libtorchaudio/cuctc/src/bitonic_topk/bitonic_sort.cuh, src/libtorchaudio/cuctc/src/bitonic_topk/pow2_utils.cuh, src/libtorchaudio/cuctc/src/bitonic_topk/warpsort_topk.cuh, src/libtorchaudio/cuctc/src/ctc_prefix_decoder.cpp, src/libtorchaudio/cuctc/src/ctc_prefix_decoder_kernel_v2.cu, src/libtorchaudio/cuctc/src/device_data_wrap.h
Summary: Continue to hipify more torchaudio targets.
Differential Revision: D64298970
=> [AMD] Hipify torchaudio_decoder

test/torchaudio_unittest/prototype/functional/dsp_utils.py
Summary:
X-link: https://github.com/pytorch/opacus/pull/680
X-link: https://github.com/pytorch/captum/pull/1387
X-link: https://github.com/pytorch/botorch/pull/2584
This replaces uses of `numpy.ndarray` in type annotations with `numpy.typing.NDArray`. In Numpy-1.24.0+ `numpy.ndarray` is annotated as generic type. Without template parameters it triggers static analysis errors: 
```counterexample
Generic type `ndarray` expects 2 type parameters.
```
`numpy.typing.NDArray` is an alias that provides default template parameters.
Differential Revision: D64619891
=> [CODEMOD][pytorch] replace uses of np.ndarray with npt.NDArray (#3845)

src/libtorio/ffmpeg/stream_reader/stream_reader.h, src/libtorio/ffmpeg/stream_writer/stream_writer.h
Summary:
X-link: https://github.com/pytorch/ao/pull/1151
X-link: https://github.com/facebookincubator/AITemplate/pull/1032
Reviewed By: houseroad
Differential Revision: D64835967
=> c10::nullopt -> std::nullopt

.github/workflows/build_docs.yml, .github/workflows/ffmpeg.yml, .github/workflows/lint.yml, .github/workflows/unittest-linux-cpu.yml, .github/workflows/unittest-linux-gpu.yml
After : https://github.com/pytorch/test-infra/pull/5902
=> Migrate towards linux_lob_v2.yml

src/torchaudio/functional/filtering.py
Summary: When `pos - samplesLen_ns + flushedLen_ns < 0`, there should be no trimming at all. Before this fix, the negative index would result in incorrect trimming that wraps around the audio from its end.
Differential Revision: D67155973
=> Fix incorrect audio trimming with negative index

.github/workflows/integration-test.yml
As we no longer build PyTorch for 3.8
=> Update integration-test.yml to Python 3.9

.github/workflows/build-conda-m1.yml, .github/workflows/build-conda-windows.yml, .github/workflows/build-wheels-m1.yml, .github/workflows/build_conda_linux.yml, .github/workflows/build_docs.yml, .github/workflows/build_wheels_aarch64_linux.yml, .github/workflows/build_wheels_linux.yml, .github/workflows/build_wheels_windows.yml, .github/workflows/ffmpeg.yml, .github/workflows/lint.yml, .github/workflows/unittest-linux-cpu.yml, .github/workflows/unittest-linux-gpu.yml, .github/workflows/unittest-macos-cpu.yml, .github/workflows/unittest-windows-cpu.yml, .github/workflows/unittest-windows-gpu.yml
```
for i in .github/workflows/*.yml; do sed -i -e s#@main#@release/2.6# $i; done
find . | grep .yml | xargs sed -i "s/test-infra-ref: main/test-infra-ref: release\/2.6/g"
```
=> [Release only] release 2.6 changes

src/torchaudio/functional/filtering.py, test/torchaudio_unittest/transforms/transforms_test_impl.py
Differential Revision: D67532573
=> Fix vad return zero output when nonzero pre_trigger_time is requested

cmake/TorchAudioHelper.cmake
See documentation:
https://cmake.org/cmake/help/latest/module/FindPython3.html 
Successful workflow:
https://github.com/pytorch/test-infra/actions/runs/13381336461/job/37371953479?pr=6
We would need to bump cmake version to 3.31.2 in test-infra.
Please see: https://github.com/pytorch/test-infra/pull/6298
=> Enable 3.13t builds on Windows

cmake/LoadHIP.cmake, tools/setup_helpers/extension.py
Added changes for Windows in LoadHIP.cmake:
- set default ROCM_PATH and HIP_PATH for Windows case
- update CMAKE_MODULE_PATH with appropriate HIP path - because the find_package call to this module uses the Module mode search
- added code for finding HIP version
- skipped find hsa-runtime64, rccl packages on Windows case
- skipped find rccl, roctx and roctracer libraries on Windows case
CMAKE_C_COMPILER and CMAKE_CXX_COMPILER redefinition on Windows case (if we are building with ROCm on Windows we need to use compiler specified with CXX and CC flags instead of cl)
=> [ROCm][Windows] Enable build with ROCm on Windows

docs/source/installation.rst
The compatibility matrix does not include the latest few builds of TorchAudio, the SoundFile link in broken. This change updates both issues.
=> Update Compatibility Matrix and SoundFile link in installation documentation

examples/hubert/dataset/hubert_dataset.py, examples/self_supervised_learning/data_modules/_utils.py
Summary:
X-link: https://github.com/ctrl-labs/src2/pull/46874
Numpy-2 removed `string_`, with guidance to use `bytes_` instead.
```
fbgs 'np.string_' -ls | xargs perl -pi -e 's,\bnp\.string_\b,np.bytes_,g'
```
Differential Revision: D74099774
=> [CODEDMOD] replace all uses of np.string_ with np.bytes_

.github/workflows/build_wheels_aarch64_linux.yml
Follow up after https://github.com/pytorch/test-infra/pull/6584
with-cuda on these jobs need to be enabled. I believe when CUDA aarch64 jobs where introduced the flag was not flipped however we have not noticed it since there was a bug in test infra generating the aarch64 builds. The PR: https://github.com/pytorch/test-infra/pull/6584 resolved this bug. As a followup we need to set the flag with-cuda: enabled.
=> Fix Linux aarch64 nightly builds. Set with-cuda: enabled

docs/source/build.linux.rst, docs/source/build.rst, docs/source/build.windows.rst
Fixes https://github.com/pytorch/pytorch/issues/149551
There are three instances that need to be updated with new instructions.
=> Removing conda installation references.

src/libtorchaudio/forced_align/gpu/compute.cu
Summary:
From canary diff: D74892205
```
[2025-05-19T14:52:37.259-07:00] Stderr:
fbcode/pytorch/audio/src/libtorchaudio/forced_align/gpu/compute.cu:237:5: error: variable 'indexScores' set but not used [-Werror,-Wunused-but-set-variable]
237 | int indexScores = 0;
|     ^
1 error generated.
```
Eliminate the unused variable indexScores in fbcode/pytorch/audio/src/libtorchaudio/forced_align/gpu/compute.cu to resolve the -Wunused-but-set-variable warning.
Differential Revision: D75027221
=> Remove Unused Variable indexScores from fbcode/pytorch/audio/src/libtorchaudio/forced_align/gpu/compute.cu

.github/scripts/unittest-linux/install.sh
We need to pin down numpy, scipy and PIL deps in unittests, otherwise we get cryptic [error](https://github.com/pytorch/audio/actions/runs/15609671867/job/43967331170?pr=3926) during test collection: 
```
ImportError: cannot import name 'NP_SUPPORTED_MODULES' from 'torch._dynamo.utils'
```
which, by printing this exception from torch core:
https://github.com/pytorch/pytorch/blob/eecaa0bbc6a39c89366f9ec97797479c27f6d760/torch/_dynamo/utils.py#L142-L143
reveals itself as a GLIBCXX error symbol error.
Tests are failing, but at least now they're running.
=> Fix CPU Linux unittest job - part 2

src/torchaudio/functional/__init__.py, src/torchaudio/functional/filtering.py, src/torchaudio/functional/functional.py, src/torchaudio/models/decoder/__init__.py, src/torchaudio/transforms/_transforms.py, test/torchaudio_unittest/common_utils/func_utils.py, test/torchaudio_unittest/functional/torchscript_consistency_impl.py
CP of https://github.com/pytorch/audio/pull/3959, adding more deprecations.
=> [release 2.8] cherry-pick

examples/tutorials/hybrid_demucs_tutorial.py
=> Remove call to mir_eval in demucs_tutorial

examples/tutorials/asr_inference_with_ctc_decoder_tutorial.py, examples/tutorials/asr_inference_with_cuda_ctc_decoder_tutorial.py, examples/tutorials/audio_data_augmentation_tutorial.py, examples/tutorials/audio_feature_augmentation_tutorial.py, examples/tutorials/audio_feature_extractions_tutorial.py, examples/tutorials/ctc_forced_alignment_api_tutorial.py, examples/tutorials/forced_alignment_tutorial.py, examples/tutorials/hybrid_demucs_tutorial.py, examples/tutorials/mvdr_tutorial.py, examples/tutorials/speech_recognition_pipeline_tutorial.py, examples/tutorials/squim_tutorial.py, src/torchaudio/models/decoder/_ctc_decoder.py, src/torchaudio/pipelines/_source_separation_pipeline.py, src/torchaudio/pipelines/_squim_pipeline.py, src/torchaudio/pipelines/rnnt_pipeline.py, src/torchaudio/utils/__init__.py, src/torchaudio/utils/download.py, test/integration_tests/conftest.py, test/integration_tests/prototype/vggish_pipeline_test.py
=> Rename download_asset to _download_asset

docs/source/index.rst, docs/source/models.decoder.rst
This commit reverts the removal of the links to the asr cuda ctc tutorial.
=> Revert "Disable asr cuda ctc tutorial (#4006)"

examples/tutorials/tacotron2_pipeline_tutorial.py
This PR allows the the tacotron tutorial to lose its deep-phonemizer dependency.
=> [TUTORIAL DEPENDENCY REMOVAL] Use char-based pipeline instead of phoneme one for tacotron tutorial

src/torchaudio/functional/functional.py, src/torchaudio/transforms/_transforms.py, test/torchaudio_unittest/functional/functional_impl.py
Summary:
tensor.item() causes CPU_GPU sync and degradates performance.
Avoid using .item() and rewrite mask_along_axis_iid to treat mask_value as a tensor
comparison https://fburl.com/mlhub/37l2ufrp
{F1980844270}
It increases SM U by 1%
{F1980890373}
{F1980890377}
Differential Revision: D79451615
=> [Pyspeech] avoid .item call in feature_processing

docs/source/index.rst, docs/source/torchaudio.rst, src/torchaudio/models/decoder/__init__.py
As in the title:
- restores docs/source/index.rst with tutorials and kaldi bits removed
- fixes detecting class when sphinx has mocked it (and `inspect.isclass` is not able to detect it)
Motivation: fixes documentation build CI
=> Fix issues in documentation build.

CONTRIBUTING.md
I missed one last reference to sox: it's in the `contributing.md` file. This PR removes it.
=> Remove reference to sox in CONTRIBUTING.md

.github/workflows/unittest-macos-cpu.yml
As in the title using the same workflow as in Linux CPU.
Missing torchcodec issue is iscovered in https://github.com/pytorch/audio/actions/runs/17685958020/job/50270778776?pr=4092
TODO in a follow-up:
- remove `.github/scripts/unittest-linux/{install.sh,run_test.h}` as unused
=> Add missing torchcodec dependency to MacOS M1 workflow.
